### ISSUE TITLE
Switching from Gled fork to Glitch Soc

### ISSUE THREAD

**Issue by vibhi19** [glitch-soc/mastodon#1005]
I just wanted to know, how i can switch from Gled fork to Glitch soc, it is juts like Update?

> su - mastodon
> git clone https://github.com/glitch-soc/mastodon.git && cd live
> git checkout master
> gem update --system
> bundle install
> yarn install --pure-lockfile
> then migrate db 
> RAILS_ENV=production bundle exec rails db:migrate
> 
> Then Precompile
> RAILS_ENV=production bundle exec rails assets:precompile
> restart all services
> sudo systemctl restart mastodon-*
> 

is it right or need some correction?

**Comment by ThibG** [comment]
You'd need to also copy/move `public/system`, or switch to glitch-soc from within the same path (add a remote and switch to it).
Otherwise, this should be pretty much it *but* I don't know what Gled's fork includes which might cause trouble.

Generally speaking, the instructions are available here: https://glitch-soc.github.io/docs/#how-to-install-and-update-glitch-soc

**Comment by vibhi19** [comment]
> You'd need to also copy/move `public/system`, or switch to glitch-soc from within the same path (add a remote and switch to it).
> Otherwise, this should be pretty much it _but_ I don't know what Gled's fork includes which might cause trouble.
> 
> Generally speaking, the instructions are available here: https://glitch-soc.github.io/docs/#how-to-install-and-update-glitch-soc

So above mentioned process which i added in first part is right or they need some correctness?
although i am moving within the same path.

**Comment by ThibG** [comment]
I'd rather do something like:
```sh
git remote add glitch-soc https://github.com/glitch-soc/mastodon.git
git fetch glitch-soc
git checkout -b glitch --track glitch-soc/master
bundle install && yarn install
RAILS_ENV=production SKIP_POST_DEPLOYMENT_MIGRATIONS=true bundle exec rails db:migrate
RAILS_ENV=production bundle exec rails assets:precompile
systemctl restart mastodon-{sidekiq,streaming}
systemctl reload mastodon-web
RAILS_ENV=production bundle exec rails db:migrate
```

**Comment by vibhi19** [comment]
Thanks, going to move right now

**Comment by vibhi19** [comment]
its working thanks alot for the help
