### ISSUE TITLE
Add support for web+ganarchy URLs and stuff

### ISSUE THREAD

**Issue by SoniEx2** [glitch-soc/mastodon#1014]
### Pitch

Add support for [web+whatever URLs](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler#Permitted_schemes), such as web+ganarchy:385e734a52e13949a7a5c71827f6de920dbfea43 (which, if I were to finish protocol handler support, would lead you to https://ganarchy.autistic.space/project/385e734a52e13949a7a5c71827f6de920dbfea43/ if you had my ganarchy instance as your web+ganarchy URI handler)

This should include the ability for admins to set a default handler for some of these as they so choose, with a per-user override so you can use your browser's instead of using the admin's choice.

### Motivation

I created ganarchy to give more power to users and take away power from developers. As such, it makes sense to allow instance admins to optionally curate which forks of a software their users are more likely to use, if the user so chooses. This is what I call "fediverse integration" - I'd like to integrate ganarchy and the fediverse.

Software is nothing without its users, so why do developers have so much power over the users?

Eh, in any case, I'm not here to advertise about ganarchy, just to ask for web URI support. This would be a pretty big deal for the fediverse.

**Comment by ThibG** [comment]
Web intents support is unfortunately too messy in current browsers to provide a nice user experience (the only way to register a handler makes a somewhat cryptic message appear, there does not seem to be a way to provide fallbacks, etc.)
Furthermore, this would be somewhat equivalent to accepting *any* protocol scheme (except for the purpose of auto-detecting links), and I'm uneasy with the implications.
I'm therefore closing this PR.

Also, I've been made aware by other project members that you have been banned from participating in this project, so I'm going to enforce this ban.
