### ISSUE TITLE
Add colors to privacy level icons

### ISSUE THREAD

**Issue by ThibG** [glitch-soc/mastodon#1015]
### Pitch

Add different colors to privacy level icons, in order to make them stand out.

### Motivation

It can be useful to tell at a glance which is the privacy level of a toot. We already have an icon for that, but adding different colors could be useful.
We probably should use the same colors as those used by sleeping town, ~~but I can't find their code~~. https://github.com/unascribed/sleeping.town/blob/master/public/sleeping/sleeping.css#L353-L371

Using their colors unmodified would yield this:
![image](https://user-images.githubusercontent.com/384364/56830399-84793680-6866-11e9-8973-55a60fd9d415.png)

**Comment by vibhi19** [comment]
Awesome we need this
