### ISSUE TITLE
Show replies and reboosts in local and public timelines

### ISSUE THREAD

**Issue by vibhi19** [glitch-soc/mastodon#1021]

**Comment by ThibG** [comment]
Can you be a bit more specific? :thinking:

**Comment by vibhi19** [comment]
> Can you be a bit more specific?

show all replies and reboost of local user in local timeline

**Comment by vibhi19** [comment]
Gled fork already has that so no need additional work  

https://github.com/gled-rs/mastodo

**Comment by ThibG** [comment]
I think that, unlike in Gled's Mastodo, we should make that configurable (ideally at the end-user level, but that would be more work/less efficient than admin-level I guess)

**Comment by vibhi19** [comment]
> I think that, unlike in Gled's Mastodo, we should make that configurable (ideally at the end-user level, but that would be more work/less efficient than admin-level I guess)

It will be less efficient if added on end user level. 

User wont feel any change and there will be more frequent update on local time  and more content to interact with.i used gled fork and it works real good and really useful

**Comment by vibhi19** [comment]
Thank You. is there any way to enable it by default
