### ISSUE TITLE
Issue with Getting Started page

### ISSUE THREAD

**Issue by phobos-dthorga** [glitch-soc/mastodon#1027]
Hello!

I've recently installed and successfully setup a Mastodon Glitch instance via docker-compose in conjunction with nginx and ElasticSearch, using the instructions mentioned below [ 1, 2 ] in order of importance. But whenever I visit the "Getting Started" page, I get the error displayed as shown in [ 3, 4 ].

[ 1 ] - https://github.com/ummjackson/mastodon-guide/blob/master/up-and-running.md
[ 2 ] - https://docs.joinmastodon.org/administration/installation/
[ 3 ] - https://imgur.com/a/AdLr6oB
[ 4 ] - https://paste.gekkofyre.io/view/48e9803e

I’m using SolusVM and a virtual machine just for this purpose, which has 6 vCPUs and 8 GB of RAM, along with 120 GB of SSD space. The dedicated server itself has 128 GB of DDR3 ECC RAM, a modern Intel Xeon CPU, etc. Basically it hosts a number of clients for our web-hosting company, GekkoFyre Networks, but still has enough spare resources for this VM instance. So really, I don't see a lack of resources being the issue unless more RAM is somehow required?

Or maybe it's to do with uniquely being a docker-compose setup? Any help on this matter would be sincerely appreciated, thank you.

**Comment by ThibG** [comment]
Thank you for your report!
This is not an issue with your setup but with glitch-soc's code, I will work on resolving it shortly.
