### ISSUE TITLE
Direct msg using JSXC 

### ISSUE THREAD

**Issue by vibhi19** [glitch-soc/mastodon#1035]
We all know that DM mentions are a great mess in mastodon. There is alot of talk over this but it never has been added. 

One on one msg feature is really important.
only Misskey has a Talk feature that lets you talk one on one right now it would be awesome if that support is added through JSXC. 
https://www.jsxc.org/

**Comment by yipdw** [comment]
JSXC is an XMPP client; you'd still need an XMPP server running somewhere.

In addition to the XMPP server, this would also require (at least):

1. A separate process to maintain an XMPP account for each local account.  (XMPP accounts and WebFinger addresses _look_ similar, but they are not the same.)
2. Some way to negotiate this capability with remote servers.  (What if the account you want to DM is on a server that does not support this XMPP-ActivityPub mapping thing?)

I'm not sure how all of the above straightens out the "great mess"; it seems like it just adds more stuff on.

**Comment by vibhi19** [comment]
Yes, One need to run an xmpp server.

There are patch which we can use to sync Mastodon account  and password with  xmpp so one has the same username as there mastodon username on JSXC.

There are some check can be run to see if certain server support it or not. It still will be useful for local user anyways.

well we can discuss thing to come to solution that is less complex and less messy

**Comment by ThibG** [comment]
I think this is outside the scope of the project, at least for now.
Therefore I'm closing this issue.
