### ISSUE TITLE
"Mark Media as Sensitive" toggle doesn't indicate whether it's selected

### ISSUE THREAD

**Issue by rtucker** [glitch-soc/mastodon#1039]
When I add an image (at least via mobile, with the glitch theme), there's no visible way to determine if the image has already been marked sensitive.

Examples:

![2019-05-09 20 57 06](https://user-images.githubusercontent.com/97437/57495658-408e2480-729d-11e9-885b-09e5db7b7ae3.png)
![2019-05-09 20 57 12](https://user-images.githubusercontent.com/97437/57495662-44ba4200-729d-11e9-8425-b1bbd556e1eb.png)

I think the second one is sensitive?  I had to do some trial-and-error.

This is on vulpine.club, merged up to 3191c3b I believe.

Thanks!

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
It is indeed the second one, and the only visible change is the color, which is far less than ideal.
That's what upstream does too, but we should definitely revisit that design. Not too sure how, though.

**Comment by ThibG** [comment]
Would #1042 work for you?

**Comment by rtucker** [comment]
Looks good in theory, waiting for it to build now :)

**Comment by rtucker** [comment]
Looks good to me.  Thanks!!
