### ISSUE TITLE
Port single-column changes from upstream

### ISSUE THREAD

**Issue by ThibG** [glitch-soc/mastodon#1066]
Upstream is currently making changes to the mobile layout to better support a single-column on regular computers, view similar to Twitter.

This is Work in Progress, but it would probably make sense to port some of those changes. Related commits:
- 9ddeb30f90f9402eb567c88354d4956fcfdf0361
- 84dc21d55d8627182ce201baeddb6fbbdf8748c2
- 1e5532e693d9533ee37f553aeb191e284178fa52
- 0e445ebb1392c8dbce320509d219f16c7c221406
- 4a818ac2deffaff9925ce5b160dbc5385b815a87
- 3593b854233da1dbb49e95c929019c60a53eca79
- 451e5980b609eca5b20041963aca0098508475d7
- 7c1ca0c37b7e68bd4e388afb3bca55d2b71fd2ad
- d93b82af87de90eaa29eb54a423722fb9fb45b38
- 6077eca240d3dc8765380c99896d85ab6e9c4ea9
- possibly c402c291f4991e2b021d8c13b557e6a8f650dcf3 and fe3bf3b0fc7c74ce12b48a4e03498c410bfd82f5?
- ed19f33440f4ccfe5323c6a8a67a345682652873
- cc8f6b3cdaca81be99875c27002e0280d1d88191
- possibly 9add88a920200bc0610b25434ad056469f28eae5?

**Comment by vibhi19** [comment]
The single column layout or simple mode also work on Desktop too. It will be really awesome as my user keep asking for single column ui.

and Also add a option to make it default i dont wanna go tell everyone to go to settings and make changes to have twitter like UI.
