### ISSUE TITLE
Upstream merge desync?

### ISSUE THREAD

**Issue by Reverite** [glitch-soc/mastodon#1069]
Looks like glitch-soc is up to date on upstream, but lib/mastodon/version.rb still states 2.8.2 despite being on 2.8.4? Not sure if some commits got lost somewhere.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
It's just that the version number has not been incremented in Mastodon's development branch until very recently (after the last merge, which includes all the fixes)

**Comment by Reverite** [comment]
Ah, didn't see that commit.

Sorry about that, wasn't sure 👍
