### ISSUE TITLE
"Show confirmation dialog before posting uncaptioned image" function doesn't seem to be working right

### ISSUE THREAD

**Issue by corrinr** [glitch-soc/mastodon#1077]
I've had this feature enabled for a while, and any time I forget to caption an image I don't see a confirmation dialog--the post just won't send, as if I didn't click the post button. I just got a report from a user who had the same issue, who tested it on Firefox with the setting enabled and on Chrome with it disabled and the posts on Firefox wouldn't send while the Chrome ones would. Usually once the image is captioned it will send, but it sometimes takes up to 15-30 seconds to register. 

ETA-- we're running a slightly older version of glitch so this may have been fixed in an update, but I couldn't find any recent commits about it!
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
In the absence of more information, I will just assume this has been fixed by https://github.com/glitch-soc/mastodon/pull/1041
If that's not the case, please reopen.

**Comment by corrinr** [comment]
ty, sorry I didn't see that PR when I searched! hopefully updating will fix the issue
