### ISSUE TITLE
"Show thread" link not visible in threads in Glitch theme

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#1080]
The "Show thread" link is not visible in toots with polls in ~vanilla~ Glitch theme on vulpine.club.

But it is visible on 2.8.0 on queer.party, which doesn't use Glitch, and on mastodon.social.

Edit: Oops, sorry, I am apparently using the Glitch theme on Vulpine Club but I forgot! So this bug is in Glitch, not vanilla.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
I cannot reproduce this. Maybe the parent toot was not known to the instance at the time you've seen the poll in vulpine.club?

**Comment by Cassolotl** [comment]
They were polls I posted myself on vulpine.club, I'm viewing them from my own account. 🈂️ 

For example, this toot: https://vulpine.club/@EmojiTetra/102187271077942436

Here's how it looks in the webUI:

![Screenshot 2019-05-31 at 10 45 20](https://user-images.githubusercontent.com/6607512/58697284-37badb00-8391-11e9-83dc-6877aa20e4d0.png)

![Screenshot 2019-05-31 at 10 45 45](https://user-images.githubusercontent.com/6607512/58697312-4608f700-8391-11e9-8a55-16ddd99aad67.png)

**Comment by Cassolotl** [comment]
It's also happening to me on dev.glitch.social on the glitch theme:

![Screenshot 2019-05-31 at 10 56 39](https://user-images.githubusercontent.com/6607512/58698215-d267e980-8392-11e9-98f9-1bc614809318.png)

**Comment by ThibG** [comment]
You're not using vanilla flavor. The thread thing isn't a thing in glitch flavor as I thought it was unnecessary and redundant with both the double-arrow thing and the speech bubble icon which both indicate that the toot is a reply.

**Comment by Cassolotl** [comment]
>The thread thing isn't a thing in glitch flavor

AHHHHHH now I feel silly. Thank you, and I'm sorry to have bothered you!

**Comment by ThibG** [comment]
np
