### ISSUE TITLE
thread/post notification silencing/unsubscribe

### ISSUE THREAD

**Issue by hoodiek** [glitch-soc/mastodon#11]
this is such a prevalent problem that i have seen it on twitter, and on mastodon, since before i ever knew what it meant. "my notifications exploded" and the like, all mean that a simple post got Too Popular and overwhelmed any ability to use the account as normal is impossible.

the solution is the ability to temporarily or permanently dismiss notifications from a certain thread.

as such, clicking on a post's action menu (the ... at the bottom) (at any level, base or reply, etc) should give us a "mute thread" option, with a list of three things to hide from any replies or actions on that post or it's successors in the thread.

- hide favorites
- hide boosts
- hide replies

all would presumably default to being checked when you click the mute thread button, and whenever a thread is currently muted, in the column options for your notifications, a button should be added to "view muted threads" that would show all notifications being hidden, and add a button beside each one to "unmute thread"

EDIT: in theory we do not want to load the notifications at all, they should not be sent to the client unless they request them by clicking view muted threads

**Comment by beatrix-bitrot** [comment]
thinking of closing this now that conversation muting is in mainline, any objections?
