### ISSUE TITLE
Change default layout to single column in web UI 

### ISSUE THREAD

**Issue by vibhi19** [glitch-soc/mastodon#1104]
can someone tell me how to achieve this?

**Comment by ThibG** [comment]
Change the `layout` property in `app/javascript/flavours/glitch/reducers/local_settings.js`.
But we don't have a proper single column layout yet. I mean, it's the mobile UI which stretches all the way.

**Comment by vibhi19** [comment]
Well Vanilla has Single column layout so i was thinking to set it as a default, can you add an option to do it.
People doesn't like multi column its overwhelming information for them so it can help me alot.

**Comment by ThibG** [comment]
You could try #1108. It will default to single column for new users, and that can be overridden in the local app settings.
I'm trying this a bit before merging, and it would be helpful to have other people try it as well.

**Comment by vibhi19** [comment]
looks like you already merged it

**Comment by ThibG** [comment]
Yes. Closing this issue too, since it's now the default.

**Comment by vibhi19** [comment]
Thanks

**Comment by vibhi19** [comment]
Hi, I Just updated and it has some issues, when You click on toots it isn't loading
