### ISSUE TITLE
New 'advanced web client' functionality seems to break Mobile View in app settings

### ISSUE THREAD

**Issue by adamemerson** [glitch-soc/mastodon#1114]
I've been using the 'Mobile View' option on Glitchsoc for a while. When mastodon added the option to disable the 'Advanced Web Client', I thought that I'd try it. It wasn't as good, so I tried turning advanced web client back on and re-enabling mobile view in Glitchsoc Application Settings

BUT NOW every time I check it, I get the non-advanced three-column view, rather than the single-column mobile view I should be. I've tried wiping my web browser's history/application data and relogging in, but the problem persists.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
The new single-column view with up to two panes is supposed to replace the old mobile view (and gracefully fall back to something like the older mobile view if the window is not wide enough), so it is expected.
I thought that new mode was an improvement over the old one in every way, so I'm curious about why you prefer the old behavior.

**Comment by adamemerson** [comment]
I have a visual impairment and I need my fonts to be reasonably large, so having an enforced horizontal/vertical split like this that I can't make go away means that the amount of text I can look at without having to scroll around whether reading or composing is Really Not Much.

Also, currently, when I have it zoomed in to a level that is comfortable to read, the compose column gets 'stuck' with much of its content up above the top of the screen and there's no real way to get at it without zooming back out to where it's not comfortable to read.

(For me personally, since I have a narrow visual field as well, 'swapping' between compose and other columns is less disruptive than 'scrolling' as the former requires a keystroke and the latter requires re-finding the mouse cursor, insertion point, and whatever text I was interested in.)

**Comment by ThibG** [comment]
> I have a visual impairment and I need my fonts to be reasonably large, so having an enforced horizontal/vertical split like this that I can't make go away means that the amount of text I can look at without having to scroll around whether reading or composing is Really Not Much.

Thanks for the explanation.

> Also, currently, when I have it zoomed in to a level that is comfortable to read, the compose column gets 'stuck' with much of its content up above the top of the screen and there's no real way to get at it without zooming back out to where it's not comfortable to read.

I can't seem to reproduce that, zooming (at least with Firefox's built-in zoom) works “the correct way”:
![zoom](https://user-images.githubusercontent.com/384364/59555255-fbea5d00-8faf-11e9-9a4e-f94f5c010b27.gif)

Is that behavior not suiting you, or is there something else I'm missing?

**Comment by adamemerson** [comment]
In my case, when I'm zoomed in and I click on the edit box, the compose column 'jumps' up and much of the content on top disappears above the top of the window
![masto](https://user-images.githubusercontent.com/458092/59556773-773f1500-8f96-11e9-9af7-af8b6e16b139.png)

**Comment by adamemerson** [comment]
Looking at it again, I thought that there was no way to compose at all when zoomed in all the way but it LOOKS like it's just a bit glitchy and if I jump around between columns a few times the 'pencil' icon comes back, which solves the major problem I was having.

(It would be nice if when zoomed in enough to get a single column the column took up the whole width of the viewport instead of having big margins on either side, though, but the MAIN problem I was having looks like it's not as bad as I first thought.)

**Comment by ThibG** [comment]
> In my case, when I'm zoomed in and I click on the edit box, the compose column 'jumps' up and much of the content on top disappears above the top of the window
> ![masto](https://user-images.githubusercontent.com/458092/59556773-773f1500-8f96-11e9-9af7-af8b6e16b139.png)

Oh ok, I can reproduce that. I don't think it's a big issue but it can be quite confusing… I suppose this may be an issue with the scrolling behavior. I will look into it.

> Looking at it again, I thought that there was no way to compose at all when zoomed in all the way but it LOOKS like it's just a bit glitchy and if I jump around between columns a few times the 'pencil' icon comes back, which solves the major problem I was having.

I can't reproduce this. However, the pencil icon is not displayed on every column: it's disabled on search, compose, getting started and toot view. That is on purpose but may be ill-advised?
Additionally, there was recently a bug in which the compose form wouldn't open automatically when hitting “reply” or “delete & redraft” on mobile. This has been fixed.

> (It would be nice if when zoomed in enough to get a single column the column took up the whole width of the viewport instead of having big margins on either side, though, but the MAIN problem I was having looks like it's not as bad as I first thought.)

Ok, I will look into it as well. I'm afraid this wouldn't look that well, though, and I'm not sure how it helps with your narrow field of vision?
I guess in the worst case I can add another option if that helps.

**Comment by ThibG** [comment]
The weird scrolling behavior when clicking on the compose form has been fixed.

With regards to the single column taking the whole width of the viewport, I opened #1122, but I'm really unsure about it.

**Comment by ThibG** [comment]
I believe this issue has been addressed with the changes to the UI since the addition of that single-column mode. Please reopen with more explanations if you are still not satisfied with it!
