### ISSUE TITLE
rich text presentation issues

### ISSUE THREAD

**Issue by BenLubar** [glitch-soc/mastodon#1118]
Formatting doesn't appear at all on the public frontend (https://mastodon.lubar.me/@ben/102282023190299480)

Lists only have padding above them, never below, in the web UI.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
Appropriate styling is only available in the glitch flavour, and it seems your instance defaults on the vanilla flavour.

**Comment by BenLubar** [comment]
Ah, I didn't know there was a site-wide setting. That part is fixed, but the list bottom margin is still very ugly.

**Comment by ThibG** [comment]
The margins thing should be addressed by #1126
