### ISSUE TITLE
Limitation on audio upload

### ISSUE THREAD

**Issue by vibhi19** [glitch-soc/mastodon#1124]
Just curious about the limitation by default on audio files, and is there doc where you document these changes so people can look it up and dont ask here like me.

**Comment by vibhi19** [comment]
Can anyone tell me something about this @ThibG

**Comment by ThibG** [comment]
`MAX_AUDIO_LENGTH` is how you change it, it is documented in `.env.production.sample`

**Comment by vibhi19** [comment]
Well i wanted to know default limit, i seen the sample file actully

**Comment by ThibG** [comment]
The default limit is 60 seconds.
