### ISSUE TITLE
Columns have uneven spacing with screen

### ISSUE THREAD

**Issue by slice** [glitch-soc/mastodon#1130]
I updated to 5ea45351a today and it looks like the columns' spacing in advanced mode are borked somehow:

![image](https://user-images.githubusercontent.com/4206232/59737574-035d7080-9213-11e9-8ae9-c1096be76342.png)

The compose drawer has uneven padding, while the rest of the columns don't have any at all, and touch the edges of the screen.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
Hm, what browser are you using, and how wide is your screen? I cannot reproduce this.
These CSS rules should apply to the column: https://github.com/glitch-soc/mastodon/blob/5ea45351a0c3258a4e783e9f9b570e24b9c58d78/app/javascript/flavours/glitch/styles/components/index.scss#L566-L580

**Comment by slice** [comment]
Agh. Looks like I messed up when handling conflicts. 😓 Sorry for the trouble.
