### ISSUE TITLE
Adding Profile Card in Glitch Flavor 

### ISSUE THREAD

**Issue by vibhi19** [glitch-soc/mastodon#1131]
![Profile card](https://user-images.githubusercontent.com/31093426/59742867-44459b80-928c-11e9-9752-b8230d677bde.JPG)
 
As Vanilla Show a Profile card in Hamburger menu, can we also add it in Glitch too its really handy  for new user who join via mobile as one of my friend keep finding a way to edit profile. 

and Rename Preference option to Settings its less confusing for new user.

**Comment by ThibG** [comment]
> As Vanilla Show a Profile card in Hamburger menu, can we also add it in Glitch too its really handy for new user who join via mobile as one of my friend keep finding a way to edit profile.

Right, adding that.

> and Rename Preference option to Settings its less confusing for new user

I'm sorry, I can't see how

**Comment by vibhi19** [comment]
Thank you, You are awesome, as of Preference, All those option in twitter/or any other social are behind setting option, i dont want make big changes Just rename it in menu, URL and everything will rename the same.

it will also help them in certain way if they want to change password or email.

**Comment by ThibG** [comment]
I really don't think we should do this.

**Comment by vibhi19** [comment]
Think Like a user who just joined, Here is a small story I asked my friends to join they were finding a way to upload image but as i set glitch to default there wasn't the option of Profile in menu(which you added) and They didn't know preference will take them to settings. so its better to rename it to setting the new user will know that they can find all those option behind setting, just rename it in menu everything will be the same..

**Comment by ThibG** [comment]
Preferences leads to preferences. It's the same as upstream. I really don't know what to say more, and I honestly don't think changing it is worth having to maintain yet another change with upstream.

**Comment by vibhi19** [comment]
Yeah You need to maintain it, that is True, it can be done via css or not? if yes Help me with CSS if You can
