### ISSUE TITLE
Number in notification icon

### ISSUE THREAD

**Issue by vibhi19** [glitch-soc/mastodon#1132]
when there is no new notification, sometime it show 15 notification on icon its really annoying and weird 
![Notification](https://user-images.githubusercontent.com/31093426/59743079-dbaaee80-928c-11e9-9b32-6c546f44cfc1.JPG)

**Comment by vibhi19** [comment]
@thibg Can you tell me what is the issue with notification

**Comment by ashkitten** [comment]
we don't currently keep track of what notifications are read server-side, so every time you reload the page it will assume all loaded notifications are unread.

**Comment by vibhi19** [comment]
> we don't currently keep track of what notifications are read server-side, so every time you reload the page it will assume all loaded notifications are unread.

I used vanilla mastodon and i dont see this issue there why?

**Comment by ashkitten** [comment]
vanilla mastodon does not display an unread count at all. you can disable the unread count in local settings with the glitchsoc web ui.

**Comment by vibhi19** [comment]
> vanilla mastodon does not display an unread count at all. you can disable the unread count in local settings with the glitchsoc web ui.

Now i understand Thanks for the help. i am closing it now

**Comment by ThibG** [comment]
Actually, both vanilla and glitch-soc have this counter, but they differ on how it is counted, which basically leads vanilla to count all notifications existing on page load as counted, while glitch counts them as unread.

**Comment by ashkitten** [comment]
oh, interesting. maybe we can copy their behavior then?

**Comment by vibhi19** [comment]
Yeah Please do that
