### ISSUE TITLE
Remove Padding from Glitch Soc Theme

### ISSUE THREAD

**Issue by vibhi19** [glitch-soc/mastodon#1136]
There is Padding Under navigation bar Please remove it as it looks alot better and new without it (similar to new vanilla )

![Padding](https://user-images.githubusercontent.com/31093426/59968126-21e4a400-9552-11e9-93cc-167f5d39f4bb.png)
![No padding](https://user-images.githubusercontent.com/31093426/59968132-3de84580-9552-11e9-9cd2-870923d0798c.png)

Screenshot used here has nothing to do with me.

**Comment by ThibG** [comment]
Upstream has exactly the same behavior, but with a different breakpoint. I'll investigate if it makes sense to use upsream's breakpoint and how to do that exactly.

**Comment by vibhi19** [comment]
Thanks
