### ISSUE TITLE
Issue with Elastic search

### ISSUE THREAD

**Issue by vibhi19** [glitch-soc/mastodon#1139]
I am asking it here because i could not find any answer on forum or internet, The problem is that I removed the es completely from our server, but sidekiq still show these task in retries they are in hundred which make me a little worry, Can someone tell me how to stop them. 

![Sidekiq](https://user-images.githubusercontent.com/31093426/60076471-4785cf00-9745-11e9-80f4-113ce07e9681.JPG)

**Comment by rhaamo** [comment]
do you have deactivated ES in .env too ?

**Comment by vibhi19** [comment]
Yes I removed it from .env file too

**Comment by vibhi19** [comment]
A reboot seems to have done the Job
