### ISSUE TITLE
Data exports don't work if local-only statuses have been posted

### ISSUE THREAD

**Issue by unascribed** [glitch-soc/mastodon#1153]
Attempting to create a data export if you have ever posted a local status fails with the following error:

```
sidekiq_1    | 2019-07-05T19:16:46.440Z 6 TID-ovq8afv76 BackupWorker JID-0331e1ecc913c6f672bb0ba8 INFO: fail: 1.918 sec
sidekiq_1    | 2019-07-05T19:16:46.440Z 6 TID-ovq8afv76 WARN: {"context":"Job raised exception","job":{"class":"BackupWorker","args":[60],"retry":5,"queue":"pull","backtrace":true,"dead":false,"jid":"0331e1ecc913c6f672bb0ba8","created_at":1562354204.521802,"enqueued_at":1562354204.5218463},"jobstr":"{\"class\":\"BackupWorker\",\"args\":[60],\"retry\":5,\"queue\":\"pull\",\"backtrace\":true,\"dead\":false,\"jid\":\"0331e1ecc913c6f672bb0ba8\",\"created_at\":1562354204.521802,\"enqueued_at\":1562354204.5218463}"}
sidekiq_1    | 2019-07-05T19:16:46.440Z 6 TID-ovq8afv76 WARN: Mastodon::NotPermittedError: Local-only statuses should not be serialized
sidekiq_1    | 2019-07-05T19:16:46.440Z 6 TID-ovq8afv76 WARN: /opt/mastodon/app/serializers/activitypub/note_serializer.rb:28:in `id'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:387:in `read_attribute_for_serialization'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer/field.rb:25:in `value'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:340:in `block in attributes'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:337:in `each'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:337:in `each_with_object'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:337:in `attributes'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:400:in `attributes_hash'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:368:in `serializable_hash'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer/association.rb:58:in `serializable_hash'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:410:in `block in associations_hash'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:357:in `yield'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:357:in `block (2 levels) in associations'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:352:in `each'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:352:in `block in associations'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:408:in `each'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:408:in `each_with_object'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:408:in `associations_hash'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:369:in `serializable_hash'
sidekiq_1    | /opt/mastodon/app/lib/activitypub/adapter.rb:35:in `serializable_hash'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/adapter/base.rb:61:in `as_json'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/serializable_resource.rb:10:in `as_json'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:71:in `block (3 levels) in notify'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:24:in `block (3 levels) in instrument_rendering'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:81:in `block in notify_render'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:80:in `notify_render'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:23:in `block (2 levels) in instrument_rendering'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:97:in `block in tag_logger'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:97:in `tag_logger'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:22:in `block in instrument_rendering'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `instance_exec'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:70:in `block (2 levels) in notify'
sidekiq_1    | /opt/mastodon/app/services/backup_service.rb:153:in `serialize'
sidekiq_1    | /opt/mastodon/app/services/backup_service.rb:23:in `block (2 levels) in build_json!'
sidekiq_1    | /opt/mastodon/app/services/backup_service.rb:22:in `each'
sidekiq_1    | /opt/mastodon/app/services/backup_service.rb:22:in `block in build_json!'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:238:in `block in in_batches'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:222:in `loop'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:222:in `in_batches'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:135:in `find_in_batches'
sidekiq_1    | /opt/mastodon/app/services/backup_service.rb:21:in `build_json!'
sidekiq_1    | /opt/mastodon/app/services/backup_service.rb:12:in `call'
sidekiq_1    | /opt/mastodon/app/workers/backup_worker.rb:21:in `perform'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:192:in `execute_job'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:165:in `block (2 levels) in process'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
sidekiq_1    | /opt/mastodon/app/lib/sidekiq_error_handler.rb:5:in `call'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-unique-jobs-6.0.13/lib/sidekiq_unique_jobs/server/middleware.rb:29:in `call'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:164:in `block in process'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:109:in `local'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/rails.rb:43:in `block in call'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:73:in `block in wrap'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:72:in `wrap'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/rails.rb:42:in `call'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:250:in `stats'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_logger.rb:8:in `call'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:74:in `global'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:125:in `block in dispatch'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:48:in `with_context'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:124:in `dispatch'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:163:in `process'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:83:in `process_one'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:71:in `run'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:16:in `watchdog'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by ThibG** [comment]
#1154 should fix it. Are you able to test it to make sure?

**Comment by unascribed** [comment]
Yeah, that PR fixes it.

**Comment by joyeusenoelle** [comment]
I'm getting the same error on the most recent glitchsoc release. I can confirm that the changes from #1154 are present. Here's the trace, in case it's useful:

`2020-05-21T12:50:46.040Z pid=985 tid=gn4977nt9 class=BackupWorker jid=2900c5fce20c36054c6f37ef elapsed=54.857 INFO: fail
2020-05-21T12:50:46.045Z pid=985 tid=gn4977nt9 WARN: {"context":"Job raised exception","job":{"retry":5,"queue":"pull","backtrace":true,"dead":false,"class":"BackupWorker","args":[53],"jid":"2900c5fce20c36054c6f37ef","created_at":1590064342.0131788,"enqueued_at":1590065391.1834857,"error_message":"Local-only statuses should not be serialized","error_class":"Mastodon::NotPermittedError","failed_at":1590064408.1147327,"retry_count":4,"error_backtrace":...
2020-05-21T12:50:46.047Z pid=985 tid=gn4977nt9 WARN: Mastodon::NotPermittedError: Local-only statuses should not be serialized
2020-05-21T12:50:46.047Z pid=985 tid=gn4977nt9 WARN: /home/mastodon/live/app/serializers/activitypub/note_serializer.rb:29:in 'id'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:395:in 'read_attribute_for_serialization'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer/field.rb:25:in 'value'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:340:in 'block in attributes'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:337:in 'each'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:337:in 'each_with_object'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:337:in 'attributes'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:408:in 'attributes_hash'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:371:in 'serializable_hash'
/home/mastodon/live/app/lib/activitypub/serializer.rb:36:in 'serializable_hash'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer/association.rb:58:in 'serializable_hash'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:418:in 'block in associations_hash'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:357:in 'yield'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:357:in 'block (2 levels) in associations'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:352:in 'each'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:352:in 'block in associations'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:416:in 'each'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:416:in 'each_with_object'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:416:in 'associations_hash'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model/serializer.rb:372:in 'serializable_hash'
/home/mastodon/live/app/lib/activitypub/serializer.rb:36:in 'serializable_hash'
/home/mastodon/live/app/lib/activitypub/adapter.rb:40:in 'serializable_hash'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model_serializers/adapter/base.rb:61:in 'as_json'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model_serializers/serializable_resource.rb:10:in 'as_json'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model_serializers/logging.rb:71:in 'block (3 levels) in notify'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:109:in 'block in run_callbacks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model_serializers/logging.rb:24:in 'block (3 levels) in instrument_rendering'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model_serializers/logging.rb:81:in 'block in notify_render'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in 'instrument'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model_serializers/logging.rb:80:in 'notify_render'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model_serializers/logging.rb:23:in 'block (2 levels) in instrument_rendering'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model_serializers/logging.rb:97:in 'block in tag_logger'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in 'block in tagged'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:28:in 'tagged'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in 'tagged'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model_serializers/logging.rb:97:in 'tag_logger'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model_serializers/logging.rb:22:in 'block in instrument_rendering'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:118:in 'instance_exec'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:118:in 'block in run_callbacks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:136:in 'run_callbacks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.10/lib/active_model_serializers/logging.rb:70:in 'block (2 levels) in notify'
/home/mastodon/live/app/services/concerns/payloadable.rb:7:in 'serialize_payload'
/home/mastodon/live/app/services/backup_service.rb:25:in 'block (2 levels) in build_json!'
/home/mastodon/live/app/services/backup_service.rb:24:in 'each'
/home/mastodon/live/app/services/backup_service.rb:24:in 'block in build_json!'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:136:in 'block in find_in_batches'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:238:in 'block in in_batches'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in 'loop'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in 'in_batches'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:135:in 'find_in_batches'
/home/mastodon/live/app/services/backup_service.rb:23:in 'build_json!'
/home/mastodon/live/app/services/backup_service.rb:14:in 'call'
/home/mastodon/live/app/workers/backup_worker.rb:25:in 'perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:196:in 'execute_job'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:164:in 'block (2 levels) in process'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/middleware/chain.rb:138:in 'block in invoke'
/home/mastodon/live/app/lib/sidekiq_error_handler.rb:5:in 'call'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/middleware/chain.rb:140:in 'block in invoke'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-unique-jobs-6.0.21/lib/sidekiq_unique_jobs/server/middleware.rb:29:in 'call'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/middleware/chain.rb:140:in 'block in invoke'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/middleware/chain.rb:143:in 'invoke'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:163:in 'block in process'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:136:in 'block (6 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/job_retry.rb:111:in 'local'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:135:in 'block (5 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/rails.rb:43:in 'block in call'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/execution_wrapper.rb:87:in 'wrap'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/reloader.rb:73:in 'block in wrap'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/execution_wrapper.rb:87:in 'wrap'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/reloader.rb:72:in 'wrap'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/rails.rb:42:in 'call'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:131:in 'block (4 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:257:in 'stats'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:126:in 'block (3 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/job_logger.rb:13:in 'call'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:125:in 'block (2 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/job_retry.rb:78:in 'global'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:124:in 'block in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/logger.rb:10:in 'with'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/job_logger.rb:33:in 'prepare'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:123:in 'dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:162:in 'process'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:78:in 'process_one'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/processor.rb:68:in 'run'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/util.rb:15:in 'watchdog'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/util.rb:24:in 'block in safe_thread'`

**Comment by ThibG** [comment]
Could you try the following PR? https://github.com/glitch-soc/mastodon/pull/1332
