### ISSUE TITLE
Potential issue with relays getting a 401 error?

### ISSUE THREAD

**Issue by catgoat** [glitch-soc/mastodon#1184]
I just set up a new relay over at relay.dog, and I noticed glitch soc instances are having a lot of trouble connecting to it so I wanted to raise this as a potential issue. Vulpine.club was on the relay successfully before a recent prod deployment in which they updated their version of glitch soc as well, as far as I know.

Below is what I see in a debug log for one instance (vulpine.club) but it also happens for barkshark.tk. The admin of barkshark verified it happens against her own dev relay but not with an older version of glitch-soc, so I suspect one is able to recreate this with latest glitch-soc and the pleroma relay code.

This happens over and over again in the logs: 

[2019-07-30 23:34:19,625] INFO: 127.0.0.1 [30/Jul/2019:23:34:19 +0000] "GET /actor HTTP/1.1" 500 330 "-" "http.rb/3.3.0 (Mastodon/2.9.2+glitch+vulpine-prod-20190728-01; +https://vulpine.club/)"
[2019-07-30 23:34:19,634] DEBUG: HTTP END [<aiohttp.client.ClientSession object at 0x7faab00344e0>], [TraceRequestEndParams(method='POST', url=URL('https://vulpine.club/inbox'), headers=<CIMultiDict('Content-Length': '300', 'Content-Type': 'application/activity+json', 'User-Agent': 'ActivityRelay', 'signature': 'keyId="https://relay.dog/actor#main-key",algorithm="rsa-sha256",headers="(request-target) content-length content-type user-agent",signature=“REDACTED FOR LENGTH“’)>, response=<ClientResponse(https://vulpine.club/inbox) [401 Unauthorized]>
<CIMultiDictProxy('Date': 'Tue, 30 Jul 2019 23:34:19 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'Mastodon', 'X-Frame-Options': 'DENY', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Referrer-Policy': 'same-origin', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload', 'Cache-Control': 'no-cache, no-store', 'Vary': 'Accept-Encoding', 'Content-Encoding': 'gzip', 'X-Request-Id': 'REDACTED', 'X-Runtime': '0.052172')>
)]
[2019-07-30 23:34:19,634] DEBUG: 'https://vulpine.club/inbox' >> resp 'Public key not found for key https://relay.dog/actor#main-key'

I have not seen anything like this with any of the vanilla mastodon instances on the relay right now

Please let me know if there's anything I can add that would be helpful.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
This is the relay software not working when the request to get the actor is signed

**Comment by ThibG** [comment]
Found the issue in the relay software, submitted a fix: https://git.pleroma.social/pleroma/relay/merge_requests/18

**Comment by catgoat** [comment]
Thank you!

**Comment by otrapersona** [comment]
I'm not sure if this is related or not but I haven't been able to successfully add a relay. I'm on the latest commit which at the time is https://github.com/glitch-soc/mastodon/commit/787d5d728923393f12421a480b3c7aee789a11fe .

I tried it on an instance that migrated to glitch and on one that started fresh with glitch, an admin friend of mine tried on theirs too and the same happened:

Even if the instance is listed as approved on the relay's page list (and I personally asked a relay admin and they told me they accepted my instance and even restarted their relay), for me they'll be indefinitely say "Waiting for relay's approval".

The logs says:

> method=POST path=/inbox format=*/* controller=ActivityPub::InboxesController action=create status=401 duration=35.86 view=0.59 key=https://relay.mastodon.host/actor#main-key

> method=POST path=/inbox format=*/* controller=ActivityPub::InboxesController action=create status=401 duration=31.29 view=0.71 db=0.00 key=https://relay.mastodon.host/actor#main-key

same for relay.blob.cat and relay.mastodon.host.

Please take into account that I switched to vanilla mastodon and I was able to add the relays and they worked just fine.

**Comment by ThibG** [comment]
By “switched to vanilla mastodon”, do you mean switching to master, or a release?

**Comment by otrapersona** [comment]
forgot to specify, to version mastodon release v3.2.0
in case it's relevant, I had to use bcrypt (3.1.12) instead of bcrypt (3.1.13) on my sbc (asus tinkerboard)

**Comment by ThibG** [comment]
Alright, found out the issue. We (Mastodon's development version) bumped the requirement for signed signatures to also include the `Date` header, which the relay software does not do.

**Comment by ThibG** [comment]
A fix has apparently been proposed 2 weeks ago, but this relay software seems unmaintained.
