### ISSUE TITLE
422 Unprocessable Entity when dismissing a notification via the API

### ISSUE THREAD

**Issue by kensanata** [glitch-soc/mastodon#1188]
I have a bot running on tabletop.social which runs Mastodon 2.9.2+glitch according to the [about page](https://tabletop.social/about/). The bot's [source code](https://alexschroeder.ch/cgit/greeter) has been [unchanged since 2018](https://alexschroeder.ch/cgit/greeter/log/). On [line 73](https://alexschroeder.ch/cgit/greeter/tree/greeter.py#n73) it calls [Mastodon.py](https://github.com/halcy/Mastodon.py)'s `notifications_dismiss` function. This calls [/api/v1/notifications/dismiss](https://docs.joinmastodon.org/api/rest/notifications/#post-api-v1-notifications-dismiss) with the id of the notification to dismiss. Some time in July this stopped working.

```
Traceback (most recent call last):
  File "./greeter.py", line 98, in <module>
    main(account, os.getenv("DEBUG", default=False))
  File "./greeter.py", line 79, in main
    followers = new_followers(mastodon, debug)
  File "./greeter.py", line 73, in new_followers
    mastodon.notifications_dismiss(notification["id"])
  File "</home/alex/.local/lib/python3.5/site-packages/decorator.py:decorator-gen-67>", line 2, in notifications_dismiss
  File "/home/alex/.local/lib/python3.5/site-packages/mastodon/Mastodon.py", line 100, in wrapper
    return function(self, *args, **kwargs)
  File "/home/alex/.local/lib/python3.5/site-packages/mastodon/Mastodon.py", line 1805, in notifications_dismiss
    self.__api_request('POST', '/api/v1/notifications/dismiss', params)
  File "/home/alex/.local/lib/python3.5/site-packages/mastodon/Mastodon.py", line 3049, in __api_request
    error_msg)
mastodon.Mastodon.MastodonAPIError: ('Mastodon API returned error', 422, 'Unprocessable Entity', None)
```

When I use the debug option, I get what I expect:

```
I should be dismissing notification 130941
I should be dismissing notification 130189
```

And these are the correct notifications. When I check using `curl --header "Authorization: Bearer XXX" -sS https://tabletop.social/api/v1/notifications/130941` I get the correct notification.

The bot's permissions are `read:notifications write:notifications write:statuses`.

I'm assuming that something in the server is causing the 422 error, but I don't see what it could be. Any ideas?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [?] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
It's supposed to be `/api/v1/notifications/${id}/dismiss`, it seems like `/api/v1/notifications/dismiss?id=…` was supported but deprecated until early july

**Comment by kensanata** [comment]
I'll try and contact the author of `Mastodon.py`. Thanks for the info.

For reference, the library uses the following:

```python
    def notifications_dismiss(self, id):
        """
        Deletes a single notification
        """
        id = self.__unpack_id(id)
        params = self.__generate_params(locals())
        self.__api_request('POST', '/api/v1/notifications/dismiss', params)
```

I'm interpreting what you are saying as also saying that [the Mastodon documentation of the dismiss API call](https://docs.joinmastodon.org/api/rest/notifications/#post-api-v1-notifications-dismiss) is also out of date. I'll look into that, too.

**Comment by kensanata** [comment]
Looking at the sources in the repo for the documentation, I see that the documentation was updated [four weeks ago](https://source.joinmastodon.org/mastodon/docs/commit/887ae4dbb74ff4e57e216b6d08de62070f871b65).
