### ISSUE TITLE
Disabling and re-enabling follower counts gives incorrect numbers

### ISSUE THREAD

**Issue by brortao** [glitch-soc/mastodon#1202]
If you hide follower counts in admin settings, then show them again, the number displayed is incorrect.

An example: https://cursed.technology/users/tao/followers
Follower count says 26, but there are about 19 pages of 12 followers each.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by brortao** [comment]
This also occurs in the vanilla Mastodon front-end. It can't occur in vanilla Mastodon proper, ofc.

**Comment by ThibG** [comment]
This seems unrelated to the “hide followers count” setting, as it only affects display, and not counting

**Comment by brortao** [comment]
You're right, the data is incorrect in the `account_stats` table, too.
Closing as a duplicate of https://github.com/tootsuite/mastodon/issues/11403 -- apologies, I wouldn't have guessed that this was a vanilla issue!
