### ISSUE TITLE
Feature request: exclusive lists

### ISSUE THREAD

**Issue by ghost** [glitch-soc/mastodon#1204]
### Pitch

[Hometown](https://github.com/hometown-fork/hometown), another Mastodon fork, recently released their v1.0 with a neat feature: exclusive lists. This lets you follow someone without their posts appearing in your home feed, only in lists.

### Motivation

Copying from the [Hometown wiki](https://github.com/hometown-fork/hometown/wiki/Exclusive-lists):

> Right now if you add an account to your "friends I like" list in Mastodon, posts from people on that list appear on that list. But they also appear on your home timeline, and maybe you don't want that! Perhaps you'd rather treat your "friends I like" list as your "real" home timeline, and then check your home timeline when you're bored. You can do that with exclusive lists!

**Comment by ThibG** [comment]
For reference, this has been implemented in https://github.com/hometown-fork/hometown/commit/bfc0fbab2c94dc134715f555edf793991da172a2

I'll review it and maybe merge it into glitch-soc

**Comment by revpriest** [comment]
Oh. I got excited to see there was a pull request and wondered if it would be merged by the weekend.

Humm. 2020 eh.

I would also like this, more than most of the other things Glitch offers.

Does the merge still work and is there a way I can apply that branch ClearlyClaire?
