### ISSUE TITLE
[Minor Bug] "Enter Two-Factor Authentication" Page isn't rendering CSS/Style sheets

### ISSUE THREAD

**Issue by Emuz** [glitch-soc/mastodon#1230]
The page for the two factor auth code input is rendering without any of the css or style sheet information. This issue started sometime around PR #1228's merging. I've not updating my live instance yet but notice this behavior on my development environment. (Live environment's two factor has it's css styling. [It's latest commit is 5911853...] 

Short Visual Desc: "White page, text left justified, SVG logo size of full width of window. No text or input box style/formatting"

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
    I did find a similar issue #271 & #271 but those are from 2017.
- [ ] This bugs also occur on vanilla Mastodon
    I tested off of mastodon.social and they did not have the same issue.

**Comment by ThibG** [comment]
For some reason the `set_pack` hook isn't called when the user is prompted for otp in `Auth::SessionsController`… I do not understand why… but I can easily work around that.
