### ISSUE TITLE
Un-bookmark not as responsive as the vanilla un-favourite

### ISSUE THREAD

**Issue by umonaca** [glitch-soc/mastodon#1244]
In vanilla, when a toot is unfavourited, the icon immediately become non-active (grey in color). However, in glitch-soc, when a toot is unbookmarked, the icon is still active, so the user is unsure if the toot has been unbookmarked or not. The user has to refresh the entire page to see the unbookmark has succeeded.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
Hm… I really can't reproduce that…
![Peek 12-11-2019 15-52](https://user-images.githubusercontent.com/384364/68681840-6c4bd900-0564-11ea-93ba-e1c8ea087daf.gif)

**Comment by umonaca** [comment]
Close because I can't reproduce it myself on glitch-soc.
