### ISSUE TITLE
Issue with cld3-ruby in latest versions when upgrading

### ISSUE THREAD

**Issue by phobos-dthorga** [glitch-soc/mastodon#1258]
Hello everyone!

We at [GekkoFyre Networks](https://gekkofyre.io/) made an attempted upgrade to the latest version of [glitch-soc](https://glitch-soc.github.io/docs/) for [Mastodon](https://github.com/tootsuite/mastodon) and ended up having to restore the virtual private server from a backup in the end. Some of the issues we experienced [are detailed in this blog article we published about the matter](https://gekkofyre.io/2020/01/gekkofyre-networks/community/everyone/backup-restoration-of-the-drake-network/), notifying our immediate community about the backup restoration.

Basically, we pulled the latest version of *glitch-soc* from GitHub as of last night ([Australian EST](https://www.timeanddate.com/time/zones/aest)), and during mid-compilation with Ruby we experienced a critical error related to the [`cld3-ruby` library](https://github.com/akihikodaki/cld3-ruby).

We've found some other issues about it [here](https://github.com/tootsuite/mastodon/issues/12704) and [there](https://github.com/tootsuite/mastodon/issues/3576) in the Mastodon community, but for the most part, it is preventing us from upgrading further than the current version which is at least 2-3 months old.

We're seeking advice on how to proceed from here, please, and although we did forget to capture the exact error message that occurred since backup restoration, we can go one better. We are happy to offer a development server containing our instance to anyone that can be trusted/vouched for.

Thank you.

**Comment by ThibG** [comment]
I unfortunately am not near a computer right now, so I cannot investigate much nor write a fix.

From what I understand, it seems you're running on Ruby 2.7, but one of the libs used (cld3) is not—in the version explicitly used by Mastodon/glitch-soc. A fix should come soon, but in the meantime, you could upgrade without going to Ruby 2.7. Alternatively, force the install of cld3 3.2.6 for Ruby 2.7 compatibility.

**Comment by phobos-dthorga** [comment]
Hello @ThibG,

It's good to hear directly from you. I believe I was using Ruby `2.6.1`, since that's what [the original instructions had mentioned](https://docs.joinmastodon.org/admin/install/). I'm rather certain of that.

If I can be of any further help, please let me know.

**Comment by ThibG** [comment]
Hm, if that's not a Ruby 2.7 compatibility issue, I'm not sure what that can be… I'd need to know the exact error to investigate further.

If the error occurs during `bundle install`, I think a way to save some time when updating then rolling back would be to copy the `vendor` directory, update, and simply revert to the old commit then revert to the copied `vendor` directory, rather than restoring the whole VM. This should avoid any downtime if you don't stop the services before upgrading.

As for Ruby 2.7 compatibility, I'll merge the necessary changes in glitch-soc when they hit upstream, which should be really soon.

**Comment by phobos-dthorga** [comment]
Hello again @ThibG,

Please let me know once the newer updates for Ruby 2.7 are ready to be `git clone`'ed by the wider public, thank you.

**Comment by ThibG** [comment]
Hm actually the issue should not be with Ruby 2.7, since Mastodon's `Gemfile` is still specifying `ruby '>= 2.4.0', '< 2.7.0'`

Anyway, the version bump for `cld3` (among other things), has been merged.

If you have any issue with the upgrade, please do report at which step and what the error is!

**Comment by ThibG** [comment]
Closing for lack of update. Feel free to reopen if you still have the issue and any additional information. (Also, consider updating your instance ASAP, there have been important fixes lately)
