### ISSUE TITLE
Show DMs

### ISSUE THREAD

**Issue by hoodiek** [glitch-soc/mastodon#126]
the concept is simple. many people find it odd that dms are in home timeline and prefer they wouldn't be. shouldn't be hard to make a toggle for it like the others shown below
![image](https://user-images.githubusercontent.com/23704040/29036838-189b80b6-7b6f-11e7-8278-d3298d9f50f9.png)

**Comment by MightyPork** [comment]
there's an upstream PR for a DM column. I'm not super optimistic about it being merged, but that'll be a cleaner solution

**Comment by dustine** [comment]
i'd gander having both options would be best long-term for glitch-soc, but i approve of a Home toggle

**Comment by hoodiek** [comment]
what dustine said, both options are necessary and we could make a pr upstream as well as here
