### ISSUE TITLE
Web client / frontend: external Images do not load

### ISSUE THREAD

**Issue by mxkris** [glitch-soc/mastodon#1276]
Hello - new admin here. I just recently switched a fresh instance from mainline to glitch-soc and after setup, all links to external images do not load the image.

You can see this in effect here: https://kindred.haus/about/more - notice how the image link to jortage does not display, nor does the avatar for my admin user.

![Annotation 2020-02-04 123419](https://user-images.githubusercontent.com/24760316/73784419-6fb9bf80-4763-11ea-8cd3-d9effd69621b.png)

The good news is this does not seem to affect apps/API - using my account via Tusky on Android, images are served and display just fine.

Please let me know what information I can provide to help sort this.

**Comment by ThibG** [comment]
This seems to be a Content Security Issue. I don't know how your instance is configured, but the CSP allows https://pool.jortage.com but not https://blob.jortage.com which seems to be what's in use

**Comment by mxkris** [comment]
Worth noting:
Federation and all other services are working fine, it really is only he web front-end, issue persists cross-browser and mobile-web.

I followed the instruction on https://glitch-soc.github.io/docs/ to the letter, no errors throughout, upon restart of services, images begun to fail to load.

**Comment by mxkris** [comment]
> This seems to be a Content Security Issue. I don't know how your instance is configured, but the CSP allows https://pool.jortage.com but not https://blob.jortage.com which seems to be what's in use

It would agree but i think that is a red herring? I don't know what switching to glitch would have changed that would stop this image from being allowed to display.

Also, see what our federated timeline looks like:
![Annotation 2020-02-04 154117](https://user-images.githubusercontent.com/24760316/73785239-ec00d280-4764-11ea-888a-f9b2d79afd66.png)

**Comment by ThibG** [comment]
hm, I think this is due to glitch-soc's Content Security Policy being slightly stricter than Mastodon's and pool.jortage.com making use of redirects. I'm not sure how to improve that (I'll look into this).

In the meantime, you can work around the issue by adding `data_hosts << 'https://blob.jortage.com` before `data_hosts.uniq!` in `config/initializers/content_security_policy.rb` and restart `mastodon-web`

**Comment by mxkris** [comment]
Excuse my ignorance; like so?:
![Annotation 2020-02-04 154901](https://user-images.githubusercontent.com/24760316/73785760-e8ba1680-4765-11ea-9767-46e9cca84bf0.png)

**Comment by mxkris** [comment]
Heyyy - it works!

Thanks for the fix.

**Comment by ThibG** [comment]
yes, except I forgot the final ', sorry, this should read:

```ruby
  data_hosts << 'https://blob.jortage.com'

  data_hosts.uniq!
```

**Comment by mxkris** [comment]
I figured it had to be closed and it worked perfectly, thank you again!

**Comment by ThibG** [comment]
Merged a cleaner fix, you want to add `EXTRA_DATA_HOSTS=https://blob.jortage.com` to your `.env.production` and restore `config/initializers/content_security_policy.rb` to how it was

**Comment by mxkris** [comment]
I assume I will need to update my instance in order to make this change, correct?

**Comment by ThibG** [comment]
Yes.
