### ISSUE TITLE
direct message replies are silently converted to public if they contain no mentions

### ISSUE THREAD

**Issue by BenLubar** [glitch-soc/mastodon#1286]
it used to be possible to draft a reply to a toot by posting a direct message reply to a post, and then later redrafting it to be public and possibly mention people

however, replying to a public post with a direct message creates a *public* reply

the direct message works properly if anyone is mentioned, including the user who is posting it

**Comment by ThibG** [comment]
I cannot reproduce this.
Is by any chance the last commit “Fix alt+enter changing visibility setting without sending toot when toot is empty”?
If so, posting by clicking the “toot” button ignores the chosen visibility, and it has been fixed since then.

**Comment by BenLubar** [comment]
hard refresh did in fact fix it, so I'm assuming that was the case
