### ISSUE TITLE
Error when db migrate or compile

### ISSUE THREAD

**Issue by mstdn** [glitch-soc/mastodon#1296]
Hello! 

I have a local copy installed but when I use the migrate or precompile function I get the following error: 

LoadError: libicuuc.so.64: cannot open shared object file: No such file or directory - /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/charlock_holmes-0.7.7/lib/charlock_holmes/charlock_holmes.so

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [-] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
bundle install --force

**Comment by mstdn** [comment]
> bundle install --force Le 1 mars 2020 23:44:25 GMT+01:00, "mstdn.social" <notifications@github.com> a écrit :
> […](#)
> Hello! > > I have a local copy installed but when I use the migrate or precompile function I get the following error: > > LoadError: libicuuc.so.64: cannot open shared object file: No such file or directory - /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/charlock_holmes-0.7.7/lib/charlock_holmes/charlock_holmes.so> > * * * *> > - [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.> - [-] This bugs also occur on vanilla Mastodon> > > -- > You are receiving this because you are subscribed to this thread.> Reply to this email directly or view it on GitHub:> #1296

Merci!
