### ISSUE TITLE
Private toot has twice the message icon

### ISSUE THREAD

**Issue by tcitworld** [glitch-soc/mastodon#1298]
Once because the message isn't boostable and once as a privacy status icon.

![Screenshot_2020-03-10 Mastodon by tcit](https://user-images.githubusercontent.com/2197836/76333462-f9742400-62f1-11ea-936f-0aac6a81157f.png)

I don't think there's a possibility for the statuses to be different so maybe hide the privacy status icon in this specific case?

Boost number could be hidden as well, but that's probably an upstream issue.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
Upstream also displays “0” indeed.

I'm not sure which part we should get rid of in this case? The part that's before favs or after?

**Comment by tcitworld** [comment]
It isn't shown in my screenshot, but the fact that privacy status icon can be colored would make me think they should be the ones kept, so I would say let's ditch the first one.
