### ISSUE TITLE
[pleroma/mastofe#19] Hide/Show all attachments (regardless of sensitive status)

### ISSUE THREAD

**Issue by lanodan** [glitch-soc/mastodon#1307]
As written in https://git.pleroma.social/pleroma/mastofe/issues/19 it would be nice to be able to hide/show all attachments (thus ignoring sensitive status), has been reported over a year ago but either didn't get the time nor the ReactJS skills for adding this feature. (and right now I can't load mastofe because of a webkit-gtk bug anyway)

**Comment by ThibG** [comment]
Mastodon has a setting (so, stored server-side and exposed in `initial_state` for this). It's `display_media` and can be `hide_all`, `show_all` or `default`.

![image](https://user-images.githubusercontent.com/384364/77350538-f428c780-6d3c-11ea-9281-296574ff4ea3.png)
