### ISSUE TITLE
Sidekiq giving out errors and attachments not working

### ISSUE THREAD

**Issue by phobos-dthorga** [glitch-soc/mastodon#1309]
Hello!

Ever since upgrading to 3.1.2 of Mastodon and henceforth glitch-soc from a clean user account (although keeping the PostgreSQL database and media files), we've been encountering a few issues. One of them is that Sidekiq is not working correctly [ 1, 2 ] .

[ 1 ] - https://paste.gekkofyre.io/view/1993ee28
[ 2 ] - https://imgur.com/95Nsqcv

That's just a small sample but it goes on for thousands of lines with many errors spread throughout, showing it working both correctly in some instances and error'ing out in others. I really do wish SystemD offered an easy-to-use export function...

We followed the following installation guides [ 3, 4 ]:

[ 3 ] - https://docs.joinmastodon.org/admin/install/
[ 4 ] - https://glitch-soc.github.io/docs/

We're also encountering issues with uploading files and making attachments, where glitch-soc gives out an `Error 500` and redirects to [ 5 ] behind-the-scenes. It originally redirected towards [ 6 ] before we made some changes to our NGINX hosting file.

[ 5 ] - `<primary-domain>/api/v2/media`
[ 6 ] - `<s3-proxy>.<primary-domain>/api/v2/media`

At both domains though, this page seems to be non-existent so we're not sure what is going on. There is also little to no information about that API specifically from what we can find, so any help at all would be sincerely appreciated.

We've tried changing permissions on Mastodon's `public` directory as well as adding the `mastodon` user to the `www-data` group, thinking it might be related in someway to that. But neither corrective measure has worked.

Thank you once more!

--
Regards,
Phobos D'thorga

https://gekkofyre.io/
GekkoFyre Networks

**Comment by ThibG** [comment]
Unfortunately, your excerpt from your sidekiq logs doesn't actually include the error message. I can't work with it.

Without the `mastodon-web` logs corresponding to the error you're hitting for the screenshot, I can only guess it is the rack bug that you can fix by deleting your `rack.session` cookie (it is documented in one of the 3.x or 3.1.x release notes).

As for the 500 error while uploading media, I can't work without the server-side logs. The API endpoint should not be served by S3, and the default configuration file should not cause this.

**Comment by ThibG** [comment]
Also, did you run database migrations when updating? I have a hunch the upload issues might be because of that.

**Comment by phobos-dthorga** [comment]
Hello @ThibG,

It's both nice to hear from you again and to see you still taking a most active role in this project. It seems that deleting `rack.session` (or rather all of the cookies for our Mastodon instance to be safe) fixed the issue at hand, regarding the loading of the Sidekiq administration GUI.

Apologies though, I should've included more details with regards to the 500 error in the original post. As you can see at the screenshot below [ 1 ], the error we are getting with attachments and multimedia uploads can be found at the bottom of the Development Console list.

[ 1 ] - https://imgur.com/TxQFuIf

The error logs for NGINX don't really seem to update after each attachment upload attempt though, but never-the-less, I have included some of their contents below for your perusal [ 2, 3 ].

[ 2 ] - https://paste.gekkofyre.io/view/9e461515
[ 3 ] - https://paste.gekkofyre.io/view/c4019c3d
[ 4 ] - https://paste.gekkofyre.io/view/9cb72e97

I'm, of course, limited to what I can upload due to user privacy concerns. I should also note that nothing of interest appears in the logs of `mastodon-web`, `mastodon-sidekiq`, and `mastodon-streaming` at least when I checked immediately after attempting an upload, by doing a `systemctl status <service>`.

P.S.
Yes, we did the database migrations and they seemed to have proceeded okay :) Would it be safe to run them again? I migrated PostgreSQL servers shortly thereafter, from Amazon AWS RDS to a server on our own infrastructure. Not sure if that's of any importance.

--
Regards,
Phobos D'thorga

https://gekkofyre.io/
GekkoFyre Networks

**Comment by phobos-dthorga** [comment]
Hello again,

I forgot to upload our NGINX config, just in-case that's required [ 1 ]!

[ 1 ] - https://paste.gekkofyre.io/view/a31a6640

--
Regards,
Phobos D'thorga

https://gekkofyre.io/
GekkoFyre Networks

**Comment by ThibG** [comment]
Running database migrations again should never be an issue, as Rails records which migrations have run and which haven't.

You should check `journalctl -u mastodon-web --follow` and try uploading some media. It should hopefully display the trace and tell us what is going on.

**Comment by phobos-dthorga** [comment]
Hello again,

Ooooh, that's a useful command :) You can see the output just below [ 1 ] and it did seem to give something useful, this time, thank you!

[ 1 ] - https://paste.gekkofyre.io/view/a86ca0a7

Let me know of your findings and definitely let me know as soon as possible if any private information (i.e. encryption keys, etc.) were included in that log excerpt.

--
Regards,
Phobos D'thorga

https://gekkofyre.io/
GekkoFyre Networks

**Comment by ThibG** [comment]
seems like you have an issue with your storage provider

**Comment by phobos-dthorga** [comment]
Thank you so much, @ThibG! Now we're getting somewhere :)

It seems we had set the wrong S3 region as of the past week (not sure why we changed it), so I corrected that, and now we're getting an SSL verification error. I dread seeing this as a system administrator *sighs*.

```Mar 31 04:17:25 hatchling.drake.network bundle[4453]: [c80b3ffa-b6ee-4fa2-bb3b-76003df7213c] [paperclip] saving media_attachments/files/000/207/049/original/c186679c470c1233.jpg
Mar 31 04:17:25 hatchling.drake.network bundle[4453]: [c80b3ffa-b6ee-4fa2-bb3b-76003df7213c] method=POST path=/api/v2/media format=html controller=Api::V2::MediaController action=create status=500 error='Seahorse::Client::NetworkingError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)' duration=460.31 view=0.00 db=6.49
Mar 31 04:17:25 hatchling.drake.network bundle[4453]: [c80b3ffa-b6ee-4fa2-bb3b-76003df7213c]
Mar 31 04:17:25 hatchling.drake.network bundle[4453]: [c80b3ffa-b6ee-4fa2-bb3b-76003df7213c] Seahorse::Client::NetworkingError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)):
Mar 31 04:17:25 hatchling.drake.network bundle[4453]: [c80b3ffa-b6ee-4fa2-bb3b-76003df7213c]
Mar 31 04:17:25 hatchling.drake.network bundle[4453]: [c80b3ffa-b6ee-4fa2-bb3b-76003df7213c] app/controllers/api/v2/media_controller.rb:5:in `create'
^C
root@hatchling:~#
