### ISSUE TITLE
superclass mismatch for class error during install

### ISSUE THREAD

**Issue by elenners** [glitch-soc/mastodon#1325]
Hello, I have been following this guide to install (https://glitch-soc.github.io/docs/) and everything went through til

> Run the pre-deployment database migrations: RAILS_ENV=production SKIP_POST_DEPLOYMENT_MIGRATIONS=true bundle exec rails db:migrate

I receive the superclass mismatch for class error as seen in the attached screenshot. Is there a workaround for this?

![image](https://user-images.githubusercontent.com/63966511/81177532-6e6b7f00-8f6c-11ea-93f1-d9c74c5729f2.png)

**Comment by ThibG** [comment]
I can't figure out what's going on. Could you copy the whole trace?

**Comment by elenners** [comment]
Sure! Unfortunately Digital Ocean's console cuts it off so I can't get it up to the command, but basically ran that RAILS_ENV command, and this was the result.

<img width="766" alt="Screen Shot 2020-05-06 at 9 55 02 AM" src="https://user-images.githubusercontent.com/63966511/81192520-f60eb900-8f7f-11ea-8402-e9e20bb7ba95.png">

**Comment by ThibG** [comment]
How did you install Ruby? Which version? Did you run `bundle install` successfully?

**Comment by elenners** [comment]
When I first tried to run bundle install I had to do snap install ruby --classic first, could that have caused the issue?

**Comment by ThibG** [comment]
Maybe. I do not know about snap. Anyway, the issue does not seem to come from something in glitch-soc's code, but something with dependencies. Something seems to be loaded twice with possibly different versions, which I haven't seen so far.
It does look like it is not using dependencies from the usual path as well.
I'd say to retry the various `bundle config` and `bundle install` steps and post if you have any issue with them.

**Comment by elenners** [comment]
Thanks so much for your help. I will start fresh and try again.

**Comment by ThibG** [comment]
Have you managed to fix your issue?

**Comment by elenners** [comment]
Hi sorry! I never did get it to work properly and ended up calling it quits. I’ll mark this closed.
