### ISSUE TITLE
Glitchy profile page (image size issue)

### ISSUE THREAD

**Issue by maximesrd** [glitch-soc/mastodon#1330]
Hello,
I recently updated glitch, and I encountered a problem with the user profiles. 

Apparently the images are wrongly dimensioned, which hides the text and gives unexpected effects (see attachement).

* * * *

- [https://github.com/glitch-soc/mastodon/search?o=desc&q=profile&s=created ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- This bug doesn't occur on vanilla Mastodon
![image](https://user-images.githubusercontent.com/42911617/82234307-8ad6c680-9931-11ea-9ab5-5fa84d38250e.png)

**Comment by ThibG** [comment]
Did you run `bundle exec rails assets:precompile` before reloading `mastodon-web`? It looks like you're running outdated assets.

**Comment by maximesrd** [comment]
Yes, the output displayed is this: 
`From https://github.com/glitch-soc/mastodon
 * branch                master     -> FETCH_HEAD
Already up to date.
mastodon@servmaxine:~/live$ assmast
yarn install v1.22.4
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 0.66s.
Everything's up-to-date. Nothing to do`

Some times, when I was trying to compile the assets, it said that the compilation was impossible, I still haven't managed to reproduce this message to debug it and know why it doesn't work.

I also tried: `bundle exec rails assets:clean` but it didn't change anything.

**Comment by ThibG** [comment]
`bundle exec rails assets:clobber && bundle exec rails assets:precompile` might help

**Comment by maximesrd** [comment]
this is the compilation error:

`I, [2020-05-18T18:14:22.691821 #8889]  INFO -- : Removed /home/mastodon/live/public/assets
Removed webpack output path directory /home/mastodon/live/public/packs
yarn install v1.22.4
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 0.60s.
I, [2020-05-18T18:14:27.080305 #8923]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css
I, [2020-05-18T18:14:27.080633 #8923]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css.gz
I, [2020-05-18T18:14:27.082272 #8923]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css
I, [2020-05-18T18:14:27.082399 #8923]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css.gz
I, [2020-05-18T18:14:27.083649 #8923]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/favicon-db10337a56c45eb43c22ff5019546b520fa22c7281d4d385f235cbca67ed26bb.png
I, [2020-05-18T18:14:27.089896 #8923]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c36774f024dc0461a1d9c30083ef24b43f271e89f2f4b3ec537010e0a1319f06.js
I, [2020-05-18T18:14:27.090001 #8923]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c36774f024dc0461a1d9c30083ef24b43f271e89f2f4b3ec537010e0a1319f06.js.gz
I, [2020-05-18T18:14:27.092469 #8923]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-91a51e56fd7a8fe6fa10d1ccccf54a9e628dc3f4a47682ba17989cf58fd5dfd2.css
I, [2020-05-18T18:14:27.092588 #8923]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-91a51e56fd7a8fe6fa10d1ccccf54a9e628dc3f4a47682ba17989cf58fd5dfd2.css.gz
Compiling...
Compilation failed:`

**Comment by ThibG** [comment]
uh, there isn't really any error i can work with here
maybe the process runs out of memory, how much available memory does the server have?

**Comment by maximesrd** [comment]
it has 4 GB of ram and 8 cores (it's in an LXC container under Proxmox).

I'm testing the previous command by stopping the services to free some RAM, it only had 2Gb left to compile. And obviously, it came from this, now, it works !

Sorry to have bothered you.

**Comment by ThibG** [comment]
No problem. You can trade off the final size of the assets for lesser build-time resources by applying this patch:

```diff
diff --git a/config/webpack/production.js b/config/webpack/production.js
index bceffaf5c..40347b773 100644
--- a/config/webpack/production.js
+++ b/config/webpack/production.js
@@ -31,14 +31,7 @@ module.exports = merge(sharedConfig, {
   stats: 'normal',
   bail: true,
   optimization: {
-    minimize: true,
-    minimizer: [
-      new TerserPlugin({
-        cache: true,
-        parallel: true,
-        sourceMap: true,
-      }),
-    ],
+    minimize: false,
   },
 
   plugins: [
@@ -47,11 +40,6 @@ module.exports = merge(sharedConfig, {
       cache: true,
       test: /\.(js|css|html|json|ico|svg|eot|otf|ttf|map)$/,
     }),
-    new BundleAnalyzerPlugin({ // generates report.html
-      analyzerMode: 'static',
-      openAnalyzer: false,
-      logLevel: 'silent', // do not bother Webpacker, who runs with --json and parses stdout
-    }),
     new OfflinePlugin({
       publicPath: output.publicPath, // sw.js must be served from the root to avoid scope issues
       safeToUseOptionalCaches: true,
```
