### ISSUE TITLE
Allow Cmd-Enter to send toot

### ISSUE THREAD

**Issue by joyeusenoelle** [glitch-soc/mastodon#1333]
Glitchsoc appears to have reimplemented the Ctrl-Enter chord for sending a toot from the Compose window. This works well in Windows and Linux systems. But on Mac OS X, *Cmd-Enter* is the default chord in vanilla Mastodon, and changing to Ctrl-Enter breaks workflow for anyone on an OS X system.† (If nothing else, on this keyboard, there is a right-Command but not a right-Control, which means I have to use both hands to play the chord.)

Please add support for using the Cmd-Enter chord as the primary send button in the Compose window.

† I may be the only one, given that this appears to be the first time this has come up!

**Comment by ThibG** [comment]
Weird, we should handle the same keys as upstream (except for alt+enter which uses the secondary privacy option). It seems we're doing that in a keyup event handler while upstream does it in a keydown handler, though. Could you give #1335 a try?

**Comment by joyeusenoelle** [comment]
Should I need to reload assets in order to apply the patch? (I have not when adding past patches of this nature.) I've edited the code and restarted services, but Cmd-Enter still fails to send. I've confirmed that it *does* send in the vanilla Mastodon flavor.

**Comment by ThibG** [comment]
Yes, that kind of changes requires rebuilding the assets and reloading mastodon-web.

**Comment by joyeusenoelle** [comment]
That did the trick, thank you!
