### ISSUE TITLE
pinned local-only toots show up in public profile

### ISSUE THREAD

**Issue by stillnotstars** [glitch-soc/mastodon#1336]
if i pin a local only toot it gets pinned on my profile (ex. elekk.xyz/@\daffodilian), i would expect it to only appear when accessing my profile from the web interface

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
Oh. Pinned statuses is something I haven't thought about here. Luckily they won't federate because the guarding code in the serializer prevents that from happening, but it is visible on the public page and also breaks federating other pinned toots. Going to fix this.
