### ISSUE TITLE
<ol> start attribute is stripped

### ISSUE THREAD

**Issue by ashkitten** [glitch-soc/mastodon#1367]
seems like the `start` attribute is removed from `<ol>`, meaning things like `2. test` get changed to `1. test` after posting, when using markdown

the same thing happens with `<ol start="2"><li>test</li></ol>`, the `start` attribute is stripped and does not appear in the client

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by Fidgetcetera** [comment]
it appears this also is an issue with the markdown parser not applying the start attribute based on the first element in an ordered list

**Comment by ashkitten** [comment]
can confirm this is an issue with redcarpet. it seems like redcarpet hasn't been worked on in nearly a year. maybe we should look at kramdown, which does seem to have support for this and is actively developed?

**Comment by ThibG** [comment]
Yeah, we should definitely investigate other parsers, but this will be a pain…

**Comment by Fidgetcetera** [comment]
q
