### ISSUE TITLE
Invite System

### ISSUE THREAD

**Issue by dustine** [glitch-soc/mastodon#138]
For when you want instances to be closed registration-wise but not want to have to add every user individually, or help people invite their friends to their personal instance. 

- It should use [Devise](https://github.com/scambra/devise_invitable) as much as possible, as that's the auth system already in use over at glitch-soc.
- Users can have a limited number of invites they can send, and if so this number must being variable and incremented/**decremented** either by automated processes or manually by admins.
   - Automated processes can be based on time a user has been present in the instance, good standing, ...
   - Limited invites must be single-use. 
   - Admins could have unlimited invites, but should be tracked (invite tree) as well.
- Invite trees must be as transparent as possible: both users and admins should easily have access to see what invites a user sent, what new accounts came from these, what invites these new accounts did in return...
   - Users should be aware that their invitee will be tracked.
- The invite system must be comfortable to use, specially to the invitee. It will be the first impression to the new user, either to the instance or the whole of the fediverse.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by m4sk1n** [comment]
Partially done by tootsuite/mastodon#5814

**Comment by marrus-sh** [comment]
@beatrix-bitrot what is the current status on the invite system and are there still things which need to be done?

**Comment by beatrix-bitrot** [comment]
there are still things. right now either admins, mods, or everyone can invite, so none of the subtlety really exists in a way that let it be used in a way to control the growth of a site/community. it's not a pressing issue for us since people are not exactly beating down the doors to get in to the instance, but it would be nice to have some day...

**Comment by yipdw** [comment]
Does the invite system in upstream address this issue to the point where we can close it?

**Comment by beatrix-bitrot** [comment]
Yep
