### ISSUE TITLE
Markdown Patch

### ISSUE THREAD

**Issue by Vibhigupta** [glitch-soc/mastodon#1384]
I like to use your markdown patch, can you link its PR and complete code?

I only require markdown related code.

**Comment by ThibG** [comment]
There is more than a single patch/PR for this feature, you should look at commits which mention “markdown” and/or touch `app/lib/sanitize_config.rb` or `app/lib/formatter.rb`.

**Comment by Vibhigupta** [comment]
Only these two files have the code related to markdown or there are more?

There is no option to search commits🤔
