### ISSUE TITLE
App settings won't save on mobile

### ISSUE THREAD

**Issue by koyuawsmbrtn** [glitch-soc/mastodon#1396]
The so-called glitch-soc "app settings" won't save when I'm on a mobile browser (or when the viewport has mobile size).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
I can't reproduce this. Are you sure this is related to the mobile view at all? glitch-soc's “app settings” are tied to the browser's local storage, not the account.

**Comment by koyuawsmbrtn** [comment]
> I can't reproduce this. Are you sure this is related to the mobile view at all? glitch-soc's “app settings” are tied to the browser's local storage, not the account.

Yes, it is. I literally can't save them on my phone.

Steps to reproduce:
1. Log into a glitch-soc instance (with your mobile browser) and change some app settings around
2. Kill the browser app and you might see the settings reset on the next reload or navigate to the "edit profile" or something that is not tied to the frontend and settings will reset as well.

**Comment by koyuawsmbrtn** [comment]
I just found out that this issue only applies to Android WebViews, but not browsers for some odd reason

**Comment by ThibG** [comment]
> I just found out that this issue only applies to Android WebViews, but not browsers for some odd reason

So you're actually confirming this doesn't have anything to do with “the viewport has mobile size”?

My guess is that Android WebViews don't manage a local storage across sessions?

**Comment by koyuawsmbrtn** [comment]
Ah, that's the issue then. Thank you for that.
