### ISSUE TITLE
Install: rake setup fails with "cannot load such file -- ruby_http_parser"

### ISSUE THREAD

**Issue by melissaboiko** [glitch-soc/mastodon#1405]
Following the mastodon install docs until I reach this point:

```bash
RAILS_ENV=production bundle exec rake mastodon:setup
```

This fails for me with:

```
rake aborted!
LoadError: cannot load such file -- ruby_http_parser
/home/mastodon/glitchsoc-mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require'
/home/mastodon/glitchsoc-mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/mastodon/glitchsoc-mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/mastodon/glitchsoc-mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/home/mastodon/glitchsoc-mastodon/vendor/bundle/ruby/2.6.0/bundler/gems/http_parser.rb-54b17ba8c7d8/lib/http_parser.rb:2:in `<top (required)>'
/home/mastodon/glitchsoc-mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/mastodon/glitchsoc-mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/mastodon/glitchsoc-mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/mastodon/glitchsoc-mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/mastodon/glitchsoc-mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/mastodon/glitchsoc-mastodon/config/application.rb:7:in `<top (required)>'
/home/mastodon/glitchsoc-mastodon/Rakefile:4:in `require'
/home/mastodon/glitchsoc-mastodon/Rakefile:4:in `<top (required)>'
/home/mastodon/glitchsoc-mastodon/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/mastodon/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
/home/mastodon/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)

```

Same steps on vanilla masto (v3.2.0) work.

OS is Raspbian 10 (Buster).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
Hm, I can't reproduce this, and it shouldn't be different from upstream. Did you run `bundle install` as required? Did it produce an error?
If this still happens, does it happen again after doing `rm -rf tmp`?

**Comment by melissaboiko** [comment]
bundle install ran fine with no errors (and yarn install, after I found out that /usr/bin/yarn in Debian (& therefore Raspbian) is a different tool altogether).

The error on `mastodon:setup` persists after `rm -rf tmp/` .

It might be something related to arm7; something related to Debian 10, or to the Raspbian flavour of it.  I can test on an amd64 vanilla Debian 10 later.

(curiously, bundle install failed on _vanilla_ masto – it was trying to install bcrypt 3.1.13, which fails on arm7. per a hard-to-find bug report, I changed Gemfile.lock to 3.1.12 and it worked. glitch-soc evades this cause it's on 3.1.15.)

**Comment by ThibG** [comment]
Oh, I hadn't noticed bcrypt had been updated. 3.1.13 had a build issue on non-x86 for a long time, this is great!

I can't really see what may be causing the issue, though. It would be interesting if you tried vanilla Mastodon's latest development version on the same hardware.

In either case, it seems `http_parser.rb` isn't used anymore, so removing it entirely (https://github.com/tootsuite/mastodon/pull/14574) should fix the issue.

**Comment by melissaboiko** [comment]
Confirmed that it doesn’t reproduce on latest mastodon commit (0f38f9726a0a9d8e13633424d03e79f54df047a4 from Aug 13).

…And I tried it again on a fresh checkout and couldn’t reproduce it myself.  I guess I must have borked the 1st attempt somehow?

In any case I think it’s safe to close this, especially if `http_parser.rb` will be removed anyway.  Sorry for the trouble!
