### ISSUE TITLE
Home Timeline, Notifications and incoming DMs visible after logout

### ISSUE THREAD

**Issue by clarjon1** [glitch-soc/mastodon#1425]
### Expected behaviour

When a user logs out in a second tab, the user's Home timelines and notification should be stopped.

### Actual behaviour

When a user logs out in a second tab, if the user has another tab open, their regular Home timeline can be read, and notifications for boosts, favs, replies, private messages show up as if the user is still logged in.

### Steps to reproduce the problem

1. Open a Masto instance in two tabs
2. Log out of instance in one tab.
3. Have someone DM you 
4. Observe as you can read the DM in the tab left open despite the auth cookie being invalidated by logging out.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bugs also occur on vanilla Mastodon

I have posted about this on masto's project: https://github.com/tootsuite/mastodon/issues/14816

It may be worth looking to the pleroma-fe project for considering methods of handling this case, as repeating these steps in pleromafe results in a "Forbidden" error in the second tab, immediately stopping timeline updates and notifications: 

![image](https://user-images.githubusercontent.com/627845/93655067-582c0000-f9ef-11ea-914e-a2b2fc9d2f6c.png)

**Comment by ClearlyClaire** [comment]
This has been fixed upstream and merged in glitch-soc a while ago, sorry for not closing this sooner!
