### ISSUE TITLE
Issue with Thread viewing in Firefox 81.02

### ISSUE THREAD

**Issue by GibsonGibson** [glitch-soc/mastodon#1440]
Issue has been reported on various platforms, Windows and Linux alike. screenshot attached. Not all users are affected, but many are. Workaround requires disabling the Glitch interface and reverting to Vanilla Mastodon interface.

![glitchglitch](https://user-images.githubusercontent.com/42438071/96473519-bff88500-11ff-11eb-98ce-69ddbc75c0a0.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
It's uBlock Origin incorrectly blocking some of our files: https://forums.lanik.us/viewtopic.php?p=157100#p157100

**Comment by GibsonGibson** [comment]
We just independently figured this out as well. thanks! 👍

**Comment by ClearlyClaire** [comment]
Closing as this has apparently been fixed in uBlock Origin a while ago.
