### ISSUE TITLE
Removal of characther limit on toots/profile names

### ISSUE THREAD

**Issue by Katnjia** [glitch-soc/mastodon#1490]
### Pitch

Set the hardcoded char limit for toots and profile names higher (65666 was what we put it on Monsterpit's mastofork), or implement a feature for admins to be able to set the char limit for both to whatever they desire.
### Motivation

The char limit for Masto is rather arbitrary; it's just hardcoded and set to follow Twitters format AFAIK. It also causes issues for toots employing lots of emoji. Quite a few instances patch out this limit, and Masto federates with other software (like Pleroma) that doesn't respect this limit anyhow.

**Comment by ThibG** [comment]
This is already possible through the environment variables `MAX_TOOT_CHARS` and `MAX_BIO_CHARS` described in `.env.production.sample`!

**Comment by Katnjia** [comment]
**Follow up**: The argument made for this limit is to hinder Masto becoming a blog platform, and abuse post length, but I think it's much better to allow admins themselves to regulate this without any hindrance. Being able to easily set the char limit allows admins to pinpoint what kind of userbase they'd like to have. 

We already have social norms when it comes to instances not respecting CW'd for more risque content; instances doing the same with post length would just be met with muting, or blocking. And people that really wish to abuse this can do so anyway, wherever glitch-soc implements this or not.
