### ISSUE TITLE
NoMethodError: undefined method `content_type'

### ISSUE THREAD

**Issue by jaredallard** [glitch-soc/mastodon#1492]
```
NoMethodError: undefined method `content_type' for #<Status:0x00007faa49712708> Did you mean? content
```

Latest glitch-soc. I'm not sure what else to provide, please let me know if there's anything!

I recently went from mainline to glitch-soc, this is showing up in Sidekiq.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
Did you recently install glitch-soc? How did you do so? Did you forget, by any chance, to run database migrations?

**Comment by jaredallard** [comment]
I did just install it. I'm using a Kubernetes chart I've made, I did run database migrations, but I can go run through that again just to make sure.

**Comment by ThibG** [comment]
were you using mainline mastodon first?

**Comment by jaredallard** [comment]
I was, yep

**Comment by ThibG** [comment]
hm, then `tootctl cache clear` might do the trick

**Comment by jaredallard** [comment]
That did it, I think! :tada: Thank you!
