### ISSUE TITLE
404 page has "dev.glitch.social" hardcoded in the header

### ISSUE THREAD

**Issue by ftpmorph** [glitch-soc/mastodon#1493]
I clicked on an account that has been deleted on my instance and noticed that the 404 page has the "dev.glitch.social" domain hardcoded into the header.

<img width="438" alt="Screenshot 2021-01-27 at 11 42 46 am" src="https://user-images.githubusercontent.com/67348935/105986778-48a37e80-6095-11eb-84e3-dbd2eb87c25a.png">

Unfortunately I don't know my way around Mastodon well enough to know where the bug is coming from in the code, sorry I can't be more helpful.

* * * *

- [✓] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [×] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
It's not hardcoded in glitch-soc, but the 404 page is generated when running `assets:compile` and pulls the title from the `site_title` setting, which means you'd need to re-generate the file after changing the `site_title` setting (“Server name” in the “Site settings” admin panel).

**Comment by ftpmorph** [comment]
That's very odd because I'd already set my own server name in the admin settings before migrating over to Glitch. I'm guessing then if things work as they should the problem should go away next time I do an upgrade?

**Comment by ThibG** [comment]
Oh, you're actually right, what it does is generate the file using the *default* settings, just like it does upstream. I'm not sure what the reason for that is, and I'm not completely sure what we should do here.

In the meantime, you can edit `config/settings.yml` and run `bundle exec rails assets:generate_static_pages`

**Comment by ftpmorph** [comment]
Thank you, I'll try that now. Seems like weird behaviour, surely upstream must be pulling in the admin's site name from somewhere?

**Comment by ThibG** [comment]
Upstream has the same issue, it's pulling the default site title, which is “Mastodon” in upstream's case.

`config/settings.yml` is a tracked file, so yeah, you will have to deal with merge commits, stash the changes, or commit and use `git pull --rebase` to rebase your commit on top of the pulled in changes

**Comment by ftpmorph** [comment]
Ahhh that makes sense. Perhaps a simple fix might be to change Glitch's default title to something more generic like "Mastodon Glitch" rather than a domain name of another instance? I personally wouldn't mind that.

I have just changed my `config/settings.yml` and reloaded mastodon-web and you were right, that has fixed it and it now shows my own site's title. 

I'm curious, if I set up a local branch on my system that pulls from glitch-soc/main and I merge the commit, will it then only merge it locally? Because I'm pretty sure that's exactly what I did when migrating, I ended up creating a local branch that pulls from glitch-soc/main. 

Sorry for the incredibly noobish git questions, I'm not used to messing with tracked files on production sites.

Of course if the default title is changed to "Mastodon Glitch" or something similarly generic I'll just dump my local change anyway.

**Comment by ThibG** [comment]
You can commit and do `git pull` or `git pull --rebase`, you may have to resolve conflicts, the difference is only in what the git history would look like: with `git pull`, you'd have merge commits, with `git pull --rebase`, you'd rebase your local changes on top of the rest.

In any case, I've pushed a change to the default setting, it is now “Mastodon Glitch Edition”.

**Comment by ftpmorph** [comment]
Thanks for taking the time to explain that to me honestly. Now I know what to do with git if I want to tweak my instance in the future.

Since the default is now “Mastodon Glitch Edition” I'm perfectly happy with that since it only shows on error pages so for now I'll save any potential hassle and dump my changes when I next `git pull`.

Looks like this can be closed now then all is fixed :)
