### ISSUE TITLE
Scroll suggestions box when item at the bottom is selected

### ISSUE THREAD

**Issue by MightyPork** [glitch-soc/mastodon#150]
![screenshot_20170921_080224](https://user-images.githubusercontent.com/2041118/30680998-36e0abc6-9ea3-11e7-8f58-a7d7185c4ce2.png)

**Comment by beatrix-bitrot** [comment]
makes sense to me

**Comment by MightyPork** [comment]
yeah but I'm not yet sure how to do that :D

**Comment by MightyPork** [comment]
autoscroll is live
