### ISSUE TITLE
Cannot access timelines in browser (works in tusky still)

### ISSUE THREAD

**Issue by thunderblood101** [glitch-soc/mastodon#1538]
Described in title. I had the advanced interface on (the multi-column one) and disabling it worked. Firefox 88, Linux Mint.

Stack trace
-----------

```
Invariant Violation: [React Intl] An `id` must be provided to format a message.
e.exports@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:124338
ye@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:67193
909/n</a.render@https://koyu.space/packs/js/flavours/glitch/async/getting_started-4cb04b19f7243c915686.chunk.js:1:7414
Bi@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:310898
qi@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:310693
Os@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:346307
vu@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:337750
mu@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:337673
su@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:334703
Yo/<@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:286344
t.unstable_runWithPriority@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:361402
Vo@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:286053
Yo@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:286291
$o@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:286224
nu@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:331488
enqueueSetState@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:290009
_.prototype.setState@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:235936
t/n.load/<@https://koyu.space/packs/js/flavours/glitch/home-8c797b90798975ebe931.chunk.js:2:721872

```Mapped stack trace
-----------

```
Invariant Violation: [React Intl] An `id` must be provided to format a message.
Error(format.replace (webpack:///node_modules/invariant/browser.js:34:14)
formatMessage (webpack:///node_modules/react-intl/lib/index.es.js:952:12)
navItems.push (webpack:///app/javascript/home/mastodon/live/app/javascript/flavours/glitch/features/getting_started/index.js:160:68)
gi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:4332:15)
Lg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:4323:1665)
elementType (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6697:51)
Gj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6143:)
Ag (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6130:49)
yj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5871:13)
fg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2845:6)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:295:9)
bg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2807:13)
gg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2836:2)
eg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2825:46)
xj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5677:12)
enqueueSetState (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:3133:4)
setState (webpack:///node_modules/react/cjs/react.production.min.js:54:26)
utils.isString (webpack:///node_modules/axios/lib/helpers/cookies.js:20:16)
```


React component stack
---------------------

```

    in t
    in InjectIntl(t)
    in Connect(InjectIntl(t))
    in t
    in Connect(t)
    in t
    in t
    in t
    in t
    in div
    in t
    in InjectIntl(t)
    in Connect(InjectIntl(t))
    in Connect(InjectIntl(t))
    in t
    in div
    in div
    in t
    in t
    in t
    in t
    in withRouter(t)
    in InjectIntl(withRouter(t))
    in Connect(InjectIntl(withRouter(t)))
    in t
    in t
    in t
    in withRouter(t)
    in t
    in t
    in t
    in f
    in IntlProvider
    in t
```

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ClearlyClaire** [comment]
This is not a bug in glitch-soc but in the fork you are using, please reach out to your instance admin.
