### ISSUE TITLE
dev.glitch.social is down

### ISSUE THREAD

**Issue by weex** [glitch-soc/mastodon#1584]
### Expected behaviour

Page should have loaded

### Actual behaviour

Page could not be loaded

### Steps to reproduce the problem

Click on link in sidebar

### Specifications

.

**Comment by ClearlyClaire** [comment]
`dev.glitch.social` isn't directly linked to glitch-soc's development anymore and is (was?) maintained by someone else.
I updated the sidebar link. Keeping the issue open as a reminder to update the README.md.
