### ISSUE TITLE
Attached image is not shown when post has a poll

### ISSUE THREAD

**Issue by tribela** [glitch-soc/mastodon#1595]
### Expected behaviour

poll with images

### Actual behaviour

only poll is shown

### Steps to reproduce the problem

1. See the post that has poll and attached image at once from glitch-flavoured web version
2. for example: https://k.lapy.link/notes/8qb0oczd6g
3.
...

### Specifications

glitch-soc 314d561ac

**Comment by ClearlyClaire** [comment]
oh, I was under the impression upstream behaved like that too, but that's not the case.
I'll look into it
