### ISSUE TITLE
Markdown formatting isn't shown when logged out

### ISSUE THREAD

**Issue by benjaminwolkchen** [glitch-soc/mastodon#1596]
### Expected behaviour

The post written with markdown should always be displayed with markdown rendering.

### Actual behaviour

When you log out, the post isn't correctly formatted.

### Steps to reproduce the problem

1. This post should look like this: 
![Screenshot 2021-09-08 at 11-53-25 Benjamin ( hbenjamin mstdn social)](https://user-images.githubusercontent.com/42138517/132488241-16012ad8-8376-4b72-a57a-5be5744cd88d.png)

2. Open this post here: https://mstdn.social/@hbenjamin/106895417293256264
...

### Specifications

This bug occured in Glitch/Mastodon Version 3.4.1.

I am using Windows 10 and I tested it with Firefox 92 and Chrome 93.

**Comment by ClearlyClaire** [comment]
The toot *is* formatted, but your admin seem to have chosen to default to the vanilla flavor, which styling negates formatting.

**Comment by mstdn** [comment]
> The toot _is_ formatted, but your admin seem to have chosen to default to the vanilla flavor, which styling negates formatting.

Exactly this! :-)

Since we made a recent change to Glitch-soc I thought it was better to keep vanilla as default for new users etc since Masto is hard enough for new people as it is 👍  They can always switch to the more advanced Glitch flavour later

**Comment by benjaminwolkchen** [comment]
Thank you. This clears things up!
