### ISSUE TITLE
Media Upload Transcoding Process Needs Tuning

### ISSUE THREAD

**Issue by DJSundog** [glitch-soc/mastodon#162]
Currently, when uploading audio files, we artificially limit duration to 60 seconds in order to try and ensure the transcoding process occurs within the timeout period and without placing undue strain on the server. It also prevents the transcoded video file from exceeding the 8mb limitation set upstream.

This could be handled in a more streamlined fashion without having to resort to the duration limitation.

**Comment by nightpool** [comment]
the only real options here are 

1. don't transcode at all (the way we do video files). There's no reason we *should* provide video representations of audio files—semantically it doesn't make any sense.
2. transcode in a sidekiq worker. This would require selectively delaying the creation of the status depending on the type, but that's not that hard.

doing *any* kind of even trivial audio processing in a web worker will completely tank your application under any kind of load. Other users will get cascading timeouts and you'll end up with lots of 500 errors. You can get away with it on single-worker systems, where intellegent routing can avoid that thread, but once you're running multiple puma servers, thing get much worse.

**Comment by beatrix-bitrot** [comment]
yeah i'm inclined to agree with switching to no transcoding for the waveform. maybe just some indicator that it's an audio thing. a static image or a thing that says AUDIO you know?

**Comment by marrus-sh** [comment]
Does upstream not transcode video to WebM? I would prefer serving audio as Opus but I don't know how expensive that would be.

I think serving audio as video is unnecessary since upstream should indicate unknown attachments (and it's a bug if it doesn't). We can handle rendering and display in the frontend.

**Comment by ThibG** [comment]
Closing as we don't transcode audio uploads anymore!
