### ISSUE TITLE
Boost aggregation is not working on streaming

### ISSUE THREAD

**Issue by tribela** [glitch-soc/mastodon#1626]
### Expected behaviour

Multiple boosts on same post will not be shown multiple time on timeline

### Actual behaviour

All of boosts are shown in timeline

### Steps to reproduce the problem

1. X following A, B, C
2. A post some posting
3. B boosts it, And C also boosts it
4. A's post, B's boost about that, C's boost about that is shown on timeline
5. If refresh and reload the timeline, only single post (the original) is shown on timeline
...

### Specifications

glitch e0f396269
Only happened while using streaming

**Comment by ClearlyClaire** [comment]
Were you able to confirm any of the above?
