### ISSUE TITLE
Layout is broken

### ISSUE THREAD

**Issue by tribela** [glitch-soc/mastodon#1629]
### Expected behaviour

Layout width is normal with Mastodon vanilla flavour

### Actual behaviour

Layout width is too wide and broken on glitch flavour

### Steps to reproduce the problem

1. Choose glitch flavour
2. See /share page or /admin/accounts/:id page for user that have long bio message on it
3.
...

### Specifications

Admin's user view page is broken like this
![image](https://user-images.githubusercontent.com/5047683/141390180-dd3509b1-63bd-4aaf-8cdc-e6925762fe94.png)
/share page is like this
![image](https://user-images.githubusercontent.com/5047683/141390210-38eafb8f-b3f1-477f-8561-e6af1edc6274.png)

This is from vanilla mastodon
![image](https://user-images.githubusercontent.com/5047683/141390224-b0ffada8-7071-4f35-ab5a-878789f6ab02.png)

on commit a25839340e93b1e93b7b99b0f65fa7da7d62bad2

**Comment by ClearlyClaire** [comment]
Admin page issue seem to be an upstream issue, unlike the share page one.
