### ISSUE TITLE
Tag search in column settings returns 401

### ISSUE THREAD

**Issue by mkody** [glitch-soc/mastodon#1639]
### Steps to reproduce the problem

1. Pin a tag column
2. Open the column's settings and enable "Include additional tags for this column"
3. Try to add a tag in one of the 3 fields, no results

![image](https://user-images.githubusercontent.com/843787/143576456-c00696c2-bba1-4259-9056-d719b7369e6b.png)

Looking at the network tab, I see I get 401 errors:  
`https://im-in.space/api/v2/search?q=cat&type=hashtags`
```json
{"error":"The access token is invalid"}
```

Comparing the headers with a vanilla instance of Mastodon, I see that I'm not sending a `authorization: Bearer ...` in the headers.
Seems to happen too when I switch to Vanilla flavor.

### Expected behaviour

I get results for my tag search.

### Actual behaviour

No Authorization header is sent, so no results.

### Specifications

When I got told of that problem, im-in.space was running on 766a361b86f8c8212c08d3bae1d4728c3c5b1f09

Updated this morning with 97151840b02499a0cec1360907a6b86a1df02b3b merged and still happening.

**Comment by ClearlyClaire** [comment]
I can reproduce it. Investigating.

**Comment by ClearlyClaire** [comment]
This is an upstream issue, see #17054

**Comment by mkody** [comment]
Thanks for looking at this!

But it might have introduced a regression? The `authorization` is passed in the additional hashtag search now, but it returns a 500 error.
And it now affects normal search.

In `mastodon-web`'s log I get:
```
method=GET path=/api/v2/search format=html controller=Api::V2::SearchController action=index status=500 error='NoMethodError: undefined method `fetch' for 24:Integer' duration=13.31 view=0.00 db=2.24

NoMethodError (undefined method `fetch' for 24:Integer):

app/services/tag_search_service.rb:79:in `from_elasticsearch'
app/services/tag_search_service.rb:10:in `call'
app/services/search_service.rb:62:in `perform_hashtags_search!'
app/services/search_service.rb:20:in `block in call'
app/services/search_service.rb:12:in `call'
app/controllers/api/v2/search_controller.rb:19:in `search_results'
app/controllers/api/v2/search_controller.rb:12:in `index'
```

Request in normal search was `GET /api/v2/search?q=%23MastoArt&resolve=true&limit=10`

**Comment by ClearlyClaire** [comment]
Doesn't seem related. It is most likely due to mastodon#16915 but I don't know much about Chewy or Elasticsearch unfortunately :/

**Comment by mkody** [comment]
Thanks, I'll close this issue and report it on upstream
