### ISSUE TITLE
Option for recaptcha(v2) or hcaptcha (PLEASE)

### ISSUE THREAD

**Issue by mstdn** [glitch-soc/mastodon#1649]
### Pitch

Meow, meow! 

Since I am running mstdn.social we do get quite a lot of new "users" on average per day. Since the most recent update we now can "mass suspend". I have been waiting for that option since we are over run with "non-active" business and spam accounts that where just too much to one by one.. (I did for a loong time)

### Motivation

But after suspending pages and pages of idle bot accounts I wanna ask for a captcha on the signup page.. Optional would be perfect since others perhaps don't want this but we REALLY NEED it so much.. 

The "honeypot" feature does not work at all it seems, if I where to guess 80% or more of all new signups per day are bots. I've come to Glitch for this since I don't think it's gonna get implemented in vanilla and that's okay but I really really hope you can take it into consideration <3 

Thank you!

**Comment by ThatOneCalculator** [comment]
I feel like HCaptcha would be far more appropriate than ReCaptcha, given the nature of the Fediverse/Mastodon being inherently anti-big-tech.

**Comment by Solsticely** [comment]
is the idea of using a PoW captcha like [Friendly Captcha](https://friendlycaptcha.com/) worth considering? Other than the whole anti-monopolisation thing I don't see much benefit to it, though it is nice to have more options on the table

**Comment by ClearlyClaire** [comment]
> is the idea of using a PoW captcha like [Friendly Captcha](https://friendlycaptcha.com/) worth considering? Other than the whole anti-monopolisation thing I don't see much benefit to it, though it is nice to have more options on the table

I would be very surprised if it were an effective antispam, especially in the long run. On the other hand, it seems easy to set up and have less privacy and accessibility issues than alternatives.

**Comment by mstdn** [comment]
Not sure that's a good option, for the basic (non commercial) package they 'only' offer 1000 validations per month. That's not very much, especially if some users take a few tries. 

I would be starting at the 39,- package for that on a minimum.. I'd rather invest the time for moderation since the costs are big enough with 50K users😅♥️

What would be the issue with hCaptcha for example? I see the obvious reasons with Google's recaptcha

**Comment by ClearlyClaire** [comment]
> Not sure that's a good option, for the basic (non commercial) package they 'only' offer 1000 validations per month. That's not very much, especially if some users take a few tries.
> 
> I would be starting at the 39,- package for that on a minimum.. I'd rather invest the time for moderation since the costs are big enough with 50K userssweat_smile

Yeah no, their pricing just does not make sense. A single attacker can easily empty your validation quota, spending only a fraction of what you would pay for that quota.

It should be somewhat easy to reimplement the server-side component directly in Mastodon, thus not having to pay a cent nor needing an API key, but again, I doubt this technique actually does anything to prevent spam registrations. It is probably not worth the effort.

> What would be the issue with hCaptcha for example? I see the obvious reasons with Google's recaptcha

The issues are basically the same as with Google's reCaptcha: you're including unvetted JS from a third-party, allowing it to send queries to that same third-party, it requires javascript, has accessibility issues, requires downloading images from that third-party, and is very annoying to the end-user. The only benefit compared to reCaptcha is that the privacy policy is friendlier.

**Comment by Solsticely** [comment]
Plemora's builtin captcha has accessibility issues, [in addition to being vulnerable to ML attacks](https://en.wikipedia.org/wiki/CAPTCHA#Circumvention). hCaptcha sounds like a better solution to me :woman_shrugging:

**Comment by mstdn** [comment]
> Plemora's builtin captcha has accessibility issues, [in addition to being vulnerable to ML attacks](https://en.wikipedia.org/wiki/CAPTCHA#Circumvention). hCaptcha sounds like a better solution to me :woman_shrugging:

Ohhh! I did not know that. That's not an option indeed, perhaps hCapcha than..

**Comment by mstdn** [comment]
Little update:

Since early this morning there seems to be some sort of "bot signup attack" going on on mstdn.social. In the past few hours we got over a 1000 new accounts many with the same domain email (something random) and often the same IP's. 

I'm currently suspending in batches and blocking IP's and email domains but it's almost overkill work. Currently our signups are on "approval" but I totally feel beaten by bots at this point.. 

PLEASE, can we take an extra look at this issue. I am sure I am not the only one and somewhere I have a feeling mastodon.social and maybe .online has also this issue at the moments since somehow we have much in common when stuff happens around the fedi. 

90% of my time on Mastodon I am suspending endless bot accounts that drive me nuts, and yes I know we can change signup to approval but like I said this feels so like they've beaten us :(

**Comment by ThatOneCalculator** [comment]
I feel like this should be an easy fix. I don't write in ruby, but if like 5 accounts are made within the span of a minute all with the same IPs, maybe it could temporarily blacklist that IP. just a though.

**Comment by weex** [comment]
Looking at the history it seems switching to invite mode or approval is the predominant recommendation. Bots get better at their captcha-solving job plus they can employ humans while humans are.... well we do have legitimate social circles that can be leveraged with invites.

Best is probably a custom captcha so something like "Fill in the blank: mstd_" becomes possible. Then you use the fedi's long-tail as an asset and make spammers deal with instances one-at-a-time.

**Comment by ClearlyClaire** [comment]
There's definitely more that we can and should do wrt. signup rate-limiting by IP (and it is something that is planned), but it's definitely not going to stop registration spam altogether.

Rate-limiting by email provider is probably not doable, and is unlikely to be effective, as domain names can also be pretty cheap.

Captcha solutions tend to be more effective, but solution to somewhat cheaply solve them routinely pop up, and using a captcha comes with a lot of tradeoffs (accessibility issues, potential privacy issues, …); not something I'm completely opposed to though, and I will probably have a look at implementing it soon-ish.

**Comment by mstdn** [comment]
Thank you! 

Like I said, optional would be awesome! I wouldn't use it by default but only enable it when I notice a spam attack like the past days :-) 

So maybe an admin option extra would make it complete(if configured etc). But editing env isn't an issue. 

Since yesterday our signups are on approval basis but still we get many bot signup requests, even when reason is enabled. It seems they have a default rule for that.. 

Also yesterday we noticed it's not only 'private' email domain that's the issue but also A LOT of Gmail.com addresses. It's very clear their service is heavily abused.. Luxkily we can find them easy with search patterns in mod panel but still it feels like putting out a fire that's been burning for some time now haha..!

Thank you for taking this serious and hopefully we can test some solutions soon-ish♥️

**Comment by mstdn** [comment]
Little update on our spam attack:

Since a week now we have signups on approval requiring a reason to join. This is the result from a few hours :( 

The past week we have had thousands of these.. They're now using Gmail and various IP's. I feel like it's a losing battle, other users came up with an invite link idea but that can also be abused when the URL is known.. Also it closes API signup ad that sucks 🤔 

<img width="731" alt="Schermafbeelding 2021-12-31 om 14 38 55" src="https://user-images.githubusercontent.com/57602062/147826220-3eef109d-c8e3-4d62-8545-0cfeb5700b48.png">

**Comment by ClearlyClaire** [comment]
https://github.com/mastodon/mastodon/pull/15275 would be a good short-term solution to this kind of registration spam, although it could easily be evaded. Past that, I am not too sure what could help.

Invite links can be set to a limited number of usages.

The signup API itself is an issue because it makes it extremely easy for bots to register, and can't be easily extended to add other requirements or things like CAPTCHA verification either.

**Comment by mstdn** [comment]
Little question.. Since the https://github.com/mastodon/mastodon/pull/15275 is not merged yet we had to close down signups. Today it was over a thousand and it was too much.. 

For now we use an invite link on the signup message but it's not optimal since mstdn.social will be put away as "closed signups" on joinmastodon and API also doesnt work with signup ofc! 

I found that QOTO.org has implemented Hcaptcha (https://git.qoto.org/qoto/qoto/-/commit/939a89006b20e3f912d20a16126774884e6bd918) and I was think about taking that over but only if it will not be a feature in Glitch, I like to avoid future merged.

**Comment by ClearlyClaire** [comment]
There are a few things I dislike in this commit. I'll try to write a PR for Hcaptcha support tomorrow!

That being said, I'm surprised you are facing so much bots when I don't think an instance like mastodon.social is suffering quite as much, I wonder if they have different filtering techniques, or if you're somehow especially targeted…

**Comment by mstdn** [comment]
Thank you!!♥️

I wonder the same thing and asked Eugen about it, no response on that one unfortunately. But there are some other admins facing the same issue. Not quite as much as us though.. 

Also, today all bot accounts from when I set this issue in motion got deleted permanently resulting in over 8.6 million sidekiq backlog, still trying to work it away but it's gonna take some time.

**Comment by ClearlyClaire** [comment]
You can try #1665, it should work properly. I expect this to block a huge part of your bot registrations at first, then be less effective if you're specifically targeted or more people adopt this.

I think I'll merge the PR if I can't find better ways to isolate hCaptcha code first.

**Comment by mstdn** [comment]
> You can try #1665, it should work properly. I expect this to block a huge part of your bot registrations at first, then be less effective if you're specifically targeted or more people adopt this.
> 
> I think I'll merge the PR if I can't find better ways to isolate hCaptcha code first.

Thank you so very much for this! Really! 

A merge would be really amazing since we have some changes, I can simply merge upstream than :) 

Fo now this would be a sufficient fix I think, if I where to be targeted I have to look for other solutions but in this case I suspect it's a botnet that abuses the Masto API since I'm not the only one. Also I doubt mastodon.social .online doesn't have this issue but I cannot check for sure

**Comment by ThatOneCalculator** [comment]
I got DM'd by a thirst bot from mastodon.social, so yea, they 100% have a bot problem lol
