### ISSUE TITLE
Timeline feed freezes(stops loading) after a while

### ISSUE THREAD

**Issue by mstdn** [glitch-soc/mastodon#1654]
### Steps to reproduce the problem

1. Update with latest code
2. Open multi-column side and let it stay for a while
3. At some point all timelines stop loading new feed and halt
...

I'm not sure what causes this issue but I can't find anything weird in the logs. I am sure there are new toots cause when I reload the page it starts working again.

Tested in Google Chrome

### Expected behaviour

Timelines keep loading

### Actual behaviour

They stop at some point

### Specifications

- Latest Glitch-soc

**Comment by ClearlyClaire** [comment]
Can you check the mastodon-streaming logs?

**Comment by mstdn** [comment]
> Can you check the mastodon-streaming logs?

Yess! The only thing in streaming logs are the start and stopping of timelines:

 Ending stream from timeline:public:local for 5168

When i reload the page it does set one to start again for my process. Not sure why it stops though

**Comment by ClearlyClaire** [comment]
I can't reproduce it and I don't know what could be happening. Does this keep happening or was it a one-time thing? Does it affect your other users? Is there something in the browser's javascript console?

**Comment by mstdn** [comment]
> I can't reproduce it and I don't know what could be happening. Does this keep happening or was it a one-time thing? Does it affect your other users? Is there something in the browser's javascript console?

It kept happening last night, from then I went checking things out. Today I'll keep my eye out and ask instance users if they experience the same ;) I leave this issue open for today and get back to you later! 

Happy new year in advance <3

**Comment by mstdn** [comment]
Okay so it happened again a few times, most recent a few minutes ago. I checked console log for error but nothing special shows up (see image):

<img width="555" alt="Schermafbeelding 2021-12-31 om 23 38 03" src="https://user-images.githubusercontent.com/57602062/147852147-1ab09ca3-dc20-4d64-8957-4352209f4316.png">

I posted also a local toot to ask for users if they experience the same issue and a few did. The only thing I see in the logging is the start and stopping of the stream for *** (i guess user ID). 

Also when this issue occurs I also do not get push noti's on web anymore, mobile push keeps working luckily

**Comment by mstdn** [comment]
This one also just popped up a few times, but seems unrelated. 

<img width="533" alt="Schermafbeelding 2022-01-01 om 14 58 22" src="https://user-images.githubusercontent.com/57602062/147852229-23dbe13c-5c48-41cd-b473-6546b9eadc4f.png">

**Comment by ClearlyClaire** [comment]
This is surprising, push notifications do not use webfinger, and there is no difference on Mastodon's side between push notifications for your browser and push notifications for your mobile app. This seems to point to an issue on your browser's side but I have no idea what it could be.

**Comment by mstdn** [comment]
> This is surprising, push notifications do not use webfinger, and there is no difference on Mastodon's side between push notifications for your browser and push notifications for your mobile app. This seems to point to an issue on your browser's side but I have no idea what it could be.

Aha..! I'm currently using the latest stable Chrome for macOS. I'm gonna try for a while in FireFox and see if this also has the same issue

**Comment by mstdn** [comment]
So I just tried Firefox for an hour and it went fine until a certain point! Maybe I can try to give a little image from what happened: 

- On my MacBook I had Masto web UI open with default 4 col on local timeline. (we have boosts on public enabled).
- From iOS i did some GIF posts and checked back on desktop
- Home timelines did load but local timeline stopped and didn't show my recent posts from mobile
- Switch to global and back to local again and they suddenly do load..

It feels like at a certain point it just closes connection for a certain timeline or something.. 

Im gonna clear all caches and browser data from my mac now and try this again.

**Comment by mstdn** [comment]
Sorry to bother again! 

I just tested out this issue on multiple desktop devices and even on vanilla. 

Situation:
- 2 Macbooks in front of me both running Chrome(also tested on FF)
- Both logged in on web UI and set on local timeline (multi col)
- After 10 min or so both screens are completely different in timeline streams. For example, one is just stuck on the local TL but keeps loading new in Home. The other does almost the opposite. Notification do come in on mobile but not always on Desktop.
- Tested this also with a vanilla source and it seems it has the same issue. For example: open the global timeline and go do something else for a bit. Come back after a while and a point its just stuck on loading. And this is a different server(!)

I'm not really sure what to do or where to look since I can't find anything strange. But it does appear on multiple devices & multiple browsers. Also I'm not the only one with the issue it seems

**Comment by mstdn** [comment]
Just did some tests with multiple browsers and streaming logs and this was the result:

- 2 browsers, same account, both focus on Local TL.
- In logs I see a "local" streaming closed, not sure that's mine..
- The local TL just stops loading in the "frist" window

Sorry, I really don't get it.. If I can't find a fix for this the only option is to downgrade to vanilla stable release :( 

![941c72652379f290](https://user-images.githubusercontent.com/57602062/148550756-437502a9-0dc6-4352-a2c3-79e877083f69.png)

**Comment by ClearlyClaire** [comment]
I still cannot reproduce this. If this is reproducible using upstream Mastodon code, please report it there. If not, please try the “vanilla” flavor in glitch-soc to see if this is reproducible.

> Okay so it happened again a few times, most recent a few minutes ago. I checked console log for error but nothing special shows up (see image):

This one error is interesting. I guess it *might* explain missing *notifications* but I fail to see how it could cause timelines top update. I'll investigate it.

> If I can't find a fix for this the only option is to downgrade to vanilla stable release :(

While you probably *can* safely downgrade to latest stable, you will have to be careful about database migrations, it's way old, and you'll lose some features and associated data/config (e.g. toot auto-cleanup).

**Comment by ClearlyClaire** [comment]
Nevermind, I did just manage to reproduce it. Not sure what's happening yet but I can at least confirm the issue exists.

**Comment by ClearlyClaire** [comment]
I'm making some progress but I have no estimate on when I'll be able to push a fix yet. In the meantime, a possible workaround might be to set `STREAMING_API_BASE_URL=https://your.domain` in `.env.production` (where `your.domain` is to be replaced with the same value as `WEB_DOMAIN` if that is defined, or `LOCAL_DOMAIN` otherwise)

**Comment by mstdn** [comment]
> I'm making some progress but I have no estimate on when I'll be able to push a fix yet. In the meantime, a possible workaround might be to set `STREAMING_API_BASE_URL=https://your.domain` in `.env.production` (where `your.domain` is to be replaced with the same value as `WEB_DOMAIN` if that is defined, or `LOCAL_DOMAIN` otherwise)

Thank you! I'm gonna try it right away. You're the best!

**Comment by mstdn** [comment]
I'm afraid this does not solve the issue :( Also it results in some errors in console 

<img width="1210" alt="Schermafbeelding 2022-01-07 om 15 44 27" src="https://user-images.githubusercontent.com/57602062/148560273-41757a1d-5053-4613-9b54-99c958d7d01d.png">

**Comment by ClearlyClaire** [comment]
I believe this is fixed by https://github.com/mastodon/mastodon/pull/17259 which can safely be cherry-picked into glitch-soc.

**Comment by mstdn** [comment]
Thank you truly @ClearlyClaire, the issue has been fixed! You're an angel! 👼
