### ISSUE TITLE
"Unconfirmed" accounts should not be shown public

### ISSUE THREAD

**Issue by mstdn** [glitch-soc/mastodon#1669]
### Pitch

In the whole spam case from a few days ago we have opened up signups again with hCaptcha enabled. It immediately had effect since the bots started signing up again. 

For now it seems the accounts are not getting activated so that's a big win! 

However.. I did spot something unusual. When a new account has not been confirmed by email it does show up on the public account page(for the time it exists) and I'm not really getting that. 

A new account should only be active when it's fully confirmed right?  

### Motivation

In this case I want to remove the possibility of a "botnet connection" with the publicly (temporary) created accounts. In the past mstdn.social but also mastodon.social has issues with a "malicious botnet actor" that was simply a default account. (I did had a IP in the bio but not sure if that matters).

**Comment by ClearlyClaire** [comment]
Please report that upstream, it's the same behavior there.
