### ISSUE TITLE
travis errors with mutes

### ISSUE THREAD

**Issue by MightyPork** [glitch-soc/mastodon#167]
some ruby errors, I think this is for @ekiru

there's a lot of them, but they're all the same:
![screenshot_20171012_084303](https://user-images.githubusercontent.com/2041118/31482702-9c1c16f6-af29-11e7-9769-4ccfb86afa3c.png)

**Comment by yipdw** [comment]
edd1a00fafb5d41afad0c177e7c2f2f6adae6d19 resolves these errors (see e.g. https://travis-ci.org/glitch-soc/mastodon/jobs/286944193).  There's another build failure, but it looks like it's from eslint.

**Comment by yipdw** [comment]
Build 437 (https://travis-ci.org/glitch-soc/mastodon/builds/287076520) now passes.
