### ISSUE TITLE
Prompt for alt-text before allowing to submit a doodle

### ISSUE THREAD

**Issue by MightyPork** [glitch-soc/mastodon#170]

**Comment by yipdw** [comment]
Would it be possible to have the existing alt-text field be focused after pressing Done on the doodle dialog? That'd draw attention and would allow alt-text to be entered with no additional mouse or keyboard motion.

**Comment by MightyPork** [comment]
possibly. It's not 100% straightforward, because the image card and it's alt text box doesn't exist until the upload finished. Maybe it can be added to the axios done callback...

**Comment by beatrix-bitrot** [comment]
i really like this idea

**Comment by ThibG** [comment]
Closing as there is a setting implementing that (but generalized to any media).
