### ISSUE TITLE
Vanilla Explore Trending Posts & News empty

### ISSUE THREAD

**Issue by mstdn** [glitch-soc/mastodon#1722]
### Steps to reproduce the problem

1. Switch to vanilla flavour
2. Checkout trending links or posts
3. Posts says there's nothing trending while there is in admin. News seems to be completely empty. 
...

<img width="373" alt="Schermafbeelding 2022-03-23 om 18 12 58" src="https://user-images.githubusercontent.com/57602062/159757138-9c0ffa17-4d3a-494f-bdcd-fa3a65e9316c.png">

<img width="383" alt="Schermafbeelding 2022-03-23 om 18 13 13" src="https://user-images.githubusercontent.com/57602062/159757170-753ca160-b06f-417f-8f28-a853923cee49.png">

---
Will the Explore feature also be ported to Glitch-soc? Me personally and many users would love this <3 

### Expected behaviour

Trending posts & trending news(links) showing

### Actual behaviour

Nothing

### Specifications

Most recent changhes.

**Comment by mstdn** [comment]
Is this planned to be fixed in the future? :) And also added to Glitch-soc maybe?

**Comment by ClearlyClaire** [comment]
Trends are localized, if the posts are not written in your interface language, they don't show up. That's upstream behavior.

**Comment by mstdn** [comment]
> Trends are localized, if the posts are not written in your interface language, they don't show up. That's upstream behavior.

But there are many links I constantly approve.. and in the beginning this was the case. But since a while it's empty everytime, even after I allow publishers / links in English or any other language
