### ISSUE TITLE
Sidekiq Chewy job failed with NoMethodError: undefined method `extract_status_plain_text' for StatusesIndex:Class

### ISSUE THREAD

**Issue by tribela** [glitch-soc/mastodon#1727]
### Steps to reproduce the problem

1. Post with ES enabled
2. watch sidekiq retry queue
3. filled up with `NoMethodError: undefined method 'extract_status_plain_text' for StatusesIndex:Class`
...

### Expected behaviour

Chewy job processed normally

### Actual behaviour

Failed with error and fills up retry queue

### Specifications

Version: glitch-soc/mastodon@eaea84903

**Comment by ClearlyClaire** [comment]
Sorry for that, should be fixed now!
