### ISSUE TITLE
Markdown post with link to LOCAL_DOMAIN is malfunctioning

### ISSUE THREAD

**Issue by tribela** [glitch-soc/mastodon#1739]
### Steps to reproduce the problem

1. Go to mastodon.tld
2. Write a post like `blababla [test link](https://mastodon.tld/some_link)`
3. The post content is totally blank
...

### Expected behaviour

Link and post should be shown

### Actual behaviour

The post content is total blank

### Specifications

v3.5.1+glitch 9309c53d21df806d57dd59dbc59a807d2f8b8b11

**Comment by single-right-quote** [comment]
Ah! So it is a glitch-soc thing! We&#8217;ve had the same problem over at our fork (kibicat/mastodon#40); the same thing happens with HTML posts. Interestingly, mentions do get processed and attached to the status its content is blanked.
