### ISSUE TITLE
Massive increase on server load

### ISSUE THREAD

**Issue by mstdn** [glitch-soc/mastodon#1746]
### Steps to reproduce the problem

1. Updated to latest Glitch-soc code
2. Keep eye on server load
3. Wow
...

Before the latest update our server load was ~4 - 10.0 sometimes but since the last update we just ran into 44 - 55.. Currently it's more "stable" around 15-20 but still, what is happening here? 

I didn't change a ting on services or whatever, not sure this could be it but it does runs a lot more postgres tasks it seems?

<img width="657" alt="Schermafbeelding 2022-04-16 om 17 04 59" src="https://user-images.githubusercontent.com/57602062/163680095-8bd244eb-14b2-4acf-a06f-e1f24a3c29a7.png">
 
<img width="651" alt="8f042413c262459c" src="https://user-images.githubusercontent.com/57602062/163680211-709b8adc-73d4-4ff0-8c4e-b5db61dfdab6.png">

### Expected behaviour

"normal" server load

### Actual behaviour

Server is getting slow, and it's big..

### Specifications

Latest code

**Comment by mstdn** [comment]
I'm gonna revert back to last "safe" commit. Server keeps crashing

**Comment by ClearlyClaire** [comment]
Does applying this patch help?

```patch
diff --git a/app/models/home_feed.rb b/app/models/home_feed.rb
index 447445092..53550b7db 100644
--- a/app/models/home_feed.rb
+++ b/app/models/home_feed.rb
@@ -44,10 +44,8 @@ class HomeFeed < Feed
   protected
 
   def from_database(limit, max_id, since_id, min_id)
-    scope = Status.where(account: @account.following)
-    scope = scope.left_outer_joins(:mentions)
-    scope = scope.where(visibility: %i(public unlisted private)).or(scope.where(mentions: { account_id: @account.id })).group(Status.arel_table[:id])
-    scope = scope.or(Status.where(account: @account))
+    scope = Status.where(account: @account).or(Status.where(account: @account.following))
+    scope = scope.where(visibility: %i(public unlisted private))
     scope
       .to_a_paginated_by_id(limit, min_id: min_id, max_id: max_id, since_id: since_id)
       .reject { |status| FeedManager.instance.filter?(:home, status, @account) }
```

**Comment by mstdn** [comment]
> Does applying this patch help?
> 
> ```diff
> diff --git a/app/models/home_feed.rb b/app/models/home_feed.rb
> index 447445092..53550b7db 100644
> --- a/app/models/home_feed.rb
> +++ b/app/models/home_feed.rb
> @@ -44,10 +44,8 @@ class HomeFeed < Feed
>    protected
>  
>    def from_database(limit, max_id, since_id, min_id)
> -    scope = Status.where(account: @account.following)
> -    scope = scope.left_outer_joins(:mentions)
> -    scope = scope.where(visibility: %i(public unlisted private)).or(scope.where(mentions: { account_id: @account.id })).group(Status.arel_table[:id])
> -    scope = scope.or(Status.where(account: @account))
> +    scope = Status.where(account: @account).or(Status.where(account: @account.following))
> +    scope = scope.where(visibility: %i(public unlisted private))
>      scope
>        .to_a_paginated_by_id(limit, min_id: min_id, max_id: max_id, since_id: since_id)
>        .reject { |status| FeedManager.instance.filter?(:home, status, @account) }
> ```

Thank you, just applied and it seems to work!

**Comment by mstdn** [comment]
Crashed again after some time away.. Reverted

**Comment by ClearlyClaire** [comment]
What is the last “safe” commit?

When your server is under load, can you connect to postgresql and get the output of the following query?
```sql
SELECT
  query
FROM pg_stat_activity
WHERE (now() - pg_stat_activity.query_start) > interval '1 minutes';
```

**Comment by mstdn** [comment]
That would be: https://github.com/mstdn/Mastodon/commit/648671ae664e529c4e9a6befa59d706666dab7b2
(sorry, out repo but you get it)

Currently I can't update for a bit, I'll try later when signups are a bit more quite

**Comment by ClearlyClaire** [comment]
The query seemed simple enough, but PostgreSQL can't actually plan anything else than what amounts to a scan over *all statuses* (which can still be pretty fast if most of the recent statuses are actually in the timeline, or extremely slow if they are further back). Reverting the whole feature in #1748 as I could not find a way to optimize it.
