### ISSUE TITLE
Win95 skin on vanilla flavour is totally broken

### ISSUE THREAD

**Issue by tribela** [glitch-soc/mastodon#1753]
### Steps to reproduce the problem

1. Switch to vanilla flavour
2. Switch to masto95 skin
3. layout is broken. cannot get back to normal skin without dev console trick
...

### Expected behaviour

win95 theme should work nicely

### Actual behaviour

user cannot get back and layout is broken

### Specifications

Glitch: `fbe212de6`
Browser: firefox

**Comment by ClearlyClaire** [comment]
I think #1755 addresses it

**Comment by kescherCode** [comment]
#1755 has addressed this - issue should be closed
