### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR: column "total_plan_time" does not exist

### ISSUE THREAD

**Issue by lunaisnotaboy** [glitch-soc/mastodon#1777]
### Steps to reproduce the problem

1. Enable query stats in `postgresql.conf` as directed by the PGHero interface.
2. Restart PostgreSQL and Mastodon.
3. Go to `/pghero` in a browser.

### Expected behaviour

The PGHero dashboard should've loaded with query stats now enabled.

### Actual behaviour

It returned a 500 error.

### Specifications

This is in the most recent commit in our fork of Glitchsoc (https://github.com/mint-lgbt/fedimint/commit/fcd0c583fd0a7e46060d3cfcc95adc36fb805349). Below is some more details from our Sentry instance that picked up the data:

```
Browser: Chrome 96.0.4664
Client OS: Chrome OS 14268.67.0
Environment: production
OS: Linux #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022
Runtime: ruby ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
Transaction: PgHero::HomeController#index
```

You'll probably find the brief amount of information at https://github.com/mint-lgbt/fedimint/issues/1 useful.

**Comment by ClearlyClaire** [comment]
I'm not sure how that's in scope for glitch-soc, as it's an issue with the PostgreSQL deployment in relation to PgHero, not a feature Mastodon/glitch-soc itself provides or can do anything about.

**Comment by lunaisnotaboy** [comment]
My apologies.

**Comment by ClearlyClaire** [comment]
No worries!
