### ISSUE TITLE
New tootctl search deploy algorithm breaks the command (likely upstream issue)

### ISSUE THREAD

**Issue by kescherCode** [glitch-soc/mastodon#1781]
### Steps to reproduce the problem

1. Run tootctl search deploy
2. Receive error seen in this log file https://cloud.kescher.at/s/oda9FRQBc3npKTe

### Expected behaviour

It should succeed, and go faster.

### Actual behaviour

It goes faster, however, it fails quite soon on a "missing attribute: cached_tallies" and spits out a backtrace.

### Specifications

Any commit after a9b64b24d6c076cb96a66307c07d4f0158dc07da is affected.

**Comment by ClearlyClaire** [comment]
This is weird. I don't know what could be causing that. Can you confirm that it is caused by the recent upstream changes? Do you have pending migrations? Have you altered your database schema? Does the `polls` table have a `cached_tallies` column?

**Comment by kescherCode** [comment]
@ClearlyClaire 

> Can you confirm that it is caused by the recent upstream changes?

Yes, I reverted the commit and this fixes the issue.
> Do you have pending migrations?

No. I run all the migration steps each time I update Mastodon (or rather, [Catstodon](https://github.com/kescherCode/catstodon), the minimal fork of glitch-soc) on my server accessible at [catcatnya.com](https://catcatnya.com).

> Have you altered your database schema?

No.

> Does the `polls` table have a `cached_tallies` column?

```
mastodon_production=# \d polls
                                           Table "public.polls"
     Column      |            Type             | Collation | Nullable |              Default              
-----------------+-----------------------------+-----------+----------+-----------------------------------
 id              | bigint                      |           | not null | nextval('polls_id_seq'::regclass)
 account_id      | bigint                      |           |          | 
 status_id       | bigint                      |           |          | 
 expires_at      | timestamp without time zone |           |          | 
 options         | character varying[]         |           | not null | '{}'::character varying[]
 cached_tallies  | bigint[]                    |           | not null | '{}'::bigint[]
 multiple        | boolean                     |           | not null | false
 hide_totals     | boolean                     |           | not null | false
 votes_count     | bigint                      |           | not null | 0
 last_fetched_at | timestamp without time zone |           |          | 
 created_at      | timestamp without time zone |           | not null | 
 updated_at      | timestamp without time zone |           | not null | 
 lock_version    | integer                     |           | not null | 0
 voters_count    | bigint                      |           |          | 
Indexes:
    "polls_pkey" PRIMARY KEY, btree (id)
    "index_polls_on_account_id" btree (account_id)
    "index_polls_on_status_id" btree (status_id)
Foreign-key constraints:
    "fk_rails_3e0d9f1115" FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
    "fk_rails_5b19a0c011" FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
Referenced by:
    TABLE "poll_votes" CONSTRAINT "fk_rails_a6e6974b7e" FOREIGN KEY (poll_id) REFERENCES polls(id) ON DELETE CASCADE
```

**Comment by ClearlyClaire** [comment]
Seems like an upstream issue, we're investigating it, thanks!

**Comment by kescherCode** [comment]
088dc0ec5a383006952c0b15508af882a4c1109c is intended to fix this issue, right?

**Comment by ClearlyClaire** [comment]
yes

**Comment by kescherCode** [comment]
Deployed on CatCatNya~, and it works now!
