### ISSUE TITLE
Time between midnight and 01:00 on toot in web UI shows as 24:mm

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#1808]
### Steps to reproduce the problem

1. Copy and paste this URL into the search box of the Mastodon web UI on a Glitch instance and press enter: https://lgbt.io/@gendercensus/108670912725585842
2. Behold:

<img width="328" alt="Screenshot_2022-07-19_at_19_35_48" src="https://user-images.githubusercontent.com/6607512/179824210-b91c51e2-95cf-4acf-a0ed-9987fb6cc8b2.png">

### Expected behaviour

Time shows as 00:mm

### Actual behaviour

Time shows as 24:mm

### Specifications

LGBT.io, v3.5.3+glitch

**Comment by mstdn** [comment]
Is upstream issue: https://github.com/mastodon/mastodon/issues/18414

**Comment by Cassolotl** [comment]
@mstdn Thank you, I'll close this then. :)
