### ISSUE TITLE
No image previews on toots with content warning (CW)

### ISSUE THREAD

**Issue by mxamber** [glitch-soc/mastodon#1812]
### Steps to reproduce the problem

The instance I'm on recently switched to glitchsoc, and I noticed that the options regarding image previews no longer seem to be working. To reproduce, just look at any toot with a CW and at least one image.

### Expected behaviour

The toot should show the CWE tag and below it a blurred preview of the image, if that option is enabled in the user preferences  ("Show colorful gradients for hidden media")

### Actual behaviour

Instead, no image appears at all, blurred or not. The CW tag has a little picture icon next to it, which is incredibly easy to miss. None of the glitchsoc-specific options ("Preview collapsed toot media" etc) seem to change this, either.

### Specifications

Happened on up-to-date Firefox (102) on Windows and Ubuntu. Instance is on version Mastodon 3.5.2+glitch.

**Comment by ClearlyClaire** [comment]
In glitch-soc, image attachments and polls are considered content, and thus hidden behind content warnings. There is no option to change that behavior.

**Comment by mxamber** [comment]
That doesn't seem very useful.

**Comment by sk22** [comment]
If you're used to seeing posts containing images as posts with a blurred image preview, it feels pretty disruptive not to see the image preview at all – if feels as if it were a text-only post.
I think the option to turn the blurred image previews on and off should definitely be there.

**Comment by ClearlyClaire** [comment]
> That doesn't seem very useful.

Neither does your comment. Media attachments have been moved under CWs over 5 years ago (before I even started working on glitch-soc, see #38) and it's the first time I have seen someone complain about it. I'm not saying that to dismiss your use case, but try not to be this abrasive with your comments.

> If you're used to seeing posts containing images as posts with a blurred image preview, it feels pretty disruptive not to see the image preview at all – if feels as if it were a text-only post.

I understand that it's not as visually obvious, but there are multiple indications that the post does contain a media attachment:
![image](https://user-images.githubusercontent.com/384364/180638646-fa0821ee-8de7-4f16-b889-5685fcd75861.png)

In my opinion, it is not especially useful to have a placeholder of any kind outside the Content Warning fold, and I am not sure what kind of information is provided by having an extremely blurry image preview.

> I think the option to turn the blurred image previews on and off should definitely be there.

I'm considering adding such an option, but it would definitely not be enabled by default, for the reasons discussed above.

**Comment by mxamber** [comment]
> In my opinion, it is not especially useful to have a placeholder of any kind outside the Content Warning fold, and I am not sure what kind of information is provided by having an extremely blurry image preview.

I often scroll the local timeline for interesting posts and posts with images are usually more interesting than those without. So seeing a big colourful rectangle immediately tells me there's potentially cool stuff to be looked at. Now I would have to look at every post instead of just glancing over dozens at once. That might be a very specific use case, but that's my use case.

**Comment by mxamber** [comment]
Lest I open another fruitless ticket: is CW tags closing themselves a feature too?

**Comment by ClearlyClaire** [comment]
Closing themselves? Can you elaborate?

**Comment by ClearlyClaire** [comment]
Also, how has this ticket been fruitless? The option you've asked for has been implemented.

**Comment by mxamber** [comment]
> Closing themselves? Can you elaborate?

The stock behaviour is that opening a CW once keeps it open. So opening a CW in the timeline, it will still be open if I click on the toot, or if I get a notification on it. What I'm seeing in glitch 3.5.2 currently is that every time I change views (go to notifs, click on a toot, etc), I have to re-open the same CW. This is all happening in the same tab, no reloading or opening it in a different tab.

> Also, how has this ticket been fruitless? The option you've asked for has been implemented.

Oh, I missed that. I stand corrected.

**Comment by ClearlyClaire** [comment]
> > Closing themselves? Can you elaborate?
> 
> The stock behaviour is that opening a CW once keeps it open. So opening a CW in the timeline, it will still be open if I click on the toot, or if I get a notification on it. What I'm seeing in glitch 3.5.2 currently is that every time I change views (go to notifs, click on a toot, etc), I have to re-open the same CW. This is all happening in the same tab, no reloading or opening it in a different tab.

In glitch-soc, each instance of a toot has its own state, like it used to be on upstream Mastodon. This is by design, but it is true that it may be jarring when using the single-column UI where you keep changing views, and the state resets. In any case, I believe #1815 implements the option you're looking for.
