### ISSUE TITLE
Markdown numbered lists' numbers are heavily clipped in desktop Safari and iOS. Only slightly clipped in desktop Firefox/Chrome

### ISSUE THREAD

**Issue by fasiha** [glitch-soc/mastodon#1878]
### Steps to reproduce the problem

Toot a numbered list, like
```
1. First
2. Second
3. Third   
```

See example at https://octodon.social/@22/109265885601418185

### Expected behaviour

Numbers should be clearly visible

### Actual behaviour

The numbers are too far left and mostly clipped in desktop Safari/iOS. Numbers are slightly clipped in  desktop Firefox and desktop Chrome

### Detailed description

**iOS Safari** example from https://octodon.social/@kensanata/109253523351852438

![iOS-safari](https://user-images.githubusercontent.com/37649/199137343-1dbbfce1-59b8-4914-843d-a1a9ed2d7585.jpeg)

**macOS Safari** example

<img width="729" alt="macOS-Safari" src="https://user-images.githubusercontent.com/37649/199137525-ed1527d6-5cd0-4c6b-911b-5ff361578b80.png">

**Desktop Chrome (macOS)** example: note how the tip of the `4` is missing.

<img width="196" alt="macOS-Chrome" src="https://user-images.githubusercontent.com/37649/199137556-e3e09582-adad-4182-9e11-511eb7919451.png">

**Desktop Firefox (macOS)** also has the left tip of `4` missing:

<img width="190" alt="macOS-Firefox" src="https://user-images.githubusercontent.com/37649/199137577-63dfec73-73d6-4b62-8f19-92eb627747f2.png">

**Initial experimentation** messing with Safari Elements inspector and expanding `ol`'s `margin-left` to `2em` (instead of `1em` default) seems to fix the problem, in macOS Safari:

<img width="782" alt="safari-CSS-tweak" src="https://user-images.githubusercontent.com/37649/199137687-a57e5d58-4483-47a7-8bcc-997ef9ddfbae.png">

(But this might not be the best fix of course.)

### Specifications

- v3.5.3+glitch
- iOS version 16.1
- macOS 12.6 (Monterey)
- desktop Safari Version 16.0 (17614.1.25.9.10, 17614)
- desktop Firefox version 106.0.2 (64-bit)
- desktop Chrome Version 106.0.5249.119 (Official Build) (x86_64)

**Comment by prplecake** [comment]
I think changing to `2em` would be a fine change.
