### ISSUE TITLE
Some server-side settings have been lost in upstream merge

### ISSUE THREAD

**Issue by ClearlyClaire** [glitch-soc/mastodon#1890]
Some server-side settings have been lost in an upstream merge:
- `hide_followers_count`
- `show_reblogs_in_public_timelines`
- `show_replies_in_public_timelines`
- `outgoing_spoilers`

It's unclear where we should put them in the new server settings page.

**Comment by kescherCode** [comment]
imo, it should be put into `/admin/settings/discovery`, as that's approximately where it had previously been.
