### ISSUE TITLE
Browser Tab Icon needs a "New Activity" indicator

### ISSUE THREAD

**Issue by Zate** [glitch-soc/mastodon#1891]
### Pitch

In that other previous network, the bird icon gets a red dot on it when I have new messages or interactions.  I hear a sound when I have new information on this platform, but there is no visual indicator.

### Motivation

  It would be handy for hearing-impaired people to have some visual indicators.

**Comment by ClearlyClaire** [comment]
If I understand your request properly, I believe this is already covered by the “Unread notifications favicon badge” setting in the App settings
![image](https://user-images.githubusercontent.com/384364/200125372-75a09185-4050-4802-807d-2f32e20c4d76.png)

**Comment by Zate** [comment]
doh, yep that is exactly what I was after. not sure how I missed it.
