### ISSUE TITLE
Hide followers count not working

### ISSUE THREAD

**Issue by njmulsqb** [glitch-soc/mastodon#1895]
### Steps to reproduce the problem

    Open Settings --> Preferences --> Others
    Check "Hide followers count"
    Save changes
    ...
    After saving changes, the check box will be unchecked itself and settings will be reverted.

### Expected behaviour

Followers count should be hidden

### Actual behaviour

Followers count not hiding even by enabling in settings.

### Detailed description

I checked 
![image](https://user-images.githubusercontent.com/47940898/200183577-78a1527e-d371-48f4-9294-f7dc2dd4aa27.png)
the checkbox and clicked on save changes but it reverted on itself and I cant hide my followers.

The server is @infosec.exchange

### Specifications

Windows 11
Mastodon (v3.5.3+glitch).

**Comment by ClearlyClaire** [comment]
Fixed it yesterday in #1889!

**Comment by njmulsqb** [comment]
It may be irrelevant, but can you tell me when the changes are usually available on the instances e.g infosec.exchange?

**Comment by ClearlyClaire** [comment]
I have no idea, that is up to the infosec.exchange team!
