### ISSUE TITLE
Posts aren't filtered correctly

### ISSUE THREAD

**Issue by prplecake** [glitch-soc/mastodon#1900]
### Steps to reproduce the problem

1. Have a filter set up, for example, 'word'
2. Follow a new account.
3. New account creates post with 'word' in it.

### Expected behaviour

Post should obey filters, and be hidden entirely, or behind click-through warning

### Actual behaviour

Post disobeys filter

### Detailed description

I haven't taken the time to determine if this is an upstream issue. Once the page is refreshed, the posts are correctly filtered.

**Update:** This isn't limited to newly followed accounts! A post was just boosted onto my TL from an account I don't follow with a word I'm intending to filter out. Though, in this case I favorited the post and *then* the filter applied.

### Specifications

My running fork is up to date with [5410156](https://github.com/glitch-soc/mastodon/commit/54101563bbadbfafd9291a867d7fbea6df3a8b7b), and I have made no changes to anything related to filters.

**Comment by prplecake** [comment]
I just noticed that in the single post view, filtered replies are always hidden and the click-through warning isn't shown, though this seems like an entirely separate issue.

**Comment by ClearlyClaire** [comment]
https://github.com/mastodon/mastodon/pull/19963

**Comment by prplecake** [comment]
Closed with #1903
