### ISSUE TITLE
Light theme wrong contrast unusable/inaccessible

### ISSUE THREAD

**Issue by EchedeyLR** [glitch-soc/mastodon#1901]
### Steps to reproduce the problem

1. Install Glitch-Soc
2. Create account
3. Change to light theme
4. Enable confirmation on favourite and boost
5. Try to reply an answer and see no good hightlighed contrast in the post to reply
6. Try to give favourite and observe mixed dark theme with unreadable text because is dark in light theme

### Expected behaviour

Good contrast to highlight answers and be able to read what I am gonna give favourite

### Actual behaviour

Not highlighted post on reply and unreadable posts while making favourite

### Detailed description

There are 2 errors with light theme which I could observe so far:

* While replying a post, the post is not well highlighted causing a little problem in differenciation (usability)
* While making favourite, the confirmation is unreadable because of the dark background like if dark and light theme got mixed

### Specifications

Latest version

**Comment by EchedeyLR** [comment]
Attached examples:

![Screenshot_20221107-071224_Fennec](https://user-images.githubusercontent.com/56733813/200254468-cf09b108-ffdd-48bd-b80f-636f3db77ab7.png)

![Screenshot_20221107-071235_Fennec](https://user-images.githubusercontent.com/56733813/200254454-5b274002-4dc5-4db3-b0c2-d40c007600da.png)

**Comment by ClearlyClaire** [comment]
oof, that's really not good, sorry I didn't catch that in last merge. I'll try to have a look shortly

**Comment by EchedeyLR** [comment]
I have no screenshot of previous version sadly, but I remember perfectly the referenced post being more grey or a blue-greyish color, like to highlight that was being cited.
