### ISSUE TITLE
Build failure - Duplicate message id: "footer.about"

### ISSUE THREAD

**Issue by starfall-system** [glitch-soc/mastodon#1912]
### Steps to reproduce the problem

1. rails webpacker:compile

### Expected behaviour

build succeeds

### Actual behaviour

build fails

### Detailed description

```
ERROR in ./app/javascript/flavours/glitch/features/ui/components/link_footer.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /opt/mastodon/app/javascript/flavours/glitch/features/ui/components/link_footer.js: [React Intl] Duplicate message id: "footer.about", but the `description` and/or `defaultMessage` are different.
```

This ID is repeated on https://github.com/glitch-soc/mastodon/blob/main/app/javascript/flavours/glitch/features/ui/components/link_footer.js line 60 and 80.

### Specifications

ee7e49d

**Comment by ClearlyClaire** [comment]
Do you have any local change? I can't reproduce the issue. The message is indeed repeated, but the `defaultMessage` is the same, so this shouldn't cause any issue.

**Comment by starfall-system** [comment]
Oh, good callout, looks like I did make a local change and forgot about it. Never mind.
