### ISSUE TITLE
Long moderated server names make server moderation list unusable

### ISSUE THREAD

**Issue by ajfite** [glitch-soc/mastodon#1913]
### Steps to reproduce the problem

View the server moderation list at instance/about (you can check out mine with the issue at https://toot.nclf.net/about) after blocking a server with an absurdly long name

### Expected behaviour

Server list is either horizontally scrollable or long server name is truncated

### Actual behaviour

List falls off edge of its container and you can't see the ban reasons for servers

### Detailed description

See photo examples:

Advanced view:
![image](https://user-images.githubusercontent.com/1069581/201185573-18222325-daf1-4444-b98a-be1cc9fb9318.png)

Standard view:

![image](https://user-images.githubusercontent.com/1069581/201185705-e2132538-b8de-4509-8103-4777b754be4f.png)

### Specifications

Firefox 106.0.5
Windows 11

Mastodon v4.0.0rc2+glitch

**Comment by ClearlyClaire** [comment]
Can you report that upstream? That's an issue we inherit from there.

**Comment by ajfite** [comment]
Will do!

**Comment by ajfite** [comment]
https://github.com/mastodon/mastodon/issues/20351 Reported upstream

**Comment by ClearlyClaire** [comment]
Fixed by latest merge!
