### ISSUE TITLE
custom emoji don't display correctly in permalinked posts 

### ISSUE THREAD

**Issue by yungslime** [glitch-soc/mastodon#192]
I'm running the latest glitchsoc master on dev.slime.global and I noticed something strange about custom emoji in permalinked posts.

When viewing the posts within mastodon (be it on dev.slime.global or through another instance), they look fine: 

![chrome_2017-10-20_10-10-20](https://user-images.githubusercontent.com/25403790/31811286-42e210f2-b57f-11e7-9d60-ab8b6ac6253f.png)

but when viewing them by clicking on the permalink, they look like this: 

![chrome_2017-10-20_10-10-27](https://user-images.githubusercontent.com/25403790/31811301-5b70e558-b57f-11e7-8692-83c573337660.png)
https://dev.slime.global/@tom/98860053590943160

standard emoji work fine though. 
![chrome_2017-10-20_10-11-55](https://user-images.githubusercontent.com/25403790/31811307-65717a54-b57f-11e7-9c53-63317d2c8ebc.png)

I checked some posts on dev.glitch.social and it doesn't seem to be happening there, if you need any more info or a demo account on dev.slime.global, feel free to contact me here or on mastodon (@tom@slime.global)

**Comment by MightyPork** [comment]
works fine here: https://dev.glitch.social/@MightyPork/98860248233297583

**Comment by DJSundog** [comment]
Can confirm on the toot-lab

**Comment by yungslime** [comment]
It happened in your web interface too though, right? @djsundog

**Comment by yipdw** [comment]
The custom emoji on https://dev.slime.global/@tom/98860053590943160 are being rendered as images, but a `GET` on their `src` URLs yields 404.  Here's the `src`s:

`:slime:` https://dev.slime.global/system/custom_emojis/images/000/000/001/static/tom_glub_the_third_smaller.png
`:specialagentdalecooper:`: https://dev.slime.global/system/custom_emojis/images/000/000/006/static/3b21e99324a7d8e2.png

URLs like this imply that the emoji files are present in `(app root)/public/system/custom_emojis/images/...`; is that the case with your installation?

**Comment by yungslime** [comment]
okay this is strange, the images weren't there but after manually uploading one of them, it works

**Comment by MightyPork** [comment]
I had something similar happen with my local testing server, actually.
One of the RCs corrupted all my existing custom emojo images

**Comment by yungslime** [comment]
I just tried re-uploading Special Agent Dale Cooper within the custom emojo interface and now that works fine too. 

If re-adding old emoji solves this, the issue can be closed imho. 


 ![3b21e99324a7d8e2](https://user-images.githubusercontent.com/25403790/31843286-748c91b8-b5f2-11e7-8bfa-844bd9570063.png) 

thanks everyone!
