### ISSUE TITLE
Image description edit button goes away after first use

### ISSUE THREAD

**Issue by rtucker** [glitch-soc/mastodon#1925]
### Steps to reproduce the problem

1. New post
2. Add an image
3. Edit -> describe the image -> Save
4. Observe that the Edit button has gone away

### Expected behaviour

The Edit button should still be visible

### Actual behaviour

The Edit button went away after first use

### Detailed description

This happens in both the Glitch and Vanilla Mastodon flavours.

### Specifications

Mastodon v4.0.0rc4+glitchfox-prod2022111401
which is up-to-date with commit 72335694744da87cbfaff20992cb36817f6f8a60

Reproduced on Chrome+macOS and Chrome+Android, haven't tried other browsers, yet

**Comment by ClearlyClaire** [comment]
Oops! Sorry about that! Opened a PR upstream, it'll cascade down as usual: https://github.com/mastodon/mastodon/pull/20665

**Comment by ClearlyClaire** [comment]
Fixed in latest merge!
