### ISSUE TITLE
glitch flavour only: hang in emoji.js

### ISSUE THREAD

**Issue by kescherCode** [glitch-soc/mastodon#1930]
### Steps to reproduce the problem

1. Enable the *Use system's default font for emojis (applies to Glitch flavour only)* checkbox
2. Enable the glitch flavour
3. Open the Web UI
...

### Expected behaviour

Nothing of note

### Actual behaviour

A hang and a massive memory leak due to an infinite loop

### Detailed description

Likely caused by the following lines not being updated by the recent changes. https://github.com/glitch-soc/mastodon/blob/e589afa0ef520747919935956d2d87746000adc9/app/javascript/flavours/glitch/features/emoji/emoji.js#L59-L76

### Specifications

All commits since 71982e5c831f25f7a8d2807c2139b3ac8e26485d

**Comment by ClearlyClaire** [comment]
Thank you so much for figuring out it was due to the system emoji font setting!

**Comment by kescherCode** [comment]
:)
