### ISSUE TITLE
Allow drafting of mathematics using MathML

### ISSUE THREAD

**Issue by 4e554c4c** [glitch-soc/mastodon#1934]
# Pitch

Instances should be able to opt-in to drafting mathematics. This would consolidate differences between instances such as [types.pl](https://types.pl) which renders a subset of LaTeX between delimiters as math, and vanilla glitch. This would also set a precedent for MathML in activities, which would give fediverse software developers a reference for MathML in posts.

## Technical implementation
One of the benefits of rendering LaTeX-like syntax to mathML on the server (like with markdown) is that it will be possible for clients to draft math on mobile apps similarly to in the browser.
Unfortunately, most LaTeX rendering projects are written in Javascript, as they are designed to render LaTeX directly in a browser to an image. However, there are several utilities for performing this that could be integrated with the glitch backend. I've compiled a (non-exhaustive) list of possibilities, along with some pros and cons of each.

#### [Mathematical](https://github.com/gjtorikian/mathematical)
This was the original suggestion in #1432. Unfortunately, since then the project has been archived as the upstream project (Lasem, by the Gnome foundation) has ceased development. Ultimately this project could be revived considering that [lasem](https://github.com/mjakeman/lasem) has been forked. However, this would create an additional project to maintain, probably by me.
Pros:
- great ruby support
- no external dependencies

Cons:
- deprecated, must fork

#### [Texmath](https://github.com/jgm/texmath)
Texmath is a minimal, focused library and CLI for converting between LaTeX and MathML. It has [ruby bindings](https://github.com/hollingberry/texmath-ruby), albeit dated. Unfortunately, texmath is written in Haskell and thus does not integrate well with Ruby. The bindings require an installed CLI. However, I think this is an OK requirement to place on admins of *math specific instances* alone.
Pros:
- Well maintained
- Built for this purpose

Cons:
- poor ruby bindings
- requires installing an additional binary

#### [LaTeXML](https://math.nist.gov/~BMiller/LaTeXML/manual/)
Pros:
- Written in Perl, which is a tad more portable than Haskell

Cons:
- Currently no apparent ruby bindings
- A tad overkill for converting strings (it's designed for documents)

#### [MathJax](https://www.mathjax.org)
MathJax support for MathML is pretty good, since it's internally all MathML. Plus, it's designed to be able to run on a server. Node already has to be installed for mastodon, but a wrapper would have to be written between the ruby backend and MathJax, which must run on node.

Pros:
- Great TeX support, the syntax that mathematicians are expecting

Cons:
- no apparent ruby bindings
- would require shelling out to node

#### [KaTeX](https://katex.org)
KaTeX is a "light" (in comparison to MathJax) new alternative to MathJax.

Pros:
- Supposedly lighter than MathJax

Cons:
- Same as MathJax
- MathML support [doesn't seem as good as in MathJax](https://github.com/KaTeX/KaTeX/issues/1876)

# Motivation

Please see mastodon/mastodon#19806, which is a dependency for this issue. I have already created a PR "closing" that task for glitch in #1933.
This feature request is partially motivated in #1432 and the above issue. It would be nice to draft mathematics in a way that is cross-instance. In particular, administrators of math-specific instances should allow for users to write posts in a familiar syntax (latex) in a way that other instances (allowing, based on HTML scrubbing preferences) can consume. MathML is nice for this, because it renders natively in firefox, safari and new versions of chrome. Old version of chrome can use polyfills, some requiring absolutely no javascript (such as [mathml.css](https://github.com/fred-wang/mathml.css)).

**Comment by aslakr** [comment]
There is also [ronkok/Temml](https://github.com/ronkok/Temml "TeX-to-MathML conversion library in JavaScript") / <https://temml.org>, a KaTeX fork which focus on generating MathML

**Comment by 4e554c4c** [comment]
Closing in favor of #2410
