### ISSUE TITLE
The "latest" Docker image is severely behind

### ISSUE THREAD

**Issue by c-x-berger** [glitch-soc/mastodon#1938]
### Steps to reproduce the problem

1. Look at `ghcr.io/glitch-soc/mastodon:latest`
2. See that the tag is 5 months old
3. :(

### Expected behaviour

tag should probably be more recent?

### Actual behaviour

old

### Detailed description

I was wanting to update my instance (running in a k8s cluster, thus using the docker images) to the latest 4.x release. I thought that pulling the `latest` tag would bring me up to date, but apparently, it hasn't moved for several months?

It looks like upstream Mastodon has taken to [publishing on Docker Hub](https://hub.docker.com/r/tootsuite/mastodon), with up-to-date images tagged for `latest`, `edge`, and specific versions. Not so for glitch (even in GitHub's container registry).

### Specifications

Not sure what the last commit that should've been tagged `latest` is. The last tagged commit was five months ago.

I'm now on the `edge` image from 22 hours ago (`sha256:441fed0daca4afc1a05916c003bf5963e16be897b21e68c893f08a44878c3c5b`), which seems to be working correctly.

**Comment by ClearlyClaire** [comment]
Oh, that probably has to do with us not having actual releases unlike upstream. I am not completely sure how that should be changed, but the `latest` tag existing and being several months old sure isn't good.

**Comment by ineffyble** [comment]
I'll have a look
