### ISSUE TITLE
Propose Markdown support to upstream?

### ISSUE THREAD

**Issue by Andre601** [glitch-soc/mastodon#1946]
### Pitch

Feel like glitch-soc should PR a possible markdown support to Mastodon.

### Motivation

Since glitch-soc already provides markdown support, could it probably be relatively simple to propose changes to the upstream Mastodon project, to include markdown support. This would also have the benefit that both have similar/the same rendering which avoids incompatible designs in the end.

Of course, this is just me guessing this stuff, but giving a push to Mastodon could help getting things started to hopefully have native markdown support in Mastodon itself in the forseeable future.

**Comment by ClearlyClaire** [comment]
Proposed already, rejected already.

https://github.com/mastodon/mastodon/pull/10629

**Comment by Andre601** [comment]
> Proposed already, rejected already.
> 
> [mastodon#10629](https://github.com/mastodon/mastodon/pull/10629)

This was made over 3 years ago... Changes happen

**Comment by ClearlyClaire** [comment]
If you want to convince Eugen, be my guest, but I'm not putting any effort trying to upstream this before he expresses any desire for such a feature, sorry.
