### ISSUE TITLE
/oauth/authorize broken with CSP error on latest HEAD

### ISSUE THREAD

**Issue by rtucker** [glitch-soc/mastodon#1952]
### Steps to reproduce the problem

1. pinafore.social -> log in -> attempt to connect to instance running latest HEAD (381137c94e6cf341117adddc673cfac82760c710)
2. get sent to https://vulpine.club/oauth/authorize?[redacted]
3. click "Authorize"

### Expected behaviour

return to Pinafore with authorization

### Actual behaviour

nothing visible

### Detailed description

Browser console gives:

```
Refused to send form data to 'https://vulpine.club/oauth/authorize' because it violates the following Content Security Policy directive: "form-action 'self'".
```

### Specifications

glitch-soc between eb675af0fb0d73b697e066100c4faf066c0baff7 and 23ea0e75080e427e5ec6be08f7fa75fc8508cd94
Chrome 107

This is probably an upstream issue, but it's not currently reproducible on mastodon.social.

**Comment by ClearlyClaire** [comment]
Yes, this issue is shared with upstream. I'll see what we can do, thanks for reporting it!

**Comment by ClearlyClaire** [comment]
Should be fixed by latest merge!
