### ISSUE TITLE
Following hashtags doesn't work

### ISSUE THREAD

**Issue by sk22** [glitch-soc/mastodon#1958]
### Steps to reproduce the problem

1. Click the “Follow” button in an hashtag timeline
2. The follow button will change state
3. When taking a look at the dev tools, the API returned `{ following: false }` for `POST /tags/:name/follow`
4. Once reloading the page, the follow button reverts to the “not following” state again

### Expected behaviour

I should now follow #Caturday and the API should've returned { following: true }

### Actual behaviour

I'm not following that hashtag (at least according to the API)

### Detailed description

The issue didn't happen on my testing account on mastodon.social, but maybe that's because they don't run on the latest Mastodon commit? Anyway, I didn't see this happen on a vanilla server, but it could be related to this commit: https://github.com/mastodon/mastodon/commit/7fdeed5fbca1b6b761029870f02a3f812288f0aa

### Specifications

[Catstodon](https://github.com/CatCatNya/catstodon) v4.0.2+cat+1.0.2 (latest glitch-soc)
as well as glitch-soc v4.0.2+glitch

**Comment by thedeadparrot** [comment]
I am also seeing this on my glitch-soc instance. There seems to be one follow in the database. No errors returned when trying to make a new one, but no new entries added to the database. I am on version v4.0.2+glitch_1119_e0e7a09.

**Comment by ClearlyClaire** [comment]
I can reproduce this, this is definitely an upstream issue, and I'll be investigating it! Thanks for the report!

**Comment by sk22** [comment]
thank you!!

**Comment by sk22** [comment]
seems to be working again!
