### ISSUE TITLE
Custom emoji inconsistently return with missing directories in S3 url.

### ISSUE THREAD

**Issue by catgoat** [glitch-soc/mastodon#1962]
### Steps to reproduce the problem

1. Upgraded to 4.x glitch/latest commit
2. Post with custom emoji
3. View post

...

### Expected behaviour

Emoji displays

### Actual behaviour

Shortcode displays

### Detailed description

Some custom emoji show the full url, but some custom emoji omit the subdirectories and just have // where they would otherwise be in url. This happens to local and remote emoji. This happens inside apps like tusky/metatext and in the mastodon UI on firefox and chrome on mac os. (may be on others too but these I know for sure).

The web inspector shows this:

![image](https://user-images.githubusercontent.com/42517495/202954822-3c3f8013-2a38-4c46-921f-252fa67acc6b.png)

We are using digital ocean spaces & their CDN. Emoji work everywhere else -- including the picker and admin emoji viewer.

### Specifications

Mastodon 4.x/Edge/Glitch-soc custom built docker image
Docker-Compose
DigitalOcean Spaces

**Comment by catgoat** [comment]
actually I think I see errors related to this, so now I'm unsure if maybe I did something wrong when upgrading?

`ActionController::UrlGenerationError (No route matches {:action=>"show", :controller=>"emojis", :id=>#<CustomEmoji id: 65669, shortcode: "ameowbongo", domain: nil, image_file_name: "a3769304aa24069c.png", image_content_type: "image/png", image_file_size: 6418, image_updated_at: "2020-11-01 13:31:32.655565000 +0000", created_at: "2020-11-01 13:31:32.710384000 +0000", updated_at: "2020-11-01 13:31:32.710384000 +0000", disabled: false, uri: nil, image_remote_url: nil, visible_in_picker: true, category_id: nil, image_storage_schema_version: 1>}, possible unmatched constraints: [:id]
web_1                | Did you mean?  emoji_path
web_1                |                new_admin_custom_emoji_url
web_1                |                new_admin_custom_emoji_path
web_1                |                batch_admin_custom_emojis_url):
web_1                | [90b13da3-6e9d-475f-bd9f-914b92f1e918]   
web_1                | [90b13da3-6e9d-475f-bd9f-914b92f1e918] app/lib/activitypub/tag_manager.rb:43:in `uri_for'
web_1                | [90b13da3-6e9d-475f-bd9f-914b92f1e918] app/serializers/activitypub/emoji_serializer.rb:13:in `id'
web_1                | [90b13da3-6e9d-475f-bd9f-914b92f1e918] app/lib/activitypub/serializer.rb:36:in `serializable_hash'
web_1                | [90b13da3-6e9d-475f-bd9f-914b92f1e918] app/lib/activitypub/serializer.rb:36:in `serializable_hash'
web_1                | [90b13da3-6e9d-475f-bd9f-914b92f1e918] app/lib/activitypub/adapter.rb:19:in `serializable_hash'
web_1                | [90b13da3-6e9d-475f-bd9f-914b92f1e918] app/controllers/concerns/cache_concern.rb:22:in `render_with_cache'
web_1                | [90b13da3-6e9d-475f-bd9f-914b92f1e918] app/controllers/accounts_controller.rb:34:in `block (2 levels) in show'
web_1                | [90b13da3-6e9d-475f-bd9f-914b92f1e918] app/controllers/accounts_controller.rb:17:in `show'
web_1                | [90b13da3-6e9d-475f-bd9f-914b92f1e918] lib/mastodon/rack_middleware.rb:9:in `call'
web_1                | [ff19c845-eac7-48cf-b190-23a1bf9747f2] method=GET path=/users/REDACTED/statuses/REDACTED format=json controller=StatusesController action=show status=200 duration=338.25 view=0.47 db=98.17 key=https://toot.cafe/actor#main-key
web_1                | [1cceae54-10e6-487d-88f3-b76754c3efaa] method=GET path=/users/REDACTED format=json controller=AccountsController action=show status=500 error='ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"emojis", :id=>#<CustomEmoji id: 65669, shortcode: "ameowbongo", domain: nil, image_file_name: "a3769304aa24069c.png", image_content_type: "image/png", image_file_size: 6418, image_updated_at: "2020-11-01 13:31:32.655565000 +0000", created_at: "2020-11-01 13:31:32.710384000 +0000", updated_at: "2020-11-01 13:31:32.710384000 +0000", disabled: false, uri: nil, image_remote_url: nil, visible_in_picker: true, category_id: nil, image_storage_schema_version: 1>}, possible unmatched constraints: [:id]`

**Comment by catgoat** [comment]
Today random emoji show up but some don't. It's very strange. Like it inconsistently can't figure out what directories the emoji live in?

**Comment by prplecake** [comment]
My upgrade to 4.0 left my custom emojis intact. Were any changes to media storage part of your upgrade to 4.0?

**Comment by catgoat** [comment]
No changes other than to rebuild the docker images and run the pre-and-post db migrations. We do have theme customization and language customization. I did go from 3.4 to 4.0, so I skipped 3.5. Maybe I missed a migration step or something?

The inconsistency is what is most confusing to me, many of the emojis have reappeared even though I didn't do anything. It could be a peculiarity of my setup maybe? I have DO spaces and their CDN configured.

**Comment by prplecake** [comment]
> Maybe I missed a migration step or something?

I *think* if this is the case, Mastodon would complain about it. Could grep the logs for "migration" and see what comes up. 

> It could be a peculiarity of my setup maybe? I have DO spaces and their CDN configured.

Unlikely at this point, I think. I have a nearly identical setup except instead of DO services they're AWS.

Though I run from source, perhaps this issue is specific to the container.

**Comment by ClearlyClaire** [comment]
I'm not sure what is happening, but I would do `RAILS_ENV=production bin/tootctl cache clear`, that was one of the upgrade instructions for v3.5.

**Comment by catgoat** [comment]
I did try cache clear at one point, I'll give it another go -- I do see a couple of diffs between glitch-social main and meemu's release branch for those two files, so I'll try and fix the differences, since really the only changes we've made are to themes and localization 🤔 Thank you

**Comment by catgoat** [comment]
So some combo of running cache clear and making sure I had the latest commits worked! Still not sure what was going on, but thank you for the help :)
