### ISSUE TITLE
Dockerfile doesn't include ps but docker-compose.yml expects it for sidekiq health check

### ISSUE THREAD

**Issue by johnsonm** [glitch-soc/mastodon#1964]
### Steps to reproduce the problem

When building e0e7a09cf including 1b5ed3208, the ps command is not included in the image, but docker-compose.yml still has a health check that requires it:

```yaml
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
```

This means that sidekiq is marked unhealthy while continuing to serve successfully.

### Expected behaviour

The sidekiq container should be able to report healthy status

### Actual behaviour

missing procps prevents reporting healthy status

### Specifications

e0e7a09cf (which includes 1b5ed3208)

**Comment by johnsonm** [comment]
This was my simple workaround:

```diff
diff --git a/Dockerfile b/Dockerfile
index 081981d46..b76ca4c25 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -56,6 +56,7 @@ RUN apt-get update && \
     useradd -u "$UID" -g "${GID}" -m -d /opt/mastodon mastodon && \
     apt-get -y --no-install-recommends install whois \
         wget \
+        procps \
         libssl1.1 \
         libpq5 \
         imagemagick \
```

**Comment by ineffyble** [comment]
Note this has been put upstream https://github.com/mastodon/mastodon/pull/21028 - if that one is merged, we can close this one and sync the change from there
