### ISSUE TITLE
Mobile web UI: Privacy popup does not appear when tapping the privacy button on the Boost Confirmation dialog

### ISSUE THREAD

**Issue by neatchee** [glitch-soc/mastodon#1965]
### Steps to reproduce the problem

1. Using a mobile device, go to your instance URL
2. Go to Preferences => Appearance
3. Enable the "Show confirmation dialog before boosting" option
4. Go to any timeline
5. Tap the boost icon
6. In the popup confirmation screen, tap the globe (post privacy) button

### Expected behaviour

Privacy dropdown appears, allowing the user to change the privacy of the Boost

### Actual behaviour

The privacy button changes as if it's selected, but no dropdown appears

### Detailed description

When the "Show confirmation dialog before boosting" option is enabled, the mobile UI does not allow changing the privacy of the boost, because the dropdown doesn't appear after tapping the privacy button in confirmation dialog.

NOTE: Issue does NOT repro on mainline mastodon; this is a glitch-specific issue impacting touch interface behavior

### Specifications

Mastodon: 4.0.2+glitch
Ruby: 3.0.4p208
PostgreSQL: 15.1
Redis: 6.0.16

Browser: 
ALL mobile browser with touch interface
Tested on Android and iPhone; Safari and Chrome

**Comment by ClearlyClaire** [comment]
I can confirm the issue, and will try to address it soon! Thank you for your report.
