### ISSUE TITLE
Best commit to upgrade to the be on the latest of version 3 

### ISSUE THREAD

**Issue by MxFraud** [glitch-soc/mastodon#1969]
### Pitch

We haven't updated in a while, we are still on 3.4.6.
We would like to get up to the latest of version 3, but I'm unsure what commit to pick.

After looking at the git history, I'm guessing the answer it is between these two below:
* Version 3.5.3 cut https://github.com/glitch-soc/mastodon/commit/fbcbf7898f000d9d1a21d52e8a8d3ed4602aa7db
* Partent to the version 4.0.0RC1 cut https://github.com/glitch-soc/mastodon/commit/5f733ad83aebbf52361c97059ac95b13d9a7f897

I appreciate you do not cut release here, hence I looked at finding the answer myself
Yet I could very much benefit from a little guidance to find some point in time stable enough to use.
  
Thank you in advance for your help

### Motivation

Beside us, it might help some of the people using glitch that did upgrade as of late, but that cannot use version 4 yet for various reason

**Comment by ClearlyClaire** [comment]
Hi, releases after 3.5.3 are backport releases, and glitch-soc does not have any of that, so there's no such thing as “the latest of version 3” for glitch-soc.

I know that Mastodon 4.0 brings controversial changes to the user interface, but I think the easiest way to keep up with bug fixes and security fixes on glitch-soc is to track the `main` branch.

To get to something that is similar to Mastodon v3.5.5, your best bet is probably:
- check out 3f10136a41b841897f7a69fb7b2c4d13abf4de53
- cherry-pick the commits from: https://github.com/ClearlyClaire/mastodon/commit/40b66312a8bea89c0c98d1fa653827364ecf9836 https://github.com/ClearlyClaire/mastodon/commit/c6880d5c37755d544e7509cd6d8f7864419924b7 https://github.com/ClearlyClaire/mastodon/commit/6972c4b89fbeb632ea0efd61a3612b2e8a80083e https://github.com/ClearlyClaire/mastodon/commit/8f74f62d86a002bb441ff445fa5c4341c8fe6c05 https://github.com/ClearlyClaire/mastodon/commit/a2306827faea4a975210df66a08f52506474c1b1 https://github.com/ClearlyClaire/mastodon/commit/114b3ac3fab72bcea0d65539e3bc7f8985c2409d https://github.com/mastodon/mastodon/commit/2db06e1d089404844b632b3a2164c4bd3af24424 https://github.com/mastodon/mastodon/commit/b22e1476ca667e1ab83ab26a93203c3f253540af

**Comment by MxFraud** [comment]
Will do.
Thank you very much
