### ISSUE TITLE
Glitch flavour skins missing profile menu button

### ISSUE THREAD

**Issue by ThaMunsta** [glitch-soc/mastodon#1977]
### Steps to reproduce the problem

1. Login
2. Look above the post compose box to the right of the username
3. See below:
![image](https://user-images.githubusercontent.com/3221579/204363447-ae1b5d52-7419-4e34-a05b-5a0c3a606502.png)

### Expected behaviour

Display the menu that is available in default skins

### Actual behaviour

Menu button is missing in Glitch flavour skins

### Detailed description

The following menu button is available in default skins:
![image](https://user-images.githubusercontent.com/3221579/204362573-4dac98f7-a45a-48af-b31d-ec36a8353bfc.png)
This may be intentional, but it seems the menu could be a great place to put the App Settings button, rather than on the right side, above Trends

### Specifications

Mastodon | 4.0.2+glitch_1123_43dbc62
Ruby | 3.0.4p208
PostgreSQL | 14.5
Redis | 7.0.5
Chrome | 107.0.5304.107

**Comment by ClearlyClaire** [comment]
This was initially intentional, but that choice was made before the introduction of the single-column view. I'll need to revisit that because some features are not accessible in single-column mode because of this.

**Comment by ThaMunsta** [comment]
Thanks! I noticed after posting this the DeepL auto translate feature is also missing but you're possibly already aware :)
