### ISSUE TITLE
Leave the possibility to delete old toots after moving an account

### ISSUE THREAD

**Issue by juliemoynat** [glitch-soc/mastodon#1992]
### Pitch

I've moved my account and I don't want to delete the old account for now. The old account still hosts my old toots and I would like to delete some of them (not modify them, just delete). It's not possible today and I don't know why. Moreover, in the warnings before moving an account, there is no information telling that it happens like this.

So… would it be possible to leave the possibility to delete old toots after moving an account?

### Motivation

This would allow you to comply with certain laws and principles (GDPR, right to be forgotten...) without completely deleting an old account in order to just remove a few toots that the person who own the account no longer want to see.

**Comment by ClearlyClaire** [comment]
Are you sure the account you have moved from is using glitch-soc? Glitch-soc should still let you use your account, including deleting posts.

**Comment by juliemoynat** [comment]
Aaah sorry, I've clicked on a bad link! I close this ticket and move it to Mastodon.
So sorry!
