### ISSUE TITLE
No default styling on links (that are not UI elements) in admin panel

### ISSUE THREAD

**Issue by AtelierSnek** [glitch-soc/mastodon#1998]
### Steps to reproduce the problem

1. In the admin panel, issue a warning to a user that contains a link.
2. Open the warning and note that it is in the link-blue.
 ~~This can be replicated with links in mod notes and reports too.~~ This is not an issue with mod notes and reports, as they do not automatically hyperlink.
...

### Expected behaviour

Link styling should be consistent with the rest of the theme.

### Actual behaviour

Default link-blue is used, which is incredibly hard to read on the dark glitch theme

### Detailed description

This seems to be due to the lack of a default `a` style in the `.admin_wrapper` element of `app/javascript/flavours/glitch/styles/admin.scss`.

### Specifications

4.0.1+glitch
Ruby 3.0.4p208
NodeJS v18.12.0

Vivaldi 5.6.2867.36

**Comment by Plastikmensch** [comment]
I can reproduce this with warnings, but not with mod notes and reports as those don't render links.

**Comment by Plastikmensch** [comment]
Can you close this, @AtelierSnek? Fix has been implemented in #2007
