### ISSUE TITLE
Display filtering reason without clicking through

### ISSUE THREAD

**Issue by j-james** [glitch-soc/mastodon#2020]
### Pitch

Upstream re-implemented filters in a similar style to glitch earlier this year: https://github.com/mastodon/mastodon/pull/18058

Their implementation has the benefit of showing the filter that caught a post inline with the "Filtered" string, i.e., you don't need to click through to "show why" and then "Matching filters" to know why it was filtered. I think glitch should copy it - knowing what filter caught a post immediately is helpful and makes it easier to decide to view it or not.

### Motivation

(see above)

**Comment by Plastikmensch** [comment]
I'm confused, this it how it shows by default:
![Screenshot_2022-12-19_09-19-39](https://user-images.githubusercontent.com/29483052/208379568-12a1ae8e-7ac1-4cf3-8a52-dda670296345.png)

**Comment by ClearlyClaire** [comment]
Yeah, we're using the same design as upstream now

**Comment by j-james** [comment]
whoops! i didn't notice my instance was on still on 3.5.5, sorry
