### ISSUE TITLE
Translation management

### ISSUE THREAD

**Issue by ClearlyClaire** [glitch-soc/mastodon#2026]
### Pitch

Figure out how to adapt the current translation tooling to Mastodon

### Motivation

Make translations more robust and easier to maintain, having stuff like Crowdin for glitch-soc-specific strings and so on

**Comment by ClearlyClaire** [comment]
#2027 should address the Rails part, and #2028 the JS part. They need more review and testing, though.

I am also in the process of setting up Crowdin for glitch-soc.

**Comment by Plastikmensch** [comment]
The Rails part is of course still full of "missing translation:" because there aren't many available, but for those that are it works. (it's probably a good idea to initialise these, so even when translations are missing, no errors are visible)
The JS part also loads strings correctly.
I only did a quick test though

**Comment by ClearlyClaire** [comment]
> (it's probably a good idea to initialise these, so even when translations are missing, no errors are visible)

It should fall back to `en` afaik, though, right?

**Comment by Plastikmensch** [comment]
> > (it's probably a good idea to initialise these, so even when translations are missing, no errors are visible)
> 
> It should fall back to `en` afaik, though, right?

It does not

**Comment by ClearlyClaire** [comment]
Do you have an example of a translation string that is missing this way?

**Comment by Plastikmensch** [comment]
> Do you have an example of a translation string that is missing this way?

Any of the glitch settings.
Some have the setting name as title, other only show "Title" "Desc".
glitch label shows "missing translation:"
It's especially bad in the server settings.

**Comment by Plastikmensch** [comment]
Wait, I might have messed up. sec

**Comment by ClearlyClaire** [comment]
I can't reproduce this behavior, with or without the changes.

![image](https://user-images.githubusercontent.com/384364/208950005-b654b0d5-4ef1-4b2d-bb8d-01317e5ba849.png)

**Comment by Plastikmensch** [comment]
Okay, I have no idea what's happening here.
I pulled both PRs into a test branch and this is how it looks for me, if using fr:
![Screenshot_2022-12-21_17-27-43](https://user-images.githubusercontent.com/29483052/208955265-02931171-58c1-42e0-9f5e-1a2ffaef6965.png)

**Comment by ClearlyClaire** [comment]
Do you have any local changes?

**Comment by Plastikmensch** [comment]
> Do you have any local changes?

No, this is based on glitch-soc without any local changes.
The only thing I can imagine interfering is that I have to use the same database for glitch-soc and my custom fork, but I have no idea how that could cause this.
I'll mess around a bit.

**Comment by ClearlyClaire** [comment]
Are you running in a dev or production environment?

**Comment by Plastikmensch** [comment]
> Are you running in a dev or production environment?

dev environment

**Comment by ClearlyClaire** [comment]
This may be a dev VS prod thing then

**Comment by prplecake** [comment]
> This may be a dev VS prod thing then

I can confirm this is the case.

**Comment by Plastikmensch** [comment]
> This may be a dev VS prod thing then

\*long and deep groan turning into angry noises\*
You're right, it's dev vs prod
If I change the language to an unsupported one in prod, it actually does fall back to en, even without these changes.

**Comment by prplecake** [comment]
https://github.com/glitch-soc/mastodon/blob/2f2ef1d4fedd74fb9659ec3ab4f941fd959a1166/config/environments/production.rb#L70

**Comment by Plastikmensch** [comment]
> https://github.com/glitch-soc/mastodon/blob/2f2ef1d4fedd74fb9659ec3ab4f941fd959a1166/config/environments/production.rb#L70

Adding this to `development.rb` made it work.
Sorry for wasting time with this.
I expected a dev env to be basically the same as prod, just more verbose.

**Comment by ClearlyClaire** [comment]
The changes have been made and the Crowdin is live!
