### ISSUE TITLE
Translate not working

### ISSUE THREAD

**Issue by dogrileycom** [glitch-soc/mastodon#2057]
### Steps to reproduce the problem

1. Establish DeepL account
2. Configure .env.production with DEEPL_API_KEY=[key] & DEEPL_PLAN=free
3. Test from command line using CURL - Success
4. Restart mastodon-web
5. No posts in properly marked language get a translate button
...

### Expected behaviour

Each Post should have a translate button if the language is different that the setting of the server

### Actual behaviour

No translate button/link in the post

### Detailed description

Following the basics to enable translation does not produce translation option in posts.

Unsure from reading the features/requests if this is included in the glitch-soc fork at this time.

### Specifications

4.0.2+glitch
Affects all clients

**Comment by ClearlyClaire** [comment]
It should be working, although the feature has been merged in the glitch flavor only fairly recently. Also, only few clients currently support it.

**Comment by dogrileycom** [comment]
Where or what should I look for in the log to indicate when it gets called?  I don’t see anything in journalctl that ‘looks like it’

**Comment by ClearlyClaire** [comment]
Nothing “gets called” before you click on the translate button that you're reporting not showing up. You could check if it shows up in the vanilla flavor, which had the feature for longer.

My guess is that you are either not up-to-date or did not rebuild the assets after the change.

**Comment by dogrileycom** [comment]
So a user mentioned that for him on a German post this morning it worked properly.  I have asked for some screen shots.  As I understand it the poster has to ID their language in the post (it will have a FR | DE) my server needs to have it’s default language set to something different and those two things cause the link to appear?  Is there another condition that needs to be met?

**Comment by ClearlyClaire** [comment]
Yes, the requirements are:
- the post's language must be set and different from your interface language
- the post must not be private

**Comment by dogrileycom** [comment]
This is working in the Mastodon iPad client as expected. This should be closed I guess. The web client does not work, unsure if that is expected. But I was just successful with DeepL in 1.4.9 iOS.

**Comment by ClearlyClaire** [comment]
If the web client does not work, then that is a bug, or an issue with your deployment. As I said earlier, the feature was only implemented fairly recently in the glitch flavor of the web client (about a month ago) while it's been in the vanilla flavor for longer (for about 3 months)
