### ISSUE TITLE
Role setting "Display role as badge on user profiles" does not work

### ISSUE THREAD

**Issue by jippi** [glitch-soc/mastodon#2073]
### Steps to reproduce the problem

1. Add a new role and check `Display role as badge on user profiles`
2. Add a user to the role
3. Go to user profile
4. No badge found for the role

Both in Glitch and non-Glitch flavour - and  with and without `advanced UI`

### Expected behaviour

Badge is shown as checkbox indices

### Actual behaviour

Not being showed

### Detailed description

I can't spot the field in the API response, and it doesn't show on my profile 🤔 

### Specifications

Glitch 4.0.2 `ad17e1944aa4c01c5637199b464c9d78b7e54af2`

**Comment by Plastikmensch** [comment]
This is an upstream issue. The redesign removed (or rather never implemented) role badges.
There already is a PR upstream fixing this, but it hasn't been merged yet.
