### ISSUE TITLE
Follow Hashtags only accepts 1 entry

### ISSUE THREAD

**Issue by dogrileycom** [glitch-soc/mastodon#2078]
### Steps to reproduce the problem

1. Using Web client search a hashtag and click on it
2. Choose the follow + in the upper right
3. follow + changes to follow x
4. reload page follow + returns
5. Go to your single chosen tag unfollow turns x to +
6. You can now follow one other hashtag
...

### Expected behaviour

I should be able to have many hashtags that I follow

### Actual behaviour

I can only follow 1 hashtag at a time

### Detailed description

In addition to the steps above I checked via the API and the entry can be empty [] or have an entry.
I have checked the API status after clicking the + and it changing in the UI to x list is still the initial 1 hashtag

With nothing selected, /api/v1/followed_tags = []

When I add #movie as a tag
journalctl says:
method=POST path=/api/v1/tags/movie/follow format=html controller=Api::V1::TagsController action=follow status=200 duration=40.69 view=11.34 db=8.57

method=POST path=/api/v1/tags/film/follow format=html controller=Api::V1::TagsController action=follow status=200 duration=30.29 view=17.85 db=2.84

The API says:
[
    {
        "name": "movie",
        "url": "https://mastaudon.org/tags/movie",
        "history": [
            {
                "day": "1673395200",
                "accounts": "1",
                "uses": "9"
            },
            {
                "day": "1673308800",
                "accounts": "0",
                "uses": "0"
            },
            {
                "day": "1673222400",
                "accounts": "0",
                "uses": "0"
            },
            {
                "day": "1673136000",
                "accounts": "2",
                "uses": "2"
            },
            {
                "day": "1673049600",
                "accounts": "2",
                "uses": "2"
            },
            {
                "day": "1672963200",
                "accounts": "0",
                "uses": "0"
            },
            {
                "day": "1672876800",
                "accounts": "2",
                "uses": "2"
            }
        ],
        "following": true
    }
]

When I try and add #film as a hashtag I get:
journalctl
node: 
verb Subscribe timeline:hashtag:film

bundle: 
method=GET path=/api/v1/tags/film format=html controller=Api::V1::TagsController action=show status=200 duration=22.45 view=8.68 db=4.50
method=GET path=/api/v1/timelines/tag/film format=html controller=Api::V1::Timelines::TagController action=show status=200 duration=994.97 view=558.47 db=13.86
method=POST path=/api/v1/tags/film/follow format=html controller=Api::V1::TagsController action=follow status=200 duration=30.29 view=17.85 db=2.84

When I look via API at followed_tags I see the same single entry

### Specifications

Mastodon | 4.0.2+glitch
-- | --
Ruby | 3.0.4p208
PostgreSQL | 15.0
Redis | 5.0.7

**Comment by dogrileycom** [comment]
Same issue with iOS client, click the follow button and it changes briefly to unfollow and then back to follow.

**Comment by Plastikmensch** [comment]
Are you using current main?
This should've been fixed with 51a33ce77a32b85eaff37670c40a497aaef13e18

**Comment by dogrileycom** [comment]
Yes.Upgraded from vanilla mastodon 3.5.4 to glitch 4.0.2 directly, using recipe.This behavior was only reported over holidaysSent from my iPadOn Jan 11, 2023, at 1:39 AM, Plastikmensch ***@***.***> wrote:﻿
Are you using current main?
This should've been fixed with 51a33ce

**Comment by dogrileycom** [comment]
Looking at app/controllers/api/v1/tags_controller.rb my file date is 11/20 and the fix is 11/21.  Looking into the file the commit is not there either.

Should I just re-do the recipe to pull the latest version?
How could I have 4.0.2 as latest if there are updates to it?

I am new here so apologies for dumb questions. :)

Should I regularly be pulling for updates or waiting for releases?

**Comment by Plastikmensch** [comment]
> Looking at app/controllers/api/v1/tags_controller.rb my file date is 11/20 and the fix is 11/21. Looking into the file the commit is not there either.

Ah, problem found.

> Should I just re-do the recipe to pull the latest version? How could I have 4.0.2 as latest if there are updates to it?

I have no idea what a "recipe" is in that context. 
But pulling the main branch is recommended.

> Should I regularly be pulling for updates or waiting for releases?

Glitch doesn't have releases, so regularly pulling for updates is required.

**Comment by dogrileycom** [comment]
Thank you.The ‘recipe’ is your steps to upgrade on the site. I will follow them tonight.Introduction | Mastodon Glitch Editionglitch-soc.github.ioSent from my iPadOn Jan 11, 2023, at 7:15 AM, Plastikmensch ***@***.***> wrote:﻿

Looking at app/controllers/api/v1/tags_controller.rb my file date is 11/20 and the fix is 11/21. Looking into the file the commit is not there either.

Ah, problem found.

Should I just re-do the recipe to pull the latest version? How could I have 4.0.2 as latest if there are updates to it?

I have no idea what a "recipe" is in that context.
But pulling the main branch is recommended.

Should I regularly be pulling for updates or waiting for releases?

Glitch doesn't have releases, so regularly pulling for updates is required.

**Comment by dogrileycom** [comment]
This is resolved, thank you for the support
