### ISSUE TITLE
Instance List

### ISSUE THREAD

**Issue by 1bcb** [glitch-soc/mastodon#2079]
### Pitch

I think there should be a list of known instances running Glitch-SOC comparable to this one for [Hometown](https://github.com/hometown-fork/hometown/wiki/Hometown-servers).  

### Motivation

It's harder to find servers running Glitch-SOC than other ActivityPub projects.  Sites like fediverse.observer, the-federation.info, and fedidb.org allow filtering servers by project, but they all count Glitch as just a version of Mastodon.

**Comment by Plastikmensch** [comment]
There actually used to be a list, but it was removed, because it can be understood as endorsement and vetting every instance on such a list is a lot of work.

**Comment by ineffyble** [comment]
You can filter for glitch pretty easily by typing "glitch" into the search at https://instances.social/list/advanced#lang=&allowed=&prohibited=&min-users=&max-users=

**Comment by ClearlyClaire** [comment]
Yeah, as @Plastikmensch said, we used to have a list, but I'm not comfortable with potentially listing awful instances, nor with having to make that kind of editorial decision, and even if I wanted to, it would be a lot of work. Sorry!
