### ISSUE TITLE
Wrong version of ElasticSearch detected?

### ISSUE THREAD

**Issue by tamazonx** [glitch-soc/mastodon#2083]
### Steps to reproduce the problem

Going to my Administrator Dashboard displays a banner, "Incompatible Elasticsearch version: Elasticsearch 6.8.0 is running while 7.x is required".

### Expected behaviour

No warning banner should have displayed

### Actual behaviour

Warning banner displayed

### Detailed description

I'm running Elasticsearch 7.17.8, so I don't know why it's detecting 6.8.0 -- is it looking at the minimum wire compatibilty version?

It seems to be working, but I don't understand why the banner is displaying in the first place.

{
  "name" : "indiepocalypse-social",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "h5VzJRmDT6qrd9Q3RuYmpQ",
  "version" : {
    "number" : "7.17.8",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "120eabe1c8a0cb2ae87cffc109a5b65d213e9df1",
    "build_date" : "2022-12-02T17:33:09.727072865Z",
    "build_snapshot" : false,
    "lucene_version" : "8.11.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

### Specifications

Running Mastodon v4.0.2+glitch, updated on 2023-01-15

currently on hash 13227e1dafd308dfe1a3effc3379b766274809b3 of Glitch.

**Comment by Plastikmensch** [comment]
This is an upstream issue.
Upstream recently changed how the ES version is detected, so the warning isn't shown for OpenSearch, but it seems to cause this warning to appear for ES 7.x.
A proposed fix is available upstream, but not merged yet.

**Comment by Plastikmensch** [comment]
#2087 merged the fix.
