### ISSUE TITLE
After installing custom CSS, if clear the field and save it, it is not updated

### ISSUE THREAD

**Issue by Kitanit** [glitch-soc/mastodon#2085]
### Steps to reproduce the problem

1. Install custom CSS
2. Clear the CSS field and save

### Expected behaviour

Setting the default CSS

### Actual behaviour

Installing the latest CSS

### Specifications

v4.0.2+glitch Docker

**Comment by Plastikmensch** [comment]
This might be a caching issue and resolve itself with time.
Does this also happen when reloading the cache (ctrl+f5)?

**Comment by Kitanit** [comment]
> This might be a caching issue and resolve itself with time. Does this also happen when reloading the cache (ctrl+f5)?

updating to the last commit fixed
