### ISSUE TITLE
glitch-soc specific translation error

### ISSUE THREAD

**Issue by ioletsgo** [glitch-soc/mastodon#2098]
### Steps to reproduce the problem

On the User Page on glitch-soc in particular (it isn't an error on regular Mastodon) when the language is set to Portuguese,
there are two labels that translate to "Followers", it should be "Seguindo" (Following) or "Segue" (Follows)
![image](https://user-images.githubusercontent.com/36903453/215010202-dfd1efd3-3cc0-407b-8525-29bc967b8f76.png)

### Expected behaviour

Seguindo or Seque where the Portuguese equivalent for "Following" should be

### Actual behaviour

Two "Seguidores" labels

### Specifications

v4.1.0rc2+glitch

**Comment by Plastikmensch** [comment]
Hi, this looks like a mistranslation in pt-BR.
Translations are managed via [Crowdin](https://crowdin.com/project/glitch-soc).
If you want to, you can change it there (you'll need an account though).

**Comment by ClearlyClaire** [comment]
Yes, this should be handled in Crowdin, especially in https://crowdin.com/translate/glitch-soc/43/en-ptbr?filter=basic&value=0#q=follows

**Comment by ioletsgo** [comment]
So it's kind of an upstream issue. Thanks.
