### ISSUE TITLE
Status / media export

### ISSUE THREAD

**Issue by yipdw** [glitch-soc/mastodon#210]
> As a citizen of the fediverse
> To have a record of my online activity
> I want to be able to export my posted statuses and media

More or less.

This issue has existed for a while now, most recently (to my knowledge) raised by `@SinaCutie@cybre.space` and (probably) first in https://github.com/tootsuite/mastodon/issues/981 / https://github.com/tootsuite/mastodon/issues/177.  However, the linked issues deal with both export and import -- a much trickier problem.  In this issue, we are only concerned with _getting the data out_ and back to its owner. 

A couple of notes:

- These probably need to be background processes.
- Export and import aren't inextricably tied.  Of course, the export format must contain enough information for an import process, but it is possible to provide some value with just export.  The export format can be versioned for the benefit of a future import process (i.e. "only version 4 and higher have enough information to do an import").

**Comment by MightyPork** [comment]
as a bonus, it could export it to a HTML file / viewer, like birdsite does
but if we also export images, it'll be humongous ...

**Comment by yipdw** [comment]
It would be large, but if the goal is to provide someone with their complete history, I don't think there's any other option.

**Comment by beatrix-bitrot** [comment]
mmmmmmmm

what of context?

**Comment by yipdw** [comment]
Context?  I'm not sure I understand; are you referring to conversation contexts?

**Comment by beatrix-bitrot** [comment]
yeah exact

it's good to have your own toots but it's very weird to read through an archive of toots without the threads they were part of

maybe with links back to the original (if it still exists and is online) you could go read the context without including it but still...

this is not to say i think we SHOULD include the context in the archive necessarily, just that i feel a history is not complete without context. it's just an archive of your toots

**Comment by yipdw** [comment]
I think ultimately, yes, having the context in which those toots were made is necessary -- so much of what makes things memorable are the interactions between people.  

That said, exporting tens of thousands of toots for a popular account is one thing; having a popular account that is popular because of dense interactions may very well make the time/space requirements for this sort of thing _much_ higher.   I guess we'll see?

**Comment by yipdw** [comment]
I remember some Web app out there (can't remember what it was called) that provided exports as HTML pages, like @MightyPork said, and the output looked like it ran through the same server-side rendering process as everything else.  (Maybe it just `wget`ted itself? :P)  Anyway, if we did that, we could capture context and media.    It's possible that appropriate markup could even be used as the import source.

**Comment by SinaCutie** [comment]
I think that if we are to capture "context" we should only link to the outside conversation. I don't think it is necessarily the best idea to be archiving other people's toots within your own -- especially without their consent, and doubly so if the other parties have their accounts locked down/protected.

**Comment by yipdw** [comment]
Fair enough.  How about something like an HTML-formatted presentation of one person's toots (much like the public page), but with links to individual conversations (also on those public pages)?

This provides enough context to get to the original thread as seen from the archive requestor's instance (even if the current UI for doing so is a bit awkward) and avoids copying other people's toots or media into an archive meant for someone else.

**Comment by ThibG** [comment]
Isn't this already covered by the archive export feature?

**Comment by ThibG** [comment]
Closing as it is covered by the archive takeout feature. Please reopen if you feel otherwise.
