### ISSUE TITLE
Admin panel borked with latest merge from upstream

### ISSUE THREAD

**Issue by pedroCX486** [glitch-soc/mastodon#2120]
### Steps to reproduce the problem

1. Open settings
2. Select administration
3. See borked screen (on mobile it shows nothing)

### Expected behaviour

It should show the administration panel

### Actual behaviour

The admin panel disappeared or showed up broken

### Detailed description

After the latest merge from upstream the panel seems to have been broken ~~, I couldn’t diagnose yet if it’s a CSS or JS or backend issue~~.

Seems to be an front-end issue: 

`Failed to find a valid digest in the 'integrity' attribute for resource 'https://mstdn.pedrocx486.club/packs/js/flavours/glitch/admin-324f0df1d0d66c9bddca.chunk.js' with computed SHA-256 integrity 'aB3dc6n6FKVqv77eM+bSFf5Pyv2M6tyUR5zKw0E+8K0='. The resource has been blocked.`

### Specifications

MS Edge iOS - Latest
Safari iOS - Latest
MS Edge MacOS - Latest

glitch-soc using the latest commit on main from 2 days ago

**Comment by ClearlyClaire** [comment]
I can't reproduce this. It looks like there's been an assets precompilation issue or a reverse-proxy cache issue.

**Comment by pedromorais-raidiam** [comment]
Eurgh. I'll try to cleanup and recompile later today. As for cache, don't think that's the case as I try to disable all caches internally and only let Cloudflare do the caching, tried disabling it and still had the issue.

I did notice that during build I got an error, but couldn't read it as it scrolled out of buffer too quickly.

**Comment by Teutates** [comment]
I can reproduce this with an assets clobber and re-precompile. During the build on latest commit, issues arise with warnings related to https://github.com/lodash/babel-plugin-lodash/pull/260

**Comment by Plastikmensch** [comment]
> I can reproduce this with an assets clobber and re-precompile. During the build on latest commit, issues arise with warnings related to [lodash/babel-plugin-lodash#260](https://github.com/lodash/babel-plugin-lodash/pull/260)

These warnings can safely be ignored.

**Comment by pedroCX486** [comment]
> > I can reproduce this with an assets clobber and re-precompile. During the build on latest commit, issues arise with warnings related to [lodash/babel-plugin-lodash#260](https://github.com/lodash/babel-plugin-lodash/pull/260)
> 
> These warnings can safely be ignored.

In my case I had what seemed like an actual crash, but docker compose kept compiling like normal.

**Comment by pedroCX486** [comment]
Cleaned build cache, recompiled and problem disappeared. Oh well. 

For anyone else having issues, try the classic destroy and try again: docker system prune --volumes --all (beware this may be destructive if you don't know what you're doing) and recompile again.
