### ISSUE TITLE
Build main

### ISSUE THREAD

**Issue by dogrileycom** [glitch-soc/mastodon#2129]
### Steps to reproduce the problem

1. Attempt upgrade on Ubuntu 20.04
2. Run through the standard steps...
3. get to bundle install && yarn install
4. error: rbenv: version `3.2.1' is not installed (set by /home/mastodon/live/.ruby-version)
rbenv only has stable releases available to 3.1.2 for Ubuntu with rbenv -L

### Expected behaviour

Possibly grabbed it and installed it ?

### Actual behaviour

failed and indicated ruby needs to be upgraded

### Detailed description

The updates to ruby 3.2.1 seem to be required for 4.1.0 using main.  

I initially got stopped at the git pull stage but was able to specify 
git pull glitch-soc main

the upgrade to 3.2.1 on Ubuntu does not seem to be supported.

These are -L choices for rbenv
3.1.2
3.2.0-dev
3.2.0-preview1
3.2.0-preview2

Am I missing something from the requirements? Can it run with the 3.1.2 version?

### Specifications

Mastodon	4.0.2+glitch
Ruby	3.0.4p208
PostgreSQL	15.1
Redis	5.0.7

**Comment by ClearlyClaire** [comment]
It seems like you need to update rbenv itself, try `cd ~/.rbenv/plugins/ruby-build && git pull`

**Comment by dogrileycom** [comment]
That was it.  Got some other weirdness during precompile but it looks fine now.  

I can't thank you enough ClearlyClaire.
