### ISSUE TITLE
Misc. page path is not handled by Mastodon frontend

### ISSUE THREAD

**Issue by JacksonChen666** [glitch-soc/mastodon#2140]
### Steps to reproduce the problem

1. Go to homepage of instance (assuming advanced interface)
2. Click the Misc. button in the "Getting started" column
3. Reload

### Expected behaviour

The application should handle the specific path

### Actual behaviour

The application did not handle the specific path

### Detailed description

`/getting-started-misc` is a 404 but is linked within the advanced user interface.
Clicking the Misc. button/link does work. Things still work until the page is reloaded at that path.

This is what the Misc. link leads to:

<img src="https://user-images.githubusercontent.com/50755746/226174950-b2a22390-85f8-4a4c-b3c5-3933cf213bda.png" title="Mastodon/glitch-soc Advanced user interface, getting started misc. column" width=250>

### Specifications

- Mastodon on f5daa20f2a90098c9d689c5ec9d95ce9887b3a33
- LibreWolf 111.0-2
- macOS 13

**Comment by Plastikmensch** [comment]
Thanks! I noticed that too and wanted to look into it, but forgot
