### ISSUE TITLE
Latest Docker image (9a111a615f87f84c919a9f2197ce3483226b41f9) isn't available

### ISSUE THREAD

**Issue by jippi** [glitch-soc/mastodon#2142]
### Steps to reproduce the problem

`docker pull ghcr.io/glitch-soc/mastodon:9a111a615f87f84c919a9f2197ce3483226b41f9`  yields `Error response from daemon: manifest unknown`

From this pipeline (https://github.com/glitch-soc/mastodon/actions/runs/4456757370/jobs/7827412604)

I don't see any errors, but the tag isn't in the registry for some reason

### Expected behaviour

docker pull succeeding 

### Actual behaviour

docker pull failing

### Specifications

N/A

**Comment by Plastikmensch** [comment]
Oh. This might be because of 0b8b0ef65221e5341cd81b212f0e40722ffd5ef7
The image is still build, but not actually pushed and therefore not available.
