### ISSUE TITLE
Regression from upstream: clicking on a hashtag in a federated post opens the tag on the remote instance

### ISSUE THREAD

**Issue by awebeer256** [glitch-soc/mastodon#2157]
### Steps to reproduce the problem

1. Browse Mastodon on foo.social
2. See a post from [@]alice[@]bar.social, containing the hashtag \#baz
3. Click on the \#baz link

### Expected behaviour

My browser should navigate to foo.social/tags/baz

### Actual behaviour

My browser navigates to bar.social/tags/baz

### Detailed description

I checked on several instances, and as I said in the title, this problem only occurs on the ones running the glitch edition of Mastodon.

### Specifications

Bug appears: 4.1.1+glitch, 4.1.0+glitch, 4.0.2+glitch.
Doesn't appear: 4.1.1, 4.1.0, 4.0.2

Browser: Firefox

**Comment by Plastikmensch** [comment]
I can't reproduce this.
Do you have an add-on which messes with links?
I vaguely remember something like that causing this, but I'm unable to find the specific issue this was mentioned in.

**Comment by awebeer256** [comment]
I created a new browser profile and immediately went to https://infosec.exchange/@jiejie@mastodon.art/110125888322140055. The \#aisafety tag in that post points to https://mastodon.art/tags/aisafety.

**Comment by Plastikmensch** [comment]
> I created a new browser profile and immediately went to https://infosec.exchange/@jiejie@mastodon.art/110125888322140055. The #aisafety tag in that post points to https://mastodon.art/tags/aisafety.

That link unfortunately already opens the toot on .art
However, while the tag in the toot points to another instance, it should still open on the current one when clicked, unless when middle-clicked which should open it on the remote instance.

**Comment by awebeer256** [comment]
…Oops. On my phone now, I just checked and you're right.

I even saw people talking about that as I was checking if anyone had already filed this issue (here it is: https://github.com/mastodon/mastodon/issues/22414#issuecomment-1364154555), and then forgot about it as I was doing my more thorough testing just before posting 🥴.

So, uh, can I convert this issue into a feature request for the ability to change this behaviour in the user settings? I intentionally open links in new tabs all the time, whereas I don't think I'll ever want to look at the remote instance's version of something.

**Comment by Plastikmensch** [comment]
> So, uh, can I convert this issue into a feature request for the ability to change this behaviour in the user settings? I intentionally open links in new tabs all the time, whereas I don't think I'll ever want to look at the remote instance's version of something.

That has been suggested in #2082 though that one focuses more on toots in general

**Comment by awebeer256** [comment]
Okay, I'll close this as a duplicate and move the discussion there.
