### ISSUE TITLE
server broke after attempting to change post character limit

### ISSUE THREAD

**Issue by toreachpoise** [glitch-soc/mastodon#2183]
### Steps to reproduce the problem

1.hi first off i'm a pretty novice server admin and not familiar with ruby that much. i apologize in advance for this probably being caused by a mistake on my part. i started my server a couple months ago and installed glitch-soc. it's been working fine, and then i got a notification that i needed to update the ssl certificate, which i did using nginx. i then decided to change the post character limit while i was in the CLI. 
2.i made a new git branch, changed the character limit in /app/javascript/mastodon/initialstate.js, and then switched back to main
3. upon trying to switch to glitch-soc/main there was an issue because of the change i made, but it also said there were changes to many other files.
4. at this point i simply tried to restart my server and it was down.
5. i went back to CLI and tried to do git checkout on glitch-soc/main again. same problem. i did git checkout -f glitch-soc/main and it worked. i then did a git pull and went through the rest of the install/update instructions in the docs (https://glitch-soc.github.io/docs/). it all appeared to work but the server is still down. i have no idea how to figure out what is wrong.
...

### Expected behaviour

changed post character limit and restarted server

### Actual behaviour

a bunch of git conflicts and then the server crashed

### Specifications

ubuntu 22.04.2
ruby 3.2.2
#2181

**Comment by ClearlyClaire** [comment]
It's difficult to help you without knowing exactly what you did and what is going on. What do you mean by “the server is still down”? Generally, it's good to check logs with `journalctl -u mastodon-web` and `journalctl -u mastodon-sidekiq`.

Also, you don't need to change any source file in glitch-soc to change the characters limit, you only need to set the `MAX_TOOT_CHARS` variable in `.env.production`

**Comment by toreachpoise** [comment]
sorry, it actually was a problem with the ssl certificate. i apologize for wasting your time!

**Comment by SmallPatatas** [comment]
> Also, you don't need to change any source file in glitch-soc to change the characters limit, you only need to set the `MAX_TOOT_CHARS` variable in `.env.production`

AHH thanks, was scouring the docs for the setting!

**Comment by ShadowJonathan** [comment]
Same here, that note isn't documented, so i was looking at where to change that
