### ISSUE TITLE
my profile is not showing up on my instance's local timeline

### ISSUE THREAD

**Issue by Nekothegamer** [glitch-soc/mastodon#2184]
### Steps to reproduce the problem

1. write a toot
2. look at the local timeline, your toot doesn't show, while others can see it

### Expected behaviour

my own toots should appear on the local timeline 

### Actual behaviour

no toots appeared, but if i went to the local timeline on a private tab i could see it and people sent me screenshots of them seeing my toots on the local timeline

### Detailed description

i don't know what's happening, is it there some conflict with a setting or is this glitch-soc default behavior? is this glitch-soc at all and it's just actually a mastodon issue?? please help me this has been bugging me for a lot at this point and I'm tired of seeing this problem

### Specifications

Mastodon v4.1.2+chuckya

Android 11 & Fedora 37
Firefox for Android 112.0

**Comment by Plastikmensch** [comment]
Unfortunately, I can't reproduce this.
And even looking through that forks code I can't find anything obviously wrong.
I'm also not aware of any way to hide your own toots from public timelines aside from changing the privacy, but that would also cause others to not being able to see it.

Do you have enabled language filtering in Preferences > Other?
I see your default toot language is IT
Other than that it's probably best to ask the admin of your instance.

**Comment by Nekothegamer** [comment]
never
