### ISSUE TITLE
Autocomplete username while writing post

### ISSUE THREAD

**Issue by GuillaumeRossolini** [glitch-soc/mastodon#2196]
### Steps to reproduce the problem

1. Get the web app on the Home Screen (iOS here)
2. Log in and start writing a toot
3. Try atting someone by writing "@" followed by their handle

### Expected behaviour

Should see my follows at the top

### Actual behaviour

Got a list of accounts with the handles cut short

### Detailed description

Three issues that I can see:
- screen is not used at its best (display names push the handle off screen, and vertically there is lots of empty space)
- autocomplete doesn't seem to search my follows first
- tapping a suggestion doesn't complete with that handle

For example I'm following one person called Jerry. I'm looking for him and the  second suggestion displays his display name with the start of his handle, but there's only space for "jer". Tapping this one does complete with the correct handle. Was sort of expecting him to appear first.

Example 2. Looking for an account called Corey. Writing the exact handle without the domain, I get 4 suggestions with exactly one character on screen to guess the domain. Unfortunately there's two that start with an a and two with a t. So I tap one with the a but it completes with a different handle altogether (this one starts with a b).

Example 3. I'm looking for a person from my follow list, not a big account and not on my instance but their display name and handle start the same. I only get suggestions of people I don't know.

### Specifications

Don't know. It's the security.exchange instance?

**Comment by GuillaumeRossolini** [comment]
Screenshots for the first post, apologies for the chaos in my writing.

None of these helped. I felt more at ease looking them up in another tab, then copying their handle from there.

The Corey search:
![IMG_3133](https://user-images.githubusercontent.com/8587631/234671049-3ece9a80-8d20-4383-99f3-797ec50e43e7.png)
![IMG_3134](https://user-images.githubusercontent.com/8587631/234671068-054f10ba-606f-4701-9e18-db7dc9308662.png)

The Shirley search:
![IMG_3135](https://user-images.githubusercontent.com/8587631/234671073-43f4d061-43f5-4e7c-8fd0-35a8b46d47cf.png)
![IMG_3136](https://user-images.githubusercontent.com/8587631/234671076-fd1d91a0-14b3-45ab-9d65-61f0da61b4e8.png)

The Jerry search:
![IMG_3137](https://user-images.githubusercontent.com/8587631/234671083-6356f092-17a8-4d44-b83b-48a6a23d0a02.png)

**Comment by Plastikmensch** [comment]
This issue is also present in the advanced UI.
I think a good solution would be to show the handle below the display name.
But I'm pretty sure this is an upstream issue, unfortunately.

**Comment by Plastikmensch** [comment]
People generally don't manually tag accounts and most users use a mobile app, so that there hasn't been an issue upstream yet doesn't surprise me.
But yeah, it's an upstream issue and I have to correct myself: It's not just the advanced UI.
