### ISSUE TITLE
Port account rows design change from upstream

### ISSUE THREAD

**Issue by ClearlyClaire** [glitch-soc/mastodon#2217]
### Pitch

See https://github.com/glitch-soc/mastodon/pull/2152

- ef127c964a60f365129bc97a2cb2fc6d12ba6407
- 46483ae849bc06ee74f4745f4564b213e742c51c
- 5fae2de454806730742b7be7435ae1c4fb97cf3c
- 0ddc89528213859bf4caeefd475a93ed973ab0e0
- 55e7c08a83547424024bac311d5459cb82cf6dae

### Motivation

Reduce divergences from upstream.

**Comment by ClearlyClaire** [comment]
There are a few issues with this, the main one being that glitch-soc allows disabling followers counts, and the follower count is one of the main elements of the new design. What can we do about that?

**Comment by ClearlyClaire** [comment]
Maybe the easiest way around it is to never show the followers count and display the handle instead; this is gonna push the verified link further though

**Comment by Plastikmensch** [comment]
I just added `minimal: true` to `defaultProps` downstream, which basically keeps the current design.
I also show a snippet of the bio in the onboarding instead of the follower count thing to get closer to the old design.
Not sure if that's something you would want to do.

**Comment by ClearlyClaire** [comment]
This and #2200 are more intertwined than I expected… this will be a painful one!

**Comment by Plastikmensch** [comment]
The minimal prop gets added by 46483ae849bc06ee74f4745f4564b213e742c51c btw, which is somehow missing in the list

**Comment by Plastikmensch** [comment]
> This and #2200 are more intertwined than I expected… this will be a painful one!

Btw I know you prefer doing merges and ports yourself, but if you want help, just say what you need.
My capacity is also limited, but I would still like to help, if wanted.
