### ISSUE TITLE
Mastodon PR #24762 causes the webui to break

### ISSUE THREAD

**Issue by Ember-ruby** [glitch-soc/mastodon#2224]
### Steps to reproduce the problem

use a version of glitch which contains [github.com/mastodon/mastodon/pull/24762](https://github.com/mastodon/mastodon/pull/24762/files#diff-5f3fc5e3977d242572aa1d08551f5eb557de0ccaff30370838ee9df5386ea0da), specifically lines 172 and 176, the webui will no longer load

### Expected behaviour

the webui should work as normal

### Actual behaviour

the webui will no longer load, showing the generic error page

### Detailed description

when it was broken, this is what showed in the logs whenever a page was visited (some unneeded info removed)

```
mastodon bundle: method=GET path=/public/local format=html controller=HomeController action=index status=500 error='ActionView::Template::Error: bad component(expected host component): pool.jortage.com/blobfoxcoffee' duration= view= db=
mastodon bundle: ActionView::Template::Error (bad component(expected host component): pool.jortage.com/blobfoxcoffee):
mastodon bundle:      9:       %meta{ name: 'cdn-host', content: cdn_host }/
mastodon bundle:     10:
mastodon bundle:     11:     - if storage_host?
mastodon bundle:     12:       %link{ rel: 'dns-prefetch', href: storage_host }/
mastodon bundle:     13:
mastodon bundle:     14:     %link{ rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }/
mastodon bundle:     15:
mastodon bundle:
mastodon bundle: app/helpers/application_helper.rb:173:in storage_host'
mastodon bundle: app/views/layouts/application.html.haml:12
mastodon bundle: app/controllers/concerns/localized.rb:11:inset_locale'
mastodon bundle: lib/mastodon/rack_middleware.rb:9:in `call'
```

### Specifications

https://github.com/mastodon/mastodon/pull/24762/files#diff-5f3fc5e3977d242572aa1d08551f5eb557de0ccaff30370838ee9df5386ea0da 172, 176

**Comment by ClearlyClaire** [comment]
Hi! As the name suggests, `S3_ALIAS_HOST` and `S3_CLOUDFRONT_HOST` are supposed to be hostnames without a path component.

**Comment by Ember-ruby** [comment]
removing /blobfoxcoffee breaks the media
this *may* be an issue with [jortage](https://jortage.com) as it's a bit different to most media stores

**Comment by ClearlyClaire** [comment]
Ah, you're right, the underlying lib does allow paths in `S3_ALIAS_HOST`. I'll take this upstream.

**Comment by ClearlyClaire** [comment]
For reference, the upstream PR about this issue is https://github.com/mastodon/mastodon/pull/25018

**Comment by ClearlyClaire** [comment]
This should be fixed with the latest merge from upstream changes!
