### ISSUE TITLE
Failed to process new follow request

### ISSUE THREAD

**Issue by Tyketc** [glitch-soc/mastodon#2232]
### Steps to reproduce the problem

1. Set up a Mastodon server using the latest Docker image (`ghcr.io/glitch-soc/mastodon:058898802a377877961ff3bfa7d5209a5e275545`).
2. Attempt to follow a user in the instance.
3. Even though the user has not locked their toots, the follow request will fail. The initiating user will see the request as pending, but it cannot be accepted by the user being followed, with an error message output on the server's error log when attempting to accept it.

Please refer to the detailed description for error logs.

### Expected behaviour

The server can handle follows properly.

### Actual behaviour

User see the follow request as pending even though they doesn't lock their toots, and the request can't be accepted.

### Detailed description

Error log:
```
mastodon-web        | [d86d6305-56c2-4082-933a-b984a868f7f6] method=POST path=/api/v1/follow_requests/110422573782793339/authorize format=html controller=Api::V1::FollowRequestsController action=authorize status=500 error='ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column list_accounts.follow_request_id does not exist
mastodon-web        | LINE 1: ... "follow_request_id" = $1, "follow_id" = $2 WHERE "list_acco...
mastodon-web        |                                                              ^
mastodon-web        | ' duration=24.85 view=0.00 db=10.08
mastodon-web        | [d86d6305-56c2-4082-933a-b984a868f7f6]   
mastodon-web        | [d86d6305-56c2-4082-933a-b984a868f7f6] ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column list_accounts.follow_request_id does not exist
mastodon-web        | LINE 1: ... "follow_request_id" = $1, "follow_id" = $2 WHERE "list_acco...
mastodon-web        |                                                              ^
mastodon-web        | ):
mastodon-web        | [d86d6305-56c2-4082-933a-b984a868f7f6]   
mastodon-web        | [d86d6305-56c2-4082-933a-b984a868f7f6] app/models/follow_request.rb:36:in `authorize!'
mastodon-web        | [d86d6305-56c2-4082-933a-b984a868f7f6] app/services/authorize_follow_service.rb:11:in `call'
mastodon-web        | [d86d6305-56c2-4082-933a-b984a868f7f6] app/controllers/api/v1/follow_requests_controller.rb:15:in `authorize'
mastodon-web        | [d86d6305-56c2-4082-933a-b984a868f7f6] app/controllers/concerns/localized.rb:11:in `set_locale'
mastodon-web        | [d86d6305-56c2-4082-933a-b984a868f7f6] lib/mastodon/rack_middleware.rb:9:in `call'
mastodon-web        | [d86d6305-56c2-4082-933a-b984a868f7f6] lib/public_file_server_middleware.rb:18:in `call'


```

### Specifications

Mastodon 4.1.2+glitch (docker image `058898802a377877961ff3bfa7d5209a5e275545`)

**Comment by ClearlyClaire** [comment]
Have you perhaps forgotten to run database migrations when upgrading? (`bundle exec rails db:migrate`)

**Comment by Tyketc** [comment]
Oh yes. The server now works well after `db:migrate`. Please forgive my foolishness.
