### ISSUE TITLE
Open Registrations Signup Button doesn't work

### ISSUE THREAD

**Issue by prplecake** [glitch-soc/mastodon#2241]
### Steps to reproduce the problem

1. Have an instance with open registrations.
2. Try to use the "Create Account" button
3. Nothing happens

### Expected behaviour

Should be navigated to signup page

### Actual behaviour

Nothing

### Detailed description

It appears that the commit that broke this is: 9e5278ea7bec1f1a225304f8711f3e107eeffdae

`signupUrl` is always `null`, so there's no href on the link.

### Specifications

glitch-soc after 9e5278ea7bec1f1a225304f8711f3e107eeffdae, this is probably also an issue upstream.

**Comment by ClearlyClaire** [comment]
This has been an issue upstream indeed and it's been fixed there. I need to merge upstream changes.
