### ISSUE TITLE
<abbr> title attribute gets stripped when using markdown/html

### ISSUE THREAD

**Issue by sk22** [glitch-soc/mastodon#2248]
### Steps to reproduce the problem

1. post something like `in my <abbr title="in my opinion">imo</abbr> fedi instances should support the abbr tag` with html
2. see that there's no tooltip/title on `imo`
3. check the browser's dev tools and see that the api returned this content:
   ```
   <p>in my <abbr>imo</abbr> fedi instances should support the abbr tag</p>
   ```

### Expected behaviour

given the abbr tag is still there, it should be allowed to keep its title tag

### Actual behaviour

the title tag gets stripped away

### Specifications

Catstodon v4.1.2+glitch+cat+1.2.0

**Comment by mxamber** [comment]
Can confirm from vanilla glitch-soc - the abbr element is retained, its title is not.

**Comment by Plastikmensch** [comment]
> Looks like it's an oversight from merging upstream changes in [7623e18](https://github.com/glitch-soc/mastodon/commit/7623e181247b4d2227b7774143514f6e1ca9253b)

Yeah.
Are you taking care of this or should I open a quick PR?

**Comment by sk22** [comment]
thanks! :)
