### ISSUE TITLE
ArgumentError when navigating to private mentions

### ISSUE THREAD

**Issue by Plastikmensch** [glitch-soc/mastodon#2249]
### Steps to reproduce the problem

1. Unpin private mentions column when pinned (Advanced UI)
2. Use Getting started and click Private mentions
3. See `500 - Internal Server Error` pop up in the left bottom corner

### Expected behaviour

There should be no error

### Actual behaviour

Private mentions load fine, but still throws an error

### Detailed description

Seems to be caused by 2b45fecde1cff0088c3c22095070302baf795a78
Looks like an upstream issue unfortunately.

Log of the error:
```
ArgumentError - unknown keyword: "since_id":
  app/models/account_conversation.rb:46:in `to_a_paginated_by_id'
  app/controllers/api/v1/conversations_controller.rb:48:in `paginated_conversations'
  app/controllers/api/v1/conversations_controller.rb:13:in `index'
  app/controllers/concerns/localized.rb:11:in `set_locale'
  lib/mastodon/rack_middleware.rb:9:in `call'
  lib/public_file_server_middleware.rb:18:in `call'

```

### Specifications

fefdc3244cc53573e835009c17f9bc658386639e

**Comment by ClearlyClaire** [comment]
This should now be fixed!

**Comment by Plastikmensch** [comment]
It is! Thanks!
