### ISSUE TITLE
Webui breaks when CDN enabled

### ISSUE THREAD

**Issue by Tyketc** [glitch-soc/mastodon#2250]
### Steps to reproduce the problem

This bug may relate to [PR#2246](https://github.com/glitch-soc/mastodon/pull/2246)

1. Setup an instance under commit [fefdc32](https://github.com/glitch-soc/mastodon/commit/fefdc3244cc53573e835009c17f9bc658386639e)
2. Setup CDN with `Access-Control-Allow-Origin: *`
3. Restart the instance.
...

### Expected behaviour

The webui loads successfully.

### Actual behaviour

Got a blank screen with following errors in browser console:

### Detailed description

```
Subresource Integrity: The resource 'https://cdn.mastodon.instance/packs/js/locales/glitch/zh-CN-json-d9fbf1fd0d7ee3845963.chunk.js' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced.
s.e @ bootstrap:149
```

```
home.js:10 ChunkLoadError: Loading chunk 650 failed.
(error: https://cdn.mastodon.instance/packs/js/locales/glitch/zh-CN-json-d9fbf1fd0d7ee3845963.chunk.js)
    at s.e (bootstrap:126:18)
    at o (.*\.json$ include: \.json$ preloadOrder: 0 namespace object:393:29)
    at load_locale.ts:27:30
(anonymous) @ home.js:10
```

### Specifications

Mastodon 4.1.2+glitch (commit `fefdc3244cc53573e835009c17f9bc658386639e`)
Chrome 114.0

**Comment by ClearlyClaire** [comment]
I can reproduce the issue, and it's caused by https://github.com/mastodon/mastodon/pull/24906

**Comment by ClearlyClaire** [comment]
This should now be fixed!

**Comment by Tyketc** [comment]
Yes, the front-end now loads successfully. Thanks for the quick fix!
