### ISSUE TITLE
Webpacker can't find locales/vanilla/en-GB-json.js in /home/mastodon/live/public/packs/manifest.json

### ISSUE THREAD

**Issue by nanos** [glitch-soc/mastodon#2255]
### Steps to reproduce the problem

1. Updated glitch-soc with latest changes
2. Ran `bundle install && yarn install`
3. Visit my web frontend

### Expected behaviour

Web frontend loads

### Actual behaviour

Get 500 error

### Detailed description

I'm getting the following error in my logs:

```
method=GET path=/ format=html controller=HomeController action=index status=500 error='ActionView::Template::Error:Eebpacker can't find locales/vanilla/en-GB-json.js in /home/mastodon/live/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
```

### Specifications

My mastodon code is here: https://github.com/nanos/mastodon

**Comment by ClearlyClaire** [comment]
Hi! Have you rebuilt the assets? That is something you should do when updating, along with running database migrations (though database migrations are not your issue there)

`bundle exec rails assets:precompile`

(In some case, webpacker may fail and subsequent runs won't work until you do something like `bundle exec rails assets:clobber`)

**Comment by ClearlyClaire** [comment]
Webpack can be *very* memory-hungry. One way to reduce its memory usage is to apply this patch:
```patch
diff --git a/config/webpack/production.js b/config/webpack/production.js
index 7f1ee4a8f9..b7c65d9a3d 100644
--- a/config/webpack/production.js
+++ b/config/webpack/production.js
@@ -19,6 +19,7 @@ module.exports = merge(sharedConfig, {
   devtool: 'source-map',
   stats: 'normal',
   bail: true,
+  parallelism: 1,
   optimization: {
     minimize: true,
     minimizer: [
```

**Comment by nanos** [comment]
ah, nice one, thanks! That's done the trick, and the interface is back up and running again now.

Thanks for your support!
