### ISSUE TITLE
Admin Block page missing when trying to add or edit a suspend (domain_blocks.803)

### ISSUE THREAD

**Issue by WhiskeyOmega** [glitch-soc/mastodon#2257]
### Steps to reproduce the problem

1.Admin Panel > Federation
2.Add new domain block
3.Add domain and suspend
4.If Domain is already limited and also try to edit to suspend
5. Get info warning of accounts being suspend.
6. Get message saying The Page You are looking for isnt here.

...

### Expected behaviour

Should just suspend and show the page. 

### Actual behaviour

Suspending domains doesnt seem to work. 

### Specifications

 Glitch on Main #2203

**Comment by Plastikmensch** [comment]
Oh, just ran into this too

It is caused by the confirmation screen redirecting to an invalid url when upgrading a block.
Upstream issue, unfortunately.

**Comment by ClearlyClaire** [comment]
I can reproduce the issue, which is indeed shared with upstream. I thought I had tested this case, but I wrote the tests wrong… working on that
