### ISSUE TITLE
Plan to integrate security fixes on 2023-07-06 @ 13:00 GMT

### ISSUE THREAD

**Issue by neatchee** [glitch-soc/mastodon#2267]
### Steps to reproduce the problem

See: https://mastodon.social/@Mastodon/110644992947398414

### Expected behaviour

Unknown

### Actual behaviour

Unknown

### Detailed description

Mastodon upstream is doing a concurrent disclosure and fix release of major security vulnerabilities

These need to be integrated into glitch ASAP

### Specifications

Mastodon 3.5.x and above

**Comment by ClearlyClaire** [comment]
Yes, this is planned
