### ISSUE TITLE
Local Live Feed doesn't "Load More"

### ISSUE THREAD

**Issue by Taullo** [glitch-soc/mastodon#2268]
### Steps to reproduce the problem

1. Open Live Feeds
2. Select Local
3. Scroll to bottom
4. Posts don't load and "Load More" doesn't work
...

### Expected behaviour

It should automatically load more posts and/or "Load More" should load them

### Actual behaviour

Posts don't automatically load. The "Load More" button appears, but clicking it does nothing.

### Detailed description

Tested on both a live site and via Vagrant with the latest Git with the same result. The 'Remote' and 'All' timelines seem to be working fine. Mobile apps also seem to be working fine so it might be an issue with the new Firehose implementation. There's no errors printed in the console and Vagrant shows:

`19:29:14 web.1     | Started GET "/api/v1/timelines/public?local=true&only_media=false&since_id=110651789342172781" for 192.168.42.1 at 2023-07-03 19:29:14 +0000
19:29:14 web.1     | Cache read: blocked_ips
19:29:14 web.1     | Cache generate: blocked_ips
19:29:14 web.1     |    (0.1ms)  SELECT "ip_blocks"."ip" FROM "ip_blocks" WHERE "ip_blocks"."severity" = $1  [["severity", 9999]]
19:29:14 web.1     | Cache write: blocked_ips
19:29:14 web.1     |   Doorkeeper::AccessToken Load (0.1ms)  SELECT "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "BcSvxNy6HFBFGM7s5p8lFPSAeqL3qAFte3gRXMtji5s"], ["LIMIT", 1]]
19:29:14 web.1     | Cache write: rack::attack:5628041:throttle_authenticated_api:1 ({:expires_in=>47})
19:29:14 web.1     | Cache write: rack::attack:5628041:throttle_per_token_api:1 ({:expires_in=>47})
19:29:14 web.1     | Cache write: rack::attack:1876013:throttle_authenticated_paging:1 ({:expires_in=>47})
19:29:14 web.1     | Processing by Api::V1::Timelines::PublicController#show as HTML
19:29:14 web.1     |   Parameters: {"local"=>"true", "only_media"=>"false", "since_id"=>"110651789342172781"}
19:29:14 web.1     |   CACHE Doorkeeper::AccessToken Load (0.0ms)  SELECT "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2  [["token", "BcSvxNy6HFBFGM7s5p8lFPSAeqL3qAFte3gRXMtji5s"], ["LIMIT", 1]]
19:29:14 web.1     |   User Load (0.1ms)  SELECT "users"."id", "users"."email", "users"."created_at", "users"."updated_at", "users"."encrypted_password", "users"."reset_password_token", "users"."reset_password_sent_at", "users"."sign_in_count", "users"."current_sign_in_at", "users"."last_sign_in_at", "users"."admin", "users"."confirmation_token", "users"."confirmed_at", "users"."confirmation_sent_at", "users"."unconfirmed_email", "users"."locale", "users"."encrypted_otp_secret", "users"."encrypted_otp_secret_iv", "users"."encrypted_otp_secret_salt", "users"."consumed_timestep", "users"."otp_required_for_login", "users"."last_emailed_at", "users"."otp_backup_codes", "users"."account_id", "users"."disabled", "users"."moderator", "users"."invite_id", "users"."chosen_languages", "users"."created_by_application_id", "users"."approved", "users"."sign_in_token", "users"."sign_in_token_sent_at", "users"."webauthn_id", "users"."sign_up_ip", "users"."role_id", "users"."settings", "users"."time_zone" FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
19:29:14 web.1     |   SessionActivation Load (0.1ms)  SELECT "session_activations".* FROM "session_activations" WHERE "session_activations"."session_id" = $1 LIMIT $2  [["session_id", "34015463be424a94a79fe40a30cf6de2"], ["LIMIT", 1]]
19:29:14 web.1     |   Account Load (0.1ms)  SELECT "accounts"."id", "accounts"."username", "accounts"."domain", "accounts"."private_key", "accounts"."public_key", "accounts"."created_at", "accounts"."updated_at", "accounts"."note", "accounts"."display_name", "accounts"."uri", "accounts"."url", "accounts"."avatar_file_name", "accounts"."avatar_content_type", "accounts"."avatar_file_size", "accounts"."avatar_updated_at", "accounts"."header_file_name", "accounts"."header_content_type", "accounts"."header_file_size", "accounts"."header_updated_at", "accounts"."avatar_remote_url", "accounts"."locked", "accounts"."header_remote_url", "accounts"."last_webfingered_at", "accounts"."inbox_url", "accounts"."outbox_url", "accounts"."shared_inbox_url", "accounts"."followers_url", "accounts"."protocol", "accounts"."memorial", "accounts"."moved_to_account_id", "accounts"."featured_collection_url", "accounts"."fields", "accounts"."actor_type", "accounts"."discoverable", "accounts"."also_known_as", "accounts"."silenced_at", "accounts"."suspended_at", "accounts"."hide_collections", "accounts"."avatar_storage_schema_version", "accounts"."header_storage_schema_version", "accounts"."devices_url", "accounts"."suspension_origin", "accounts"."sensitized_at", "accounts"."trendable", "accounts"."reviewed_at", "accounts"."requested_review_at" FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 110651780559187701], ["LIMIT", 1]]
19:29:14 web.1     | Cache read: rails_settings_cached/af1af454976854e81428e6a1a4a3f933/timeline_preview
19:29:14 web.1     | Cache generate: rails_settings_cached/af1af454976854e81428e6a1a4a3f933/timeline_preview
19:29:14 web.1     |   Setting Load (0.2ms)  SELECT "settings".* FROM "settings" WHERE (thing_type is NULL and thing_id is NULL) AND "settings"."var" = $1 ORDER BY "settings"."id" ASC LIMIT $2  [["var", "timeline_preview"], ["LIMIT", 1]]
19:29:14 web.1     | Cache write: rails_settings_cached/af1af454976854e81428e6a1a4a3f933/timeline_preview
19:29:14 web.1     | Cache read: rails_settings_cached/af1af454976854e81428e6a1a4a3f933/show_replies_in_public_timelines
19:29:14 web.1     | Cache generate: rails_settings_cached/af1af454976854e81428e6a1a4a3f933/show_replies_in_public_timelines
19:29:14 web.1     |   Setting Load (0.2ms)  SELECT "settings".* FROM "settings" WHERE (thing_type is NULL and thing_id is NULL) AND "settings"."var" = $1 ORDER BY "settings"."id" ASC LIMIT $2  [["var", "show_replies_in_public_timelines"], ["LIMIT", 1]]
19:29:14 web.1     | Cache write: rails_settings_cached/af1af454976854e81428e6a1a4a3f933/show_replies_in_public_timelines
19:29:14 web.1     | Cache read: rails_settings_cached/af1af454976854e81428e6a1a4a3f933/show_reblogs_in_public_timelines
19:29:14 web.1     | Cache generate: rails_settings_cached/af1af454976854e81428e6a1a4a3f933/show_reblogs_in_public_timelines
19:29:14 web.1     |   Setting Load (0.2ms)  SELECT "settings".* FROM "settings" WHERE (thing_type is NULL and thing_id is NULL) AND "settings"."var" = $1 ORDER BY "settings"."id" ASC LIMIT $2  [["var", "show_reblogs_in_public_timelines"], ["LIMIT", 1]]
19:29:14 web.1     | Cache write: rails_settings_cached/af1af454976854e81428e6a1a4a3f933/show_reblogs_in_public_timelines
19:29:14 web.1     | Cache read: exclude_account_ids_for:110651780559187701
19:29:14 web.1     | Cache generate: exclude_account_ids_for:110651780559187701
19:29:14 web.1     |    (0.1ms)  SELECT "blocks"."target_account_id" FROM "blocks" WHERE "blocks"."account_id" = $1  [["account_id", 110651780559187701]]
19:29:14 web.1     |    (0.1ms)  SELECT "blocks"."account_id" FROM "blocks" WHERE "blocks"."target_account_id" = $1  [["target_account_id", 110651780559187701]]
19:29:14 web.1     |    (0.1ms)  SELECT "mutes"."target_account_id" FROM "mutes" WHERE "mutes"."account_id" = $1  [["account_id", 110651780559187701]]
19:29:14 web.1     | Cache write: exclude_account_ids_for:110651780559187701
19:29:14 web.1     |   Status Load (0.4ms)  SELECT "statuses"."id", "statuses"."updated_at" FROM "statuses" INNER JOIN "accounts" ON "accounts"."id" = "statuses"."account_id" WHERE "statuses"."visibility" = $1 AND "accounts"."suspended_at" IS NULL AND "accounts"."silenced_at" IS NULL AND (statuses.reply = FALSE OR statuses.in_reply_to_account_id = statuses.account_id) AND "statuses"."reblog_of_id" IS NULL AND ("statuses"."local" = $2 OR "statuses"."uri" IS NULL) AND "statuses"."deleted_at" IS NULL AND 1=1 AND "statuses"."id" > 110651789342172781 ORDER BY "statuses"."id" DESC LIMIT $3  [["visibility", 0], ["local", true], ["LIMIT", 20]]
19:29:14 web.1     | Cache read: filters:v3:110651780559187701
19:29:14 web.1     | Cache generate: filters:v3:110651780559187701
19:29:14 web.1     |   SQL (0.2ms)  SELECT "custom_filter_keywords"."id" AS t0_r0, "custom_filter_keywords"."custom_filter_id" AS t0_r1, "custom_filter_keywords"."keyword" AS t0_r2, "custom_filter_keywords"."whole_word" AS t0_r3, "custom_filter_keywords"."created_at" AS t0_r4, "custom_filter_keywords"."updated_at" AS t0_r5, "custom_filter"."id" AS t1_r0, "custom_filter"."account_id" AS t1_r1, "custom_filter"."expires_at" AS t1_r2, "custom_filter"."phrase" AS t1_r3, "custom_filter"."context" AS t1_r4, "custom_filter"."created_at" AS t1_r5, "custom_filter"."updated_at" AS t1_r6, "custom_filter"."action" AS t1_r7 FROM "custom_filter_keywords" LEFT OUTER JOIN "custom_filters" "custom_filter" ON "custom_filter"."id" = "custom_filter_keywords"."custom_filter_id" WHERE "custom_filter"."account_id" = $1 AND (expires_at IS NULL OR expires_at > NOW())  [["account_id", 110651780559187701]]
19:29:14 web.1     |   SQL (0.2ms)  SELECT "custom_filter_statuses"."id" AS t0_r0, "custom_filter_statuses"."custom_filter_id" AS t0_r1, "custom_filter_statuses"."status_id" AS t0_r2, "custom_filter_statuses"."created_at" AS t0_r3, "custom_filter_statuses"."updated_at" AS t0_r4, "custom_filter"."id" AS t1_r0, "custom_filter"."account_id" AS t1_r1, "custom_filter"."expires_at" AS t1_r2, "custom_filter"."phrase" AS t1_r3, "custom_filter"."context" AS t1_r4, "custom_filter"."created_at" AS t1_r5, "custom_filter"."updated_at" AS t1_r6, "custom_filter"."action" AS t1_r7 FROM "custom_filter_statuses" LEFT OUTER JOIN "custom_filters" "custom_filter" ON "custom_filter"."id" = "custom_filter_statuses"."custom_filter_id" WHERE "custom_filter"."account_id" = $1 AND (expires_at IS NULL OR expires_at > NOW())  [["account_id", 110651780559187701]]
19:29:14 web.1     | Cache write: filters:v3:110651780559187701
19:29:14 web.1     | Completed 200 OK in 11ms (Views: 0.2ms | ActiveRecord: 2.0ms | Allocations: 9335)
19:29:14 web.1     | 
19:29:14 web.1     | 
`

### Specifications

Latest commit ed15893 with newly deployed Vagrant VM

**Comment by ClearlyClaire** [comment]
Ah, sorry about that. Identified the problem, I'll fix it upstream and port the changes in glitch-soc tomorrow.
