### ISSUE TITLE
Last column's timeline becomes empty after navigating back

### ISSUE THREAD

**Issue by MightyPork** [glitch-soc/mastodon#227]
steps:

1. open a toot
2. click the back arrow
3. timeline is empty

![screenshot_20171119_161344](https://user-images.githubusercontent.com/2041118/32991906-a0d30fae-cd44-11e7-86af-c3cfb3d81048.png)

**Comment by MightyPork** [comment]
might be upstream actually

**Comment by chriswmartin** [comment]
Possibly related to the glitch theme, this dosen't happen with the vanilla theme on my instance.
