### ISSUE TITLE
Crash on asset precompilation

### ISSUE THREAD

**Issue by thatcosmonaut** [glitch-soc/mastodon#2278]
### Steps to reproduce the problem

After updating to latest commit, I get this error on asset:precompile

```
Compilation failed:
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/home/mastodon/live/node_modules/@babel/types/lib/validators/generated/index.js:2740:35)
    at PluginPass.Program (/home/mastodon/live/node_modules/babel-plugin-lodash/lib/index.js:102:44)
```

### Expected behaviour

The assets should have precompiled

### Actual behaviour

The asset compiler crashed

### Specifications

Latest glitch-soc
Ruby 3.2.2

**Comment by ClearlyClaire** [comment]
The warning is just a warning. Is there any other error message? If not, check that it did not get OOM-killed

**Comment by thatcosmonaut** [comment]
Ah, Rails. Alright, will keep an eye on OOM

**Comment by thatcosmonaut** [comment]
Yep, that was it, thanks
