### ISSUE TITLE
When using slow mode, clicking on the "All" button under the notifications column if there is a notification that isn't loaded causes notification column to empty

### ISSUE THREAD

**Issue by 9p4** [glitch-soc/mastodon#2288]
### Steps to reproduce the problem

1. Enable slow mode
2. Enable advanced web interface
3. Get a notification on a post
4. In the notifications tab, click the "All" button

### Expected behaviour

The latest notifiction should have loaded

### Actual behaviour

The notifications tab removes all notifications until the page is refreshed

### Detailed description

Does not seem to affect vanilla Mastodon.

[mastodon.webm](https://github.com/glitch-soc/mastodon/assets/17993169/ce46066c-ad98-4d95-948e-c94e2c83e214)

### Specifications

ghcr.io/glitch-soc/mastodon:29503e5ba604 (4.1.3+glitch)

**Comment by Plastikmensch** [comment]
Can reproduce and confirm this happens in the glitch flavour and not in vanilla.
This seems to be caused by a missed change in e91bf82083ac390a0cf229d8e94fa412fdec57ff.
Will create a PR shortly.
