### ISSUE TITLE
Regex filter does not work on local feed

### ISSUE THREAD

**Issue by zackarired** [glitch-soc/mastodon#2295]
### Steps to reproduce the problem

1. Go to live feeds
2. Select This Server
3. Expand filters and add a regex to the field

### Expected behaviour

Posts should be filtered out based on the regex filter

### Actual behaviour

Nothing is filtered

### Specifications

Latest commit bb98d970e3f3333f85d454bc1fd26a1b582b14d2 with newly deployed Vagrant VM

I tried debugging it but could not find an obvious reason.

**Comment by Plastikmensch** [comment]
That's odd.
I tested this and it worked fine locally and I still cannot reproduce this.
Note that the regex filter does not apply to your own toots as these are always shown, which is expected behaviour.

**Comment by zackarired** [comment]
Ohhh, I only had my own toots in the server I tested from. I did not know this was the case. Where is it documented that my own toots are not filtered?

**Comment by zackarired** [comment]
I found the culprit: https://github.com/glitch-soc/mastodon/blob/bb98d970e3f3333f85d454bc1fd26a1b582b14d2/app/javascript/flavours/glitch/features/ui/containers/status_list_container.js#L36C56-L36C56

**Comment by Plastikmensch** [comment]
> Where is it documented that my own toots are not filtered? 

Nowhere afaik, unless you dig through the git history.
I'm working on adding regex filters to the docs, but I'm very busy with other stuff right now, so it'll take some time.

But this is in line with keyword filters also not applying to your own toots.
