### ISSUE TITLE
"Open in advanced web interface" button is shown on mobile web

### ISSUE THREAD

**Issue by tribela** [glitch-soc/mastodon#2307]
### Steps to reproduce the problem

1. Open /home in mobile browser
2.
3.
...

### Expected behaviour

Normal mobile layout

### Actual behaviour

Mobile layout with "Open in advanced web interface" button on side bar

### Detailed description

![image](https://github.com/glitch-soc/mastodon/assets/5047683/f3853773-a5c5-48a0-a13c-8e7a8000c7d9)

### Specifications

Commit 47a1941637

**Comment by ClearlyClaire** [comment]
I can reproduce the issue, and it doesn't happen using the vanilla flavor. I'm going to investigate it.
