### ISSUE TITLE
Quote toots open in new tab, not dynamic column in advanced web interface

### ISSUE THREAD

**Issue by ilmari** [glitch-soc/mastodon#2328]
### Steps to reproduce the problem

1. Use glitch edition advanced web interface
2. Click on a quote toot to view the original post

### Expected behaviour

The quoted post opens in the dynamic column

### Actual behaviour

The quoted post opens in a new tab

### Specifications

Glitch-soc v4.1.4+glitch.th
Firefox 102.13.0esr (64-bit) Debian 11 (Bullseye)

**Comment by Plastikmensch** [comment]
Glitch-soc doesn't support quote toots.
Either your instance made some modifications, in which case you should contact the admin, or you are referring to the link, which is shown, which is... well a link and supposed to open in a new tab.
