### ISSUE TITLE
Make keyword mutes operate on the text content of statuses

### ISSUE THREAD

**Issue by yipdw** [glitch-soc/mastodon#234]
At the moment, keyword mutes run on the status content as it is stored in the database, which means it's matching on both the status text and any HTML that's injected to control paragraph breaks, hashtag links, etc.

We should strip out this HTML and match only on the text.

**Comment by nightpool** [comment]
this would break matching on link urls, which is pretty important for some
usescases

**Comment by yipdw** [comment]
Is that a use case we could satisfy by matching on both the text content and the HTML?   Or perhaps we don't need to operate on tag-stripped text at all?

The initial motivation for doing text-only match was to support the "keyword mute for all-caps posts", but given the questions in #235 I'm not sure we can support that (at least not without making it a special case).

**Comment by marrus-sh** [comment]
the html content of statuses includes the full URL for masto instances, it's shortened via CSS. this does mean you can't match link urls from other instances though.

(notably, if this wasn't the case then link url matching wouldn't work on the regex filtering currently implemented in the frontend either)

**Comment by marrus-sh** [comment]
see https://github.com/glitch-soc/mastodon/blob/master/app/javascript/mastodon/reducers/statuses.js#L57 for how tags are currently stripped for searching and regex in the frontend

**Comment by marrus-sh** [comment]
(whoops, the relevant line is the domParser where `search_index` is calculated a few lines down)

**Comment by yipdw** [comment]
Oh, right -- I think you pointed this out to me before.  Maybe we'll have to replicate this in the backend for consistency's sake.

**Comment by yipdw** [comment]
Double-checking: if client-side regex _does_ filter on links, is it really looking at `href`, `src`, etc? The method used to build `search_index` doesn't seem to include that information: 
![screenshot_20171221_165825](https://user-images.githubusercontent.com/3859/34278417-4151a3d4-e670-11e7-95fd-1b7489db3c8f.png)

**Comment by marrus-sh** [comment]
it is not because `a.href === a.textContent` for mastodon statuses~

**Comment by yipdw** [comment]
#236 addresses this issue.
