### ISSUE TITLE
Makara missing - read replica not possible?

### ISSUE THREAD

**Issue by hcsaustrup** [glitch-soc/mastodon#2340]
### Steps to reproduce the problem

`makara` seems to have been removed from the Gemfile recently, rendering my configuration invalid and causing the errors below. Is the Makara read replica trick described here https://docs.joinmastodon.org/admin/scaling/#read-replicas being phased out - maybe in favour of something else? 

Please advise.

```
rake aborted!
LoadError: Could not load the 'postgresql_makara' Active Record adapter. Ensure that the adapter is spelled correctly in config/database.yml and that you've added the necessary adapter gem to your Gemfile.
```

### Expected behaviour

It should work, like it did in a40529fa79c6882eb1929014e5f9324d8e81ae49

### Actual behaviour

It fails as it's unable to load the postgresql_makara adapter

### Specifications

Version: `nightly-2023-07-29` (also fails in `latest`)
Previous working  version: `a40529fa79c6882eb1929014e5f9324d8e81ae49`

**Comment by ClearlyClaire** [comment]
Hi!
Yes, `makara` has been removed, in favor of native Rails support for replicas. You can use `DB_NAME`, `DB_USER`, `DB_PASS`, `DB_HOST` and `DB_PORT` for the primary, and `DB_REPLICA_NAME`, `DB_REPLICA_USER`, `DB_REPLICA_PASS`, `DB_REPLICA_HOST`, `DB_REPLICA_PORT` for the replica (if any of the replica env vars is omitted, it will use the primary one instead)

**Comment by ClearlyClaire** [comment]
Closing as the feature has been replaced with native support for replicas, but heads up the above comment is outdated and the proper env var names are `REPLICA_DB_*` and not `DB_REPLICA_*`
