### ISSUE TITLE
Allow keyword mutes to be specified as regexes

### ISSUE THREAD

**Issue by yipdw** [glitch-soc/mastodon#235]

**Comment by yipdw** [comment]
Question: How do we prevent pathologically slow regular expressions from affecting other people on the server?

**Comment by MightyPork** [comment]
would limiting the regex size help?

**Comment by yipdw** [comment]
I don't think it would.  Try this:

```
s = 'foo ' * 70 + 'fo '
r1 = /^(\s*foo\s*)*$/
s =~ r1
```

On Ruby 2.3.3p222, this takes a _very_ long time to finish.

**Comment by MightyPork** [comment]
hmmmm :thounking:

you could time how long it takes and when it once exceeds some limit like e.g. 500ms, disable/delete it. then the slowdown won't ruin the server for everyone until some admin steps in, but only lag it once

**Comment by yipdw** [comment]
Timing could catch the most egregiously slow regexes.  (I'm not sure if it'd also catch those that require a lot of memory, but maybe there exists a good correlation between time and space.)  However, to make timing work, we'd need to know (at least):

- what's the average time cost for the "good" keyword mutes? (this is per-environment)
- what's the variability introduced by e.g. garbage collection?

I would like to know timings anyway, but that's for curiosity and performance reasons, and these numbers require careful measurement.

I think a timing-based approach would also not prevent a situation where someone adds bad regexes on one instance and then toots out something that looks spammy but innocuous ("foo foo foo ...") on a second instance.  With multiple mutes, this would add up to (say) ~500ms of mute-checking work for each bad regex, and in the meantime task queues clog up.  Depending on the server, this could be a one-time annoyance or cause prolonged degradation of service -- but I don't think either should be a possibility.

**Comment by yipdw** [comment]
I think I'm going to drop this idea: I still don't know of a good way to make it robust in a multi-user environment (save implementing another regex engine, which doesn't seem like a good use of time), and in practice it doesn't seem like people want regexes in keyword mutes.

Feel free to re-open if this does not seem true.
