### ISSUE TITLE
Set default post formatting to markdown as admin

### ISSUE THREAD

**Issue by jenbanim** [glitch-soc/mastodon#2357]
### Pitch

I would like to make markdown rather than plain text the default post formatting for new users on my server

![image](https://github.com/glitch-soc/mastodon/assets/40228062/bee08b74-2065-4dd4-be1f-36234b5d09a8)

### Motivation

The majority of users on my server are migrating away from Reddit. We switched the server to Mastodon Glitch specifically for the markdown support (which is wonderful btw, thank you). Rather than sending every new user a guide on how to set up their preferences to create a familiar interface, I would like to reduce friction by setting defaults that are comfortable for the people using my server

I was able to make changes to the default glitch app settings by following the instructions in #2191 and editing the file `app/javascript/flavours/glitch/reducers/local_settings.js`. Is there an option in that file or somewhere else that contains the default post formatting?

**Comment by TheEssem** [comment]
Seems like this is possible by applying #2361 and changing `default_content_type` in config/settings.yml to `text/markdown`. Hoping that pull request gets merged.

**Comment by jenbanim** [comment]
Thanks! Since creating this issue I've switched to your Chuckya fork that implements this feature, so I'm marking this issue as closed
