### ISSUE TITLE
Have an option to disable the upcoming public search index

### ISSUE THREAD

**Issue by ShadowJonathan** [glitch-soc/mastodon#2358]
### Pitch

I would like to be able to disable public post search via environment variables, so that the elasticsearch instance will not index them.

### Motivation

This is caused by me seeing this PR, which basically assures that mastodon soon will get a public search ability; https://github.com/mastodon/mastodon/pull/26344

I'd like to get ahead of that, and ask if it's possible to disable this via environment variables, like so many things already are configurable for glitch-soc

**Comment by tobyink** [comment]
Don't want to bike shed too much, but environment variables seems a weird way to control this. Wouldn't a config file option or a setting available in the preferences screens make more sense?

**Comment by ShadowJonathan** [comment]
AFAIK the environment variable file (`.env.production`) is pretty much the config file, unless there's another one I'm not aware of?

**Comment by tobyink** [comment]
There's `config/environments/production.rb`, `config/settings.yml`, and basically the entire `config` directory.

**Comment by ShadowJonathan** [comment]
Ah, I just found https://github.com/mastodon/mastodon/pull/23808, which may be interesting to look at

**Comment by ClearlyClaire** [comment]
Upstream is going to use a separate, opt-in setting. I believe we can close this issue? It's not going to be per-post like https://github.com/mastodon/mastodon/pull/23808, but it's going to be opt-in either way.
