### ISSUE TITLE
Have glitch-soc omit "discoverable" actor key for remote instances

### ISSUE THREAD

**Issue by ShadowJonathan** [glitch-soc/mastodon#2359]
### Pitch

I'd like to have a setting for our instance where I can make sure that the "discoverable" key effectively sets to "false" for remote instances, but works as intended for the local instance.

### Motivation

This is to avoid scraping and indexing of public posts, as being put forward in the PR here: https://github.com/mastodon/mastodon/pull/26344

Omitting "discoverable" for remote instances will allow it to isolate from whatever remote mastodon instances if they add search or not.

**Comment by Plastikmensch** [comment]
It is not 100% clear that the new search really will use `discoverable` or a newly introduced setting specifically for that.
I does now, but people have brought up the issue with that upstream already and while I have as little faith as anyone, I expect it to be changed. But even when not, I wouldn't expect glitch-soc to accept that as is.

**Comment by ClearlyClaire** [comment]
Upstream is [leaning towards using a separate flag](https://github.com/mastodon/mastodon/issues/26418#issuecomment-1672148043), so this and #2358 will probably not be needed. Will see when that happens, though, and keeping these issues open for now.

**Comment by ShadowJonathan** [comment]
That's reasonable, yeah.
