### ISSUE TITLE
Port upstream's hashtag handling

### ISSUE THREAD

**Issue by ClearlyClaire** [glitch-soc/mastodon#2381]
I am not completely on board with the styling (see https://github.com/mastodon/mastodon/pull/26606) and even less with the fact tags are moved at display time rather than authoring time (we may want to split the two behaviors)

### Commits

- df6e7198984b42cf8d64e66548742e14264236a0
- 85ecadb6309ba43ee8bfeb21dfbdee72ff773252
- f0862bcf984d994b9f0b0bbea82431e5a1812351
- 3ed2bf92d06a5ebaf3ad92a55d5ae3c0c2640686
- 061fd66ee66afc8a5c7923ff7648f51a6da3fe7c
- 58acaa9ae666d4e40c5b68316513a0fcb9200daf
- 44ba785242c14bdfcd95854683a69a8451288dba
- 613cfd625c8be11b4fb91d769ddbeee7a535a57a
- 10b06436d13702aedaa92a8ece84fbfde2829d57
- 4d59dfb1c619ebec44243acc7f21dc3edb9feb3b

**Comment by Leatherface75** [comment]
Reason for that is because Fediverse is bigger than Mastodon if i understand this right.

**Comment by Leatherface75** [comment]
Something like this is what i prefer and added this on my instance but what to change to port it to Glitch theme?

![image](https://github.com/glitch-soc/mastodon/assets/2489019/22c92b09-2902-44c9-8e16-83b412bc99a4)
