### ISSUE TITLE
Local timeline/Global Timeline header shenanigans

### ISSUE THREAD

**Issue by Selene-Amanita** [glitch-soc/mastodon#2382]
### Steps to reproduce the problem

Click on "Local Timeline" or "Global Timeline" on the advanced web interface, scroll down, then click on the header of that column.

### Expected behaviour

The header displaying "Local Timeline" and going to the top of the column

### Actual behaviour

The header displaying "Live feed" and nothing

### Detailed description

Seen on octodon.social and eldritch.cafe (glitch.soc v4.2.0-beta1+glitch) not on kitty.town (vanilla v4.1.6), it might be an upstream bug but idk.

When in advance mode:
- clicking on "Local Timeline" or "Global Timeline" (from above the message box or from the menu) makes the column that appears display "Live Feed" as a header instead of "Local Timeline" or "Global Timeline"
- clicking on that header doesn't "go to the top" of the column, like all other columns do

When in basic mode:
- the menu only displays a "Local Feed", which seems to be the Local Timeline, I assume it's an attempt to simplify the interface for newcomers, but wouldn't that be a problem for small instances with few public local messages?
- clicking on the header to go to the top seems to work

### Mastodon instance

octodon.social

### Mastodon version

v4.2.0-beta1+glitch

### Browser name and version

Firefox 115.0.2

### Operating system

Mint Vera 21.1 Mate

**Comment by Plastikmensch** [comment]
Yes, not scrolling to top is an upstream bug and caused by the wrapping of the live feed having 2 `scrollable` classes in the advanced UI and `scrollTop` selecting the wrong one.

(In case someone wants to fix it themselves)
```diff
diff --git a/app/javascript/flavours/glitch/components/column.jsx b/app/javascript/flavours/glitch/components/column.jsx
index 312a6848b5..badaeaaf5a 100644
--- a/app/javascript/flavours/glitch/components/column.jsx
+++ b/app/javascript/flavours/glitch/components/column.jsx
@@ -18,7 +18,7 @@ export default class Column extends PureComponent {
   };
 
   scrollTop () {
-    const scrollable = this.props.bindToDocument ? document.scrollingElement : this.node.querySelector('.scrollable');
+    const scrollable = this.props.bindToDocument ? document.scrollingElement : this.node.querySelector('.scrollable:not(.scrollable--flex)');
 
     if (!scrollable) {
       return;
```

The local and federated timeline have been replaced by the live feed (or also called "firehose") column recently.

**Comment by ClearlyClaire** [comment]
@Selene-Amanita thanks for the report! This is indeed a known upstream issue (see https://github.com/mastodon/mastodon/issues/26405)

@Plastikmensch would you be interested in submitting a PR upstream? (Though I suspect your patch may interfere with other uses of `scrollable--flex`)

**Comment by ClearlyClaire** [comment]
@Plastikmensch nevermind, I'm taking this upstream, and will credit you as co-author.

**Comment by Plastikmensch** [comment]
> @Plastikmensch nevermind, I'm taking this upstream, and will credit you as co-author.

I'm okay with that.

**Comment by ClearlyClaire** [comment]
Done: https://github.com/mastodon/mastodon/pull/26633
