### ISSUE TITLE
When OMNIAUTH_ONLY=true the web interface stuck and cannot log in v4.2.0

### ISSUE THREAD

**Issue by fame-odoo** [glitch-soc/mastodon#2405]
### Pitch

Hi, several days ago I opened this issue in mastodon and seems like it is not working for glitch version as well.

I have been using glitch version all the time. I am wondering will we fix this bug as well? (I honestly really don't enjoy the PR related to that issue. I would prefer the old log in page even it just has one button)

https://github.com/mastodon/mastodon/issues/26849

### Motivation

https://github.com/mastodon/mastodon/issues/26849

**Comment by Plastikmensch** [comment]
The same fix will be applied to glitch-soc in an upstream merge.
This can take a bit though, as upstream is close to a new release, which means Claire, who does the upstream merges, will be even busier than usual.

Whether or not the old login page will be kept, I can't say, but I wouldn't count on it.
