### ISSUE TITLE
db:migrate syntax error on 0cb343eec2086809564455319b4bc3f1343c5dd4

### ISSUE THREAD

**Issue by melissaboiko** [glitch-soc/mastodon#2415]
### Steps to reproduce the problem

Just tried a regular upgrade process, and at the database step I'm getting this:

  ```sh
  + env RAILS_ENV=production bundle exec rails db:migrate
  -- execute("REINDEX INDEX CONCURRENTLY preview_cards_statuses_pkey")
  rails aborted!
  StandardError: An error has occurred, all later migrations canceled:

  PG::SyntaxError: ERROR:  syntax error at or near "CONCURRENTLY"
  LINE 1: REINDEX INDEX CONCURRENTLY preview_cards_statuses_pkey
  ```

### Expected behaviour

db:migrate

### Actual behaviour

reproducible SQL syntax error 

### Technical details

 * ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
 * node v18.13.0
 * postgresl 11.20-1.pgdg120+1
 * upgrading from v4.1.4+glitch

**Comment by ClearlyClaire** [comment]
0cb343eec2086809564455319b4bc3f1343c5dd4 does not match any commit known to me, but the issue you're facing should be fixed in a recent glitch-soc version

**Comment by melissaboiko** [comment]
maybe I'm confusing something? I thought that's the commit I get from pulling from main right now ("Tag nightly images as `latest` in glitch-soc...")

**Comment by ClearlyClaire** [comment]
oops i was the one being confused, sorry, 0cb343eec2086809564455319b4bc3f1343c5dd4 does exist it's indeed the latest

**Comment by ClearlyClaire** [comment]
I think I identified the issue, gonna fix it soon!

**Comment by ClearlyClaire** [comment]
can you try the latest version? it should now work

**Comment by melissaboiko** [comment]
it solved the problem, thanks for your work!

but now I'm getting something else:

```
-- add_index(:preview_cards_statuses, [:status_id, :preview_card_id], {:name=>:preview_cards_statuses_pkey, :algorithm=>
:concurrently, :unique=>true})
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "preview_cards_statuses_pkey" already exists
/home/mastodon/glitch-soc/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgre
sql/database_statements.rb:48:in `exec'
```

perhaps my database was left in an inconsistent state after the last failed migration?

**Comment by ClearlyClaire** [comment]
Please do `DROP INDEX preview_cards_statuses_pkey` in PostgreSQL and try the migration again

**Comment by melissaboiko** [comment]
worked without a hitch! thank you so much!
