### ISSUE TITLE
Search results are not scrollable

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#244]
7 results, but I can't scroll down to see the bottom of the list:

![screen shot 2017-12-07 at 22 11 03](https://user-images.githubusercontent.com/6607512/33741364-df8e2dfe-db9b-11e7-9c7a-55075d59a757.png)

Mac 10.13.1, latest version of Chrome.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by marrus-sh** [comment]
We made some changes to how the left-hand column operates and scrolls and it's caused us no end of grief with stuff like this 🤦🏻‍♀️

There's an `overflow: auto;` that needs to be added somewhere, we just need to figure out where and add it.

**Comment by marrus-sh** [comment]
This should be fixed by e677dda; I added a class to make the search results scrollable

**Comment by Cassolotl** [comment]
@marrus-sh Is that a version that will happen sometime soon or is it already up? (I'm asking because search results are not scrollable for me right now but that might be because you've not updated yet!)

**Comment by marrus-sh** [comment]
@Cassolotl it should be up now; let me know if it's still not working for you!

**Comment by Cassolotl** [comment]
It works! :) \o/ Thank you!
