### ISSUE TITLE
Clicking avatars on profiles in last column doesn't open profile in new tab

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#245]
This bit!

![screen shot 2017-12-07 at 22 16 23](https://user-images.githubusercontent.com/6607512/33741469-5ef138a2-db9c-11e7-8368-7e53cfb8cc60.png)

When I click a big avatar in that column, nothing happens. I'm used to it opening a profile in a new tab, and can't find any other way of opening a profile in a tab now. :S

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yipdw** [comment]
It looks like https://github.com/glitch-soc/mastodon/blob/master/app/javascript/flavours/glitch/features/account/components/header.js is missing the `<a>` wrapping the avatar that's present in vanilla: https://github.com/glitch-soc/mastodon/blob/master/app/javascript/mastodon/features/account/components/header.js#L45

I guess we can add something similar to the header component?

**Comment by marrus-sh** [comment]
Yeah I think when I wrote this I assumed that the `<Avatar>` component created a link but it looks like that's not the case; wrapping it in an `<a>` should be sufficient.

We don't need as complicated of code as vanilla since our avatars don't do the round animation, just gotta add the link.
