### ISSUE TITLE
Port upstream's icon changes

### ISSUE THREAD

**Issue by ClearlyClaire** [glitch-soc/mastodon#2453]
### Pitch

Commits to be ported:
- 134de736dcbc6aa613fd5aec21d983d92d8b0be8
- f08ca3f04289e3a258e8bff772177c20906930c3
- a4e6fe36cb79b24bf31599222ebb99ceef051414
- fa7e64df1de13b361551b0ff8f81335719c1a4a2
- e4e752c26e526d0d29e3fe5e2cf5ca9d915546ef
- 7e3c10dec676b0a560493071c5950c7e5df759b2
- 7b1d3907340d40bb60098b01bfb7b2e34ba9e7f1
- 1cba91d6d116f482d5dd052bd89adb76bf3aa41e

### Motivation

Keeping up with upstream, having more modern and maintainable icons, as well as have better accessibility. This will be a lot of work, though.

**Comment by Ember-ruby** [comment]
bit sad that this would remove the animations

**Comment by ClearlyClaire** [comment]
I agree. Custom icons and animations for the “boost” icon are planned, as for the “like” icon, upstream will change it to a heart icon, so the animation would not make a lot of sense. I can probably restore the animation for the fav icon if I port those changes before it happens.
