### ISSUE TITLE
Clicking "back" while looking at a list of people who boosted a toot takes you back to Getting Started

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#247]
Duplication! This is on dev.glitch.social.

1. Click on toot to view in far-right column.
2. Click on the tiny boost symbol to see who has saved/boosted it. URL should end in /reblogs or /favourites.
3. Click "Back" at the top of that far-right column.

**Expected behaviour:** As on unmodified Mastodons, I would expect it to go back to view the toot in the far-right column, as at the end of step 1.

**Actual behaviour:** It jumps the UI to the right, bringing the focus back to the new toot column, and the far-right column becomes the Getting Started menu. The URL becomes https://dev.glitch.social/web/getting-started.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yipdw** [comment]
Hmm, I can't seem to reproduce this issue (using Firefox 58.0a1):
![untitled](https://user-images.githubusercontent.com/3859/33776618-96d7ea84-dc07-11e7-8787-c5a63b70f54d.gif)

Are there other actions or initial conditions that might be involved?

**Comment by yipdw** [comment]
Oh, to clarify the flavour: I was using `glitch/default` on `dev.glitch.social` in that GIF.  I'm trying `vanilla/default` now, but haven't yet come up with a reproduction there either.

**Comment by Cassolotl** [comment]
I was using glitch/default, I think. I can't think of any other factors, I'm not using style sheets or anything... Maybe it's somehow just Chrome?

Now that I've been paying attention, this happens whenever I click "back" in that far-right column, for any reason.

**Comment by yipdw** [comment]
I can give this a shot with Chromium (62, I think?) in a bit.

**Comment by marrus-sh** [comment]
Did you refresh the page (including an auto-refresh if you're in a dev environment) at any time during this sequence? because that can introduce this sort of bug.

**Comment by marrus-sh** [comment]
in particular, this behavior will happen if the length of your browser history drops below the length that it had when the page first open, which happens after a page refresh and manually clicking your browser's back button a few times on a masto tab that has preexisting masto history

**Comment by Cassolotl** [comment]
@marrus-sh 

>Did you refresh the page (including an auto-refresh if you're in a dev environment) at any time during this sequence? because that can introduce this sort of bug.

No, I didn't. It happens every time, regardless of page reloads or lack thereof.

**Comment by marrus-sh** [comment]
hmmm. if you have access to the console, knowing the values of `window.history.length` and `window._mastoInitialHistoryLen` might be helpful. otherwise, i'm not sure what it could be off the top of my head; we'll have to poke around

**Comment by Cassolotl** [comment]
Gosh, I have no idea how to do that. :S

**Comment by marrus-sh** [comment]
we'll have to poke around and see if we can reproduce it then :P thanks for reporting the issue!

**Comment by Cassolotl** [comment]
Thank you for looking into it! :)

**Comment by Cassolotl** [comment]
Did you change something? It seems to be back to normal now!

**Comment by marrus-sh** [comment]
I… don't think we did? But if things are working for you, I'm glad :)

The probable cause of the problem you were having is, we changed some code so that if you press the “Back” button and the previous page *isn't* a part of the web UI (ie., a page from another site, or the Preferences pane, or anything else), then instead of navigating you away from the app, it will just take you to Getting Started. But the code is a little finicky—for security reasons, browsers don't give us access to your browser history, so we kinda have to guess? There are probably improvements that can be made here, anyway.

**Comment by Cassolotl** [comment]
Huh! Maybe it *was* Chrome and they fixed it then!

**Comment by Cassolotl** [comment]
This is happening again! It happens on dev.glitch.social but not ephemeral.glitch.social or just glitch.social. No page reloads in the middle or anything like that.

**Comment by Cassolotl** [comment]
Is that something that happens on vanilla Mastodon too? I can open a new issue on that issue list if so.

**Comment by Cassolotl** [comment]
Cool, thank you very much! :)

**Comment by ThibG** [comment]
So, `window.history.length` is not going to be very useful for us.
If I understand correctly, I think the best thing we can do is store something in the history location state to tell whether the current state is from a navigation within the application or not. With that, it would survive reloads and will not go beyond the app.
