### ISSUE TITLE
something in the last 7 commits breaks CSP

### ISSUE THREAD

**Issue by Ember-ruby** [glitch-soc/mastodon#2484]
### Steps to reproduce the problem

1.  [merged latest 7 commits](https://github.com/Ember-ruby/mastodon-glitch/commit/3c103a6ea822126f5ed61310c5d272b0077826ac#diff-c1c619ffb7b249550067cb696b8e7d6c29d1efe2ed4cf5b7a8bb6bed47b409d1)
2. reload server
3. no images load

![Screenshot_20231126_131402](https://github.com/glitch-soc/mastodon/assets/48266942/46951675-a7b8-4d0a-85c5-9661b369ee44)

### Expected behaviour

the images should load

### Actual behaviour

they do not

### Mastodon instance

blobfox.coffee

### Mastodon version

latest

### Browser name and version

firefox 120

### Operating system

nixos latest

**Comment by Leatherface75** [comment]
I have problems with pictures on previews.
It shows in the beginning and then dissapears after a while but previews from people on other servers works.
I didn't have this problems until for 2-3 months ago.

![image](https://github.com/glitch-soc/mastodon/assets/2489019/53c6a06f-eaa4-439e-9ebe-be78f8ae53f9)

**Comment by Ember-ruby** [comment]
that seems entirely unrelated

**Comment by ClearlyClaire** [comment]
Have you changed anything since you reported the issue? I can't reproduce it on your instance.

**Comment by ClearlyClaire** [comment]
I assume you have rolled back and that is why this is currently working on your instance, and I assume you were using `EXTRA_DATA_HOSTS` to allow blob.jortage.com. If that's the case, this is caused by a recent change in glitch-soc inadvertently dropping support for `EXTRA_DATA_HOSTS`. This should be fixed now, as I have reverted the changes in #2485

**Comment by Leatherface75** [comment]
> that seems entirely unrelated

Ok maybe but seems something have changed with image previews in later releases.
The strange thing is that it works first but dissapears after some day, a week or so.

**Comment by Ember-ruby** [comment]
> I assume you have rolled back and that is why this is currently working on your instance, and I assume you were using `EXTRA_DATA_HOSTS` to allow blob.jortage.com. If that's the case, this is caused by a recent change in glitch-soc inadvertently dropping support for `EXTRA_DATA_HOSTS`. This should be fixed now, as I have reverted the changes in #2485

yeah, i rolled back the commits, and also yes, using the `EXTRA_DATA_HOSTS`

**Comment by Leatherface75** [comment]
> > that seems entirely unrelated
> 
> Ok maybe but seems something have changed with image previews in later releases. The strange thing is that it works first but dissapears after some days, a week or so and not on image previews on other instances.

This seems to be my problem after 5 days mediacache dissapears 

![image](https://github.com/glitch-soc/mastodon/assets/2489019/3aa25606-8b60-4fa1-9254-5dca780c6930)

**Comment by Leatherface75** [comment]
> > > that seems entirely unrelated
> > 
> > 
> > Ok maybe but seems something have changed with image previews in later releases. The strange thing is that it works first but dissapears after some days, a week or so and not on image previews on other instances.
> 
> This seems to be my problem after 5 days previews dissapears when mediacache is cleaned. But it should download it again after that and it shouldn't dissapear on local cache.
> 
> ![image](https://private-user-images.githubusercontent.com/2489019/287464288-3aa25606-8b60-4fa1-9254-5dca780c6930.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1Mzg3OTEsIm5iZiI6MTcwMTUzODQ5MSwicGF0aCI6Ii8yNDg5MDE5LzI4NzQ2NDI4OC0zYWEyNTYwNi04YjYwLTRmYTEtOTI1NC01ZGNhNzgwYzY5MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDJUMTczNDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjkyM2YwNjg5YmIzYWQzNWE3NDI0MDljZWU4MGNkYzIxOGNkNTFhYjgxOTI1OWY2OWUyMDZjY2RlMmRiYmU3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4aLLnaos1BeoyHRLQ3lkGdvBRqhSGFywKQEycnXAFs8)

![image](https://github.com/glitch-soc/mastodon/assets/2489019/bd3a9711-1c67-49f0-9833-89e2cbb53e1f)

**Comment by Leatherface75** [comment]
> > > > that seems entirely unrelated
> > > 
> > > 
> > > Ok maybe but seems something have changed with image previews in later releases. The strange thing is that it works first but dissapears after some days, a week or so and not on image previews on other instances.
> > 
> > 
> > This seems to be my problem after 5 days previews dissapears when mediacache is cleaned. But it should download it again after that and it shouldn't dissapear on local cache.
> > ![image](https://private-user-images.githubusercontent.com/2489019/287464288-3aa25606-8b60-4fa1-9254-5dca780c6930.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1Mzg3OTEsIm5iZiI6MTcwMTUzODQ5MSwicGF0aCI6Ii8yNDg5MDE5LzI4NzQ2NDI4OC0zYWEyNTYwNi04YjYwLTRmYTEtOTI1NC01ZGNhNzgwYzY5MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDJUMTczNDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjkyM2YwNjg5YmIzYWQzNWE3NDI0MDljZWU4MGNkYzIxOGNkNTFhYjgxOTI1OWY2OWUyMDZjY2RlMmRiYmU3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4aLLnaos1BeoyHRLQ3lkGdvBRqhSGFywKQEycnXAFs8)
> 
> ![image](https://private-user-images.githubusercontent.com/2489019/287464495-bd3a9711-1c67-49f0-9833-89e2cbb53e1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MzkxMjgsIm5iZiI6MTcwMTUzODgyOCwicGF0aCI6Ii8yNDg5MDE5LzI4NzQ2NDQ5NS1iZDNhOTcxMS0xYzY3LTQ5ZjAtOTgzMy04OWUyY2JiNTNlMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDJUMTc0MDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2JiMTQ0ZGUzNDliNTU1ZDU5ZmJmMTE5YWFlMjZiM2I5NmIzOTNjMjgwMWY0MzcyYmZhZGZlODVlODgxMThjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7IminbRmfiaaNVsJQfHx3LXUwT2BokDnVne-96o26C8)

Didn't see this behaviour before 5.2.0 or 5.2.1 update.
As it is not it seems i have to change to unlimited mediacache to keep the previews.
