### ISSUE TITLE
unpinning home column in vanilla flavour leads to blank screen in glitch flavour

### ISSUE THREAD

**Issue by chriswmartin** [glitch-soc/mastodon#249]
When I unpin my home column in a vanilla flavour and then switch to a glitch flavour I get stuck with a blank screen and the console error "TypeError: Cannot read property 'name' of undefined."

This is only the case with the home column, not the notification column or any others.

![screenshot of console error](https://user-images.githubusercontent.com/17181697/33792411-a1493dea-dc63-11e7-8336-c3d5d18a3eb8.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by marrus-sh** [comment]
@chriswmartin I'm not able to reproduce this on dev.glitch.social right now—is this still an issue

**Comment by chriswmartin** [comment]
yup seems to be working again!
