### ISSUE TITLE
Users brought to onboarding screen when opening links a new tab

### ISSUE THREAD

**Issue by arimelody** [glitch-soc/mastodon#2504]
### Steps to reproduce the problem

1. Copy a URL from the interface (user's profile URL, a link to a post, etc)
2. Paste this into a new tab and enter
3. You should be brought to this onboarding screen, or similar
![firefox_W2erxfcPOr](https://github.com/glitch-soc/mastodon/assets/38161443/7cc1ba15-7517-4939-9421-345c889c4b17)

### Expected behaviour

Should have been brought to the desired page

### Actual behaviour

Brought to the onboarding page

### Mastodon instance

wetdry.world

### Mastodon version

v4.3.0-alpha.0+chuckya

### Browser name and version

Firefox 120.0.1

### Operating system

Windows 11 (22631.2715)

**Comment by mellodoot** [comment]
i believe this may be related to #2503? assuming the getting started panel more-less embeds the /getting-started route, which falls under this behaviour

**Comment by mellodoot** [comment]
this fixes the issue for our instance, should work elsewhere! closing the issue.
