### ISSUE TITLE
NoMethodError (undefined method `url' for #<PreviewCardsStatus

### ISSUE THREAD

**Issue by MFYDev** [glitch-soc/mastodon#2542]
### Steps to reproduce the problem

1. use the latest nightly image
2. see that error

### Expected behaviour

No error

### Actual behaviour

500 error

### Detailed description

INFO -- : [ca3dcf10-5f93-4ae8-b5ec-0c9428e879bd] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=500 allocations=49694 duration=38.28 view=0.00 db=3.85
F, [2023-12-22T15:40:32.500447 #17] FATAL -- : [ca3dcf10-5f93-4ae8-b5ec-0c9428e879bd]   
[ca3dcf10-5f93-4ae8-b5ec-0c9428e879bd] NoMethodError (undefined method `url' for #<PreviewCardsStatus status_id: 111581297262287960, preview_card_id: 405>):

### Mastodon version

latest nightly

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by MFYDev** [comment]
I think it is the streaming server's error

**Comment by ClearlyClaire** [comment]
Hi, please run the database migrations and restart the Mastodon services.

**Comment by MFYDev** [comment]
Thank you so much @ClearlyClaire , issue fixed
