### ISSUE TITLE
Can't pull streaming image

### ISSUE THREAD

**Issue by jippi** [glitch-soc/mastodon#2545]
### Steps to reproduce the problem

1. `docker pull ghcr.io/glitch-soc/mastodon-streaming:${MASTODON_VERSION}` as anonymous / non-maintainer

### Expected behaviour

container can be pulled

### Actual behaviour

Error response from daemon: Head "https://ghcr.io/v2/glitch-soc/mastodon-streaming/manifests/nightly.2023-12-23": unauthorized

### Detailed description

Seems to be pushed in https://github.com/glitch-soc/mastodon/actions/runs/7305629691/job/19909424774#step:10:651 correctly, but can't pull it

### Mastodon instance

expressional.social

### Mastodon version

nightly.2023-12-23

**Comment by ClearlyClaire** [comment]
Sorry about this, this should now be fixed!

**Comment by jippi** [comment]
Thank you! Can confirm it's working as expected now

**Comment by Nikos410** [comment]
Hey @ClearlyClaire sorry to bother you again. I noticed the streaming image is not tagged `latest`, there are only nightly and edge tags available. Is that intended?

Best
Nikos

**Comment by ClearlyClaire** [comment]
The `mastodon-streaming` docker image now has a `latest` tag just like the `mastodon` docker image.
