### ISSUE TITLE
Add a button to the compose box to switch between Rich text, markdown, and HTML

### ISSUE THREAD

**Issue by DraconicNEO** [glitch-soc/mastodon#2551]
### Pitch

I think it would be a good idea to add a button to the compose box that allows switching between the different writting modes on the fly in case you don't want to use markdown or HTML in some situations or only want to use them specifically in others. Currently the only way to switch between them is in the settings.

### Motivation

Currently the only way to switch between these modes is by going in the settings. I think it would be good for there to be a way to switch from the compose box without needing to go into settings.

**Comment by RustyLoaf** [comment]
This feature already exists, it just needs to be turned on in the App Settings modal. Click "App Settings" in the right sidebar, then click "Compose box" and tick the option next to "Show content-type choice when authoring toots". The documentation for it is [here](https://glitch-soc.github.io/docs/features/rich-text/).
