### ISSUE TITLE
Duplicated post in meatballs menu when opened by touch gesture makes options inaccessible

### ISSUE THREAD

**Issue by Enichan** [glitch-soc/mastodon#2614]
### Steps to reproduce the problem

1. Open your home feed on a glitch-soc instance using a glitch flavour skin on a mobile device or on a desktop browser with touch emulation turned on
2. Touch the meatballs menu on a long post in your feed
3. A modal menu pops up, with the post in question duplicated at the top (the post *is not* duplicated when clicking with a mouse)
4. If the post is not very short, menu options will overflow off the bottom of the modal popup and cannot be accessed

### Expected behaviour

All options should be accessible

### Actual behaviour

Menu options are inaccessible

### Detailed description

When using a touch gesture on the meatballs menu of a post in your feed the post in question is duplicated at the top of the modal popup menu. If this post is not very short, menu options become inaccessible by overflowing off the bottom of the modal popup. Post duplication only happens when using a touch gesture, not when clicking with a mouse, so this problem only occurs on mobile. This only happens using the glitch flavour of skins, not the vanilla mastodon flavour of skins.

In portrait mode the modal popup cannot be scrolled at all, while in landscape mode the menu options can be scrolled, but if the post is too long the section containing the menu options isn't visible and so all options are inaccessible. Neither landscape nor portrait mode allows scrolling past the duplicated status at the top of the modal dialogue.

The post is not duplicated when opening a status via "expand this post" and opening the meatballs menu with a touch gesture, but menu options may be missing in that view, such as the "filter this post" option. This effectively makes it impossible to "filter this post" on medium to long posts on mobile when using the glitch flavour skins.

Workaround: if ublock origin filter rules are available on a device the following rule hides the duplicate post: `yourinstance.domain##.actions-modal > div.status`

Suggested fix: remove post duplication when opening the modal popup dialog using touch since this post duplication in the modal dialog does not happen when clicking with a mouse.

Screenshot:
![Screenshot 2024-02-10 174629](https://github.com/glitch-soc/mastodon/assets/3856285/01d7de3b-d4cc-48e9-8237-a4d5d754c036)

### Mastodon instance

peoplemaking.games

### Mastodon version

v4.3.0-alpha.1+glitch

### Browser name and version

Firefox Android 122.1.0, Chrome Android (latest), but reproducible in any browser when using touch gestures or touch emulation

### Operating system

Android, but reproducible on any OS with a browser that supports touch gestures or touch emulation

**Comment by ClearlyClaire** [comment]
Fixed by #2615
