### ISSUE TITLE
"Modern ES syntax" brakes Web UI in some browsers

### ISSUE THREAD

**Issue by louis77** [glitch-soc/mastodon#2671]
### Steps to reproduce the problem

Two weeks ago https://github.com/glitch-soc/mastodon/commits?author=renchap introduced "modern ES" syntax in some of the JS files. Specifically this commit:

https://github.com/glitch-soc/mastodon/commit/899eac1a92c802c334606a49d538ef37bd47c91a

Ever since, the Web UI is completely broken in some browsers due to JS errors, i.e. in qutebrowser, that do not support Object.hasOwn() etc. The Chromium engine used by Qutebrowser even in the Ubuntu 22 LTS still doesn't support this and I do not see any need why this syntax was introduced (it literally has no advantage).

```
emoji_utils.js:138 Uncaught TypeError: Object.hasOwn is not a function
    at y (emoji_utils.js:138)
    at v (emoji_utils.js:121)
    at Object.<anonymous> (emoji_mart_search_light.js:28)
    at s (bootstrap:84)
    at Object.<anonymous> (home-674e841a5f6b2f202dac.chunk.js:2)
    at s (bootstrap:84)
    at Object.<anonymous> (store.js:1)
    at s (bootstrap:84)
    at Module.<anonymous> (home-674e841a5f6b2f202dac.chunk.js:2)
    at s (bootstrap:84)
```

My recommendation is to revert this commit and make the code compatible again with older browsers, which many of our users need to use.

### Expected behaviour

Don't use ES syntax incompatible with older browsers

### Actual behaviour

The Web UI doesn't work anymore

### Mastodon instance

emacs.ch

### Mastodon version

4.3.0-alpha.3+glitch

### Browser name and version

Qutebrowser v2.5.4

### Operating system

Ubuntu 22.04 LTS

**Comment by ClearlyClaire** [comment]
Hi! If `Object.hasOwn` is causing problems for you, it should have already been causing issues for a very long while, as it's been used in the notifications code.

> My recommendation is to revert this commit and make the code compatible again with older browsers, which many of our users need to use.

There is an alternative to reverting this commit, it's changing the configuration in `.browserslistrc` to cover older browsers, which would cause the appropriate polyfills to be loaded. In any case, I do not want to deviate from upstream here, as this would cause a significant increase in maintenance burden.

Another concern for old browsers is whether they include security fixes.

**Comment by louis77** [comment]
Thank you for your reply. To clarify: I'm talking on behalf of a community of users [of our instance], not just for me. And the notifications code was probably broken for while and no one noticed, but when the whole Web UI appears blank and users are unable to interact with the instance, that's a different level and this is what caused me to open this issue.

However, I realized in the meanwhile that this is a decision made by upstream and I'll place my concerns there, which is why I'll close this issue for now. Thank you for the valuable hint about `.browserslistrc`, I'll give that a try.

**Comment by wyatt8740** [comment]
@clearlyclaire

> Hi! If `Object.hasOwn` is causing problems for you, it should have already been causing issues for a very long while, as it's been used in the notifications code.
> 
> > My recommendation is to revert this commit and make the code compatible again with older browsers, which many of our users need to use.
> 
> There is an alternative to reverting this commit, it's changing the configuration in `.browserslistrc` to cover older browsers, which would cause the appropriate polyfills to be loaded. In any case, I do not want to deviate from upstream here, as this would cause a significant increase in maintenance burden.
> 
> Another concern for old browsers is whether they include security fixes.

It's worth noting that current Seamonkey (released January of this year) broke with this change. https://www.seamonkey-project.org/ - and seamonkey does get security backports.
Notifications already didn't work before, but now **the entire page** is just a blank screen and completely unusable.

What kinds of configuration changes would I need to ask my host to make to support Seamonkey and other browsers?

**Comment by ClearlyClaire** [comment]
How to configure `.browserslistrc` is described here: https://browsersl.ist/#

My understanding is that the latest SeaMonkey version (2.53.18.1) is based on Firefox 60.8 ESR (which is nearly 5 years old and I don't think is supported anymore). So you'd need to add `firefox 60` to `.browserslist.rc`.
