### ISSUE TITLE
bin/rails db:encryption:init is not doing anything

### ISSUE THREAD

**Issue by tamazonx** [glitch-soc/mastodon#2705]
### Steps to reproduce the problem

In process of updating to the latest build. I've updated Yarn and Ruby, readded redux.
_HEAD is now at e9cca1cc0 Merge pull request #2701 from ClearlyClaire/glitch-soc/merge-upstream_

I get to _RAILS_ENV=production SKIP_POST_DEPLOYMENT_MIGRATIONS=true bundle exec rails db:migrate_ and receive the following message

`I, [2024-05-06T20:47:12.179316 #4067383]  INFO -- : [dotenv] Loaded .env.production

Mastodon now requires that these variables are set:

  - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
  - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
  - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY

Run `bin/rails db:encryption:init` to generate values and then assign the environment variables.`

Well, I've run the command from the "live" directory and it just repeats the exact same message. When I check my .env.production, those variables have not been added.

![Screenshot_969](https://github.com/glitch-soc/mastodon/assets/97646922/44d90779-bd5a-429b-a858-163279b496fe)

### Expected behaviour

Variables should have been added to .env.production and seeded

### Actual behaviour

Variables were not added. Same exact message is given.

### Mastodon instance

indiepocalypse.social

### Mastodon version

v4.3.0-alpha.3+glitch

### Technical details

- ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-linux]
- Node.js v20.12.1

**Comment by tamazonx** [comment]
Sorry, found the fix -- not sure if this was my fault.
I added the 3 variables with no value to my .env.production, then ran the command and it gave me values to put in.

**Comment by RokkuCode** [comment]
To document this properly for those who are running in this wall:
- add the 3 strings to your .env.production like this (add them to the bottom of the file):
  ```
ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=
ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=
ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=
  ```
- run within your "live" directory the following command `RAILS_ENV=production bundle exec rails db:encryption:init`
- you get 3 strings with the variable names and values for the keys
- copy this 3 strings, open the .env.production and replace them with the string you have added before
