### ISSUE TITLE
Two-factor auth code page missing styling

### ISSUE THREAD

**Issue by yipdw** [glitch-soc/mastodon#271]
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by beatrix-bitrot** [comment]
i thought we fixed this???

**Comment by yipdw** [comment]
I think there must be a `before_action` that's being skipped on two-factor auth pages.  The page that prompts for a code is missing styling, as is e.g. https://dev.glitch.social/settings/two_factor_authentication/confirmation/new.

**Comment by beatrix-bitrot** [comment]
my bad, i was thinking of the oauth applications page i think

**Comment by beatrix-bitrot** [comment]
@yipdw cf #262

**Comment by yipdw** [comment]
In https://github.com/glitch-soc/mastodon/blob/master/app/controllers/auth/sessions_controller.rb, it looks like this is the sequence of events:

1. `set_pack` is the last action in the action chain
2. `authenticate_with_two_factor` is prepended to the whole chain
3. if `two_factor_enabled?` and a valid password is supplied, then `authenticate_with_two_factor` executes `prompt_for_two_factor`
4. `prompt_for_two_factor` renders `two_factor`, but this is run before `set_pack` has had a chance to run

**Comment by yipdw** [comment]
`Settings::TwoFactorAuthentication::{Confirmations,RecoveryCodes}Controller` are also both missing a `set_pack` action.  It looks like we can modify them to inherit `Settings::BaseController` and pick up an appropriate pack that way.
