### ISSUE TITLE
2a34c9a01e broke my instance

### ISSUE THREAD

**Issue by tamazonx** [glitch-soc/mastodon#2722]
### Steps to reproduce the problem

I ran updates and restarted mastodon-web and all sidekiq processes like usual, and now the web interface gives me the "We're sorry, but something went wrong on our end" elephant. Android clients aren't refreshing, instead giving me Error 500.

Checking nginx's error.og I see loads of:
connect() failed (111: Connection refused) while connecting to upstream

I do not use Docker. I'm running this on Ubuntu Server.

### Expected behaviour

Update

### Actual behaviour

Borked

### Mastodon instance

indiepocalypse.social

### Mastodon version

v4.3.0-alpha.4+glitch

### Browser name and version

Firefox 126.0.1

### Operating system

Windows 11

### Technical details

"):
May 30 15:52:40 indiepocalypse-social bundle[21714]: [02f07c5b-2edc-42ae-a423-69e4a53de559]
May 30 15:52:40 indiepocalypse-social bundle[21714]: [02f07c5b-2edc-42ae-a423-69e4a53de559] lib/action_dispatch/remote_ip_extensions.rb:49:in `calculate_ip'
May 30 15:52:40 indiepocalypse-social bundle[21714]: [02f07c5b-2edc-42ae-a423-69e4a53de559] config/initializers/rack_attack.rb:17:in `remote_ip'
May 30 15:52:40 indiepocalypse-social bundle[21714]: [02f07c5b-2edc-42ae-a423-69e4a53de559] config/initializers/rack_attack.rb:66:in `block in <class:Attack>'
May 30 15:52:40 indiepocalypse-social bundle[21714]: [02f07c5b-2edc-42ae-a423-69e4a53de559] lib/public_file_server_middleware.rb:18:in `call'
May 30 15:52:41 indiepocalypse-social bundle[21714]: F, [2024-05-30T15:52:41.017625 #21714] FATAL -- : [c1ee52fa-d434-4887-bacf-a896ea348282]
May 30 15:52:41 indiepocalypse-social bundle[21714]: [c1ee52fa-d434-4887-bacf-a896ea348282] ActionDispatch::RemoteIp::IpSpoofAttackError (IP spoofing attack?! client 127.0.0.1 is not a trusted proxy HTTP_CLIENT_IP=

**Comment by ClearlyClaire** [comment]
Please make sure your reverse-proxy (or reverse proxies) are set as trusted. If all your reverse-proxies connect to each other and Mastodon using local network addresses, you can unset `TRUSTED_PROXY_IP`. Otherwise, please make sure each reverse-proxy is listed in `TRUSTED_PROXY_IP`, even if they use local network addresses.

**Comment by tamazonx** [comment]
Oh thank you, thank you thank you. Adding localhost to TRUSTED_PROXY_IP got us back up. You're a miracle worker!
