### ISSUE TITLE
Notifications broken after updating from nightly.2024-03-28 to nightly.2024-06-08

### ISSUE THREAD

**Issue by asyncmeow** [glitch-soc/mastodon#2734]
### Steps to reproduce the problem

1. Have an instance running in docker, using `nightly.2024-03-28`
2. Upgrade to `nightly.2024-06-08` (setting activerecord encryption settings in the process)
3. Have someone like a post to test notifications

### Expected behaviour

A notification should appear in my notification feed

### Actual behaviour

No new notifications have showed up after upgrading

### Mastodon instance

fedi.rrr.sh

### Mastodon version

v4.3.0-nightly.2024-06-08+glitch

### Technical details

Using docker images:
- redis: `redis:7-alpine`
- elasticsearch: `docker.elastic.co/elasticsearch/elasticsearch:7.17.4`
- mastodon-web: `ghcr.io/glitch-soc/mastodon:nightly.2024-06-08`
- mastodon-streaming: `ghcr.io/glitch-soc/mastodon-streaming:nightly.2024-06-08`
- sidekiq: `ghcr.io/glitch-soc/mastodon:nightly.2024-06-08`

**Comment by ClearlyClaire** [comment]
Hi!

Do the notifications appear on refresh? Do you have any error in the sidekiq logs? Did you perhaps forget to run database migrations?

**Comment by asyncmeow** [comment]
Restarted my instance and it seems to have resolved itself... Not sure what the cause was tbh? On Jun 9, 2024 06:03, Claire ***@***.***> wrote:
Hi!
Do the notifications appear on refresh? Do you have any error in the sidekiq logs? Did you perhaps forget to run database migrations?

**Comment by ClearlyClaire** [comment]
> Restarted my instance and it seems to have resolved itself... Not sure what the cause was tbh?

I'd say a missing migration (restarting the services before running the migrations, and not after), but hard to say for sure (looking at the logs should help).

In any case, closing as the issue has been resolved!
