### ISSUE TITLE
Why is this post being filtered?

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#2766]
### Steps to reproduce the problem

This post: 

![Screenshot 2024-07-05 at 00 47 48](https://github.com/glitch-soc/mastodon/assets/6607512/f08db75a-52da-4afb-85bb-29d06507aabd)
URL: https://mastodonapp.uk/@ukelections/112730245513364643

... is being filtered for me as the filter word set "USA":

![Screenshot 2024-07-05 at 00 49 00](https://github.com/glitch-soc/mastodon/assets/6607512/897a2fbc-b53a-4b5a-b279-fd4eecbc038c)

But this is my list of words to filter:

- Jan6
- Jan 6
- Jan. 6
- #blackfriday
- #firstammendment
- #Indiana
- #JoeBiden
- #LasVegas
- #UCLA
- % of Americans
- 14th amendment
- 4th july
- 4th of july
- Alabama
- American conservatives
- American cops
- american democracy
- american politics
- Arizona
- at&t
- baltimore
- Bible Belt
- biden
- Bill of Rights
- black americans
- black friday
- california
- chicago
- Clarence Thomas
- Columbia
- Confederates
- congress
- congressional
- corporate america
- democrats
- DeSantis
- electoral college
- Elizabeth Warren
- FCC
- federal funding
- federal income
- first amendment
- florida
- FTC
- George Santos
- GOP
- hawai'i
- hawaii
- Hoboken
- homeland security
- idaho
- in America
- independence day
- indiana
- ivy league
- Joe Lieberman
- kansas
- kari lake
- kevin roberts
- Las Vegas
- los angeles
- Louisiana
- massachusetts
- Matt Gaetz
- medicare
- Memorial Day
- michigan
- middle school
- Mike Johnson
- million Americans
- Minnesota
- miranda rights
- Mitch McConnell
- montana
- murica
- Nashville
- nbc news
- nevada
- new york
- Nikki Haley
- North Carolina
- NYC
- NYPD
- Oakland
- ohio
- oklahoma
- oregon
- planned parenthood
- portland
- presidential candidate
- Reaganomics
- red states
- Rudy Giuliani
- san diego
- san francisco
- seattle
- South Carolina
- St. Louis
- State Department
- State Dept
- state of the union
- strip mall
- super bowl
- superbowl
- Tallahassee
- tax dollars
- Ted Cruz
- tennessee
- texan
- texas
- thanksgiving
- the American people
- the average american
- the CIA
- the FDA
- The IRS
- the most american
- the u.s.
- The United States
- the US
- the US Govt
- the usa
- the white house
- Trader Joe
- tucker carlson
- Tucson
- U.S. border patrol
- US Air Force
- US border patrol
- US colonialism
- US pol
- us senate
- US taxpayers
- uspol
- Utah
- Wall Street
- washington
- West Virginia
- white americans
- whitehouse
- Wisconsin
- your senators

I have read through it all so carefully and I cannot work out why it is being filtered based on the post and the filter words list.

The post was posted on 4th July about a big 4th July event in the UK, so I wondered if somehow it might be connected, but also, so many other posts were posted on 4th July that aren't being filtered, so I don't think that can be it!

### Expected behaviour

Post not filtered as "USA"

### Actual behaviour

Post filtered as "USA"

### Mastodon instance

eldritch.cafe

### Mastodon version

v4.3.0-alpha.5+glitch

### Browser name and version

Chrome Version 126.0.6478.127 (Official Build) (arm64)

### Operating system

macOS Sonoma 14.5 (23F79)

**Comment by Fl1pp3d0ff** [comment]
I object to the fact that you failed to capitolize "Michigan" in your list...

Seriously, though, it's being filtered for two terms: USA and Politics. What are the hashtags on the original post?

**Comment by Fl1pp3d0ff** [comment]
Also.. "Liberal Democrats" in that toot is most likely causing the issue, as you have "democrats" on your list.

This is a Layer 8 issue.

**Comment by Cassolotl** [comment]
Oh yes! Thank you. :) I figured it was a word that my brain was skipping over for some reason, but I checked the list so many times that I was doubting myself.

(I don't know what a Layer 8 issue is.)

**Comment by Fl1pp3d0ff** [comment]
Layer 7 is the user interface, so, layer 8 is the user. 🤣😜

It's something some devs/support personnel say when it's not a bug but looks like a bug to the users (and the devs). 

I'll be honest, I looked at it for a good 20+ minutes before it dawned on me.

**Comment by Cassolotl** [comment]
Thank you for scouring the list so carefully too!

**Comment by Fl1pp3d0ff** [comment]
Not a problem at all.

I'm just glad it's not a bug, and that the solution was found before the
folks who do write and maintain Mastodon's code spent a bunch of
person-hours on it.

I'm still a bit disappointed that Michigan isn't capitalized, but it's also
not my list. ;)

Enjoy your week.

-----BEGIN GEEK CODE BLOCK-----
Version: 3.1
GCS/CM/CC/E/IT/TW d-@ s+:+ !a C++$@ UBLVSCX*++++(on)$>$ P++>$ L+++$ E+@
W++>$ N+++ o+@ K+++ w@ O+@ M-@ V@>$ PS+@ PE@ Y+ PGP++ t+ 5+ X++ R@* tv++
b+>$ DI++ D+ G++ e h r+++ y+++
------END GEEK CODE BLOCK------
