### ISSUE TITLE
Duplicate key "orderedItems" in outbox.json when exporting a user's archive

### ISSUE THREAD

**Issue by dvorakroth** [glitch-soc/mastodon#2787]
### Steps to reproduce the problem

1. Export a user's archive
2. Download & extract the archive
3. Look at outbox.json
4. There's two `"orderedItems"` keys!

<img width="288" alt="Screenshot 2024-07-20 at 17 13 41" src="https://github.com/user-attachments/assets/7e57ef80-d0e7-40c2-9b5c-b0aee9c7ac89">

### Expected behaviour

There should only be one "orderedItems" key

### Actual behaviour

There were two "orderedItems" keys, one of which was a blank array

### Mastodon version

v4.3.0-alpha.5+glitch

**Comment by ClearlyClaire** [comment]
Hi! This issue is shared with upstream, do you mind reporting it there?

**Comment by dvorakroth** [comment]
sure, no problem!
