### ISSUE TITLE
"Enable collapsed toots" is off but toots are still collapsed often on mobile

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#284]
My settings:

![screen shot 2017-12-26 at 07 16 41](https://user-images.githubusercontent.com/6607512/34350020-b43d3d8c-ea0c-11e7-90a7-3ec34a202350.png)

My phone:

![photo_2017-12-26_07-17-46](https://user-images.githubusercontent.com/6607512/34350050-d9f4babe-ea0c-11e7-8289-fd5b644358a8.jpg)

And I can't find anything like settings or the Getting Started menu on my phone! (Android, Chrome-like browser I think?)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by beatrix-bitrot** [comment]
you can scroll the row of buttons to get to your getting started one, it got pushed off the edge it seems :/

about the collapse setting thing though that's definitely not right. 

which browser/OS is this?

**Comment by Cassolotl** [comment]
Android 8.1.0, "[Free Adblock Browser](https://play.google.com/store/apps/details?id=com.hsv.freeadblockerbrowser&hl=en_GB)".

Also I had no idea you could scroll the row of buttons! :o Thanks!

**Comment by Cassolotl** [comment]
Okay so I just checked my settings on the mobile site, and are the settings per device? Because on my phone the settings were set to "collapsed toots: on", but it's different on my laptop, and being told that the buttons at the top are scrollable might actually have just solved everything.

**Comment by beatrix-bitrot** [comment]
the settings ARE per device. they are stored in the localstorage of the browser

**Comment by Cassolotl** [comment]
So okay, I'm gonna close this because it wasn't a bug, it was just me not knowing that settings were per device and also not knowing that the settings icon needed to be scrolled to. 😳
