### ISSUE TITLE
20180831171112_create_bookmarks.rb repeated at each startup

### ISSUE THREAD

**Issue by lonestaritaly** [glitch-soc/mastodon#2863]
### Steps to reproduce the problem

1. starting the mastodon docker instance (linuxserver/docker-mastodon:glitch)

### Expected behaviour

No errors and all migrations being performed

### Actual behaviour

20180831171112_create_bookmarks.rb fails with "already exists" errors

### Detailed description

At start up of the instance: 

```
───────────────────────────────────────

Linuxserver.io version: 88756ab7-ls236

Build-date: 2024-10-03T10:51:39+00:00

───────────────────────────────────────

    

using keys found in /config/keys

I, [2024-10-05T19:15:30.201378 #192]  INFO -- : Migrating to CreateBookmarks (20180831171112)

== 20180831171112 CreateBookmarks: migrating ==================================

[strong_migrations] DANGER: No lock timeout set

-- create_table(:bookmarks)

bin/rails aborted!

StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

PG::DuplicateTable: ERROR:  relation "bookmarks" already exists

/app/www/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:55:in `exec'

/app/www/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:55:in `block (2 levels) in raw_execute'
```

the migration has been already performed and the relations already exist. Because of the migration failing, all other following migrations are not performed.

I saw there's a script 0_duplicate_migrations.rb that is supposed to take care of this duplication but it doesn't seem to work? or it's an issue due to how LinuxServer people start the instance in their docker container?

### Mastodon instance

m.hirad.it

### Mastodon version

v4.3.0-rc1+glitch

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: v3.3.3 (2024-06-12 revision f1c7b6f435) [x86_64-linux-musl]
- Node.js version: v20.15.1

**Comment by ClearlyClaire** [comment]
Hm, I don't know this docker image (btw, Docker images are available at <https://github.com/glitch-soc/mastodon/pkgs/container/mastodon> and <https://github.com/glitch-soc/mastodon/pkgs/container/mastodon-streaming>), so I'm not sure if they do anything that could interfere with the double migration situation.

As you said, there is some code supposed to deduplicate them, and it should work. But it's code monkey-patching Rails' internals so it is brittle and may brake with updates—maybe it *is* currently broken.

I will try to come up with a more robust way to avoid these duplicate migrations.
