### ISSUE TITLE
Docker Image Tags

### ISSUE THREAD

**Issue by ThaMunsta** [glitch-soc/mastodon#2876]
### Pitch

I noticed git actions for "mastodon" stopped adding the latest tag in prebuilt images since [nightly.2024-09-18-security](https://github.com/orgs/glitch-soc/packages/container/mastodon/275165111?tag=nightly.2024-09-18-security) but git actions still adds it to mastodon-streaming images. Can we establish some use cases for the different tags? `nightly/edge` is self explanatory - and even `v4.3.0` makes sense if someone wanted to stay locked to just that release. `v4.3` maybe for people who only want stable builds - 4.3.1 and onward; and `latest` is stable but includes security patches? I'm probably oversimplifying but should someone update the compose scripts to target the now released `v4.3` tag if they want stable 4.3 updates without riskier nightly builds? If this wasn't intentional sorry for the feature request. :)

### Motivation

I just want to make sure how I have docker setup aligns with the intentions of the prebuilt images and tags.

**Comment by ClearlyClaire** [comment]
`latest` is supposed to be the latest stable release, but there's a discrepancy/bug here that we share with upstream.

Targeting `latest` however might not be advisable, as there is no guarantee that upgrading from one release to the next is possible without manual operation (for a start, migrations are almost always required, but there might be other non-generic steps involved)
