### ISSUE TITLE
Something's up with the layout on mobile?

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#289]
This weird bar on the right that follows you between swipes on dev.glitch.social:

![screenshot_20171230-030225](https://user-images.githubusercontent.com/6607512/34450882-899d4fea-ed0e-11e7-8e2d-84353a91d200.png)

![screenshot_20171230-030232](https://user-images.githubusercontent.com/6607512/34450884-8f51e8f6-ed0e-11e7-8c15-55725fd0da0f.png)

My settings:

![screenshot_20171230-030758](https://user-images.githubusercontent.com/6607512/34450892-c515fb58-ed0e-11e7-8088-5f841d89c695.png)

It's a Chrome-ish browser on Android, "Free Adblock Browser" - Android 8.1.0.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by beatrix-bitrot** [comment]
ye i get this on my phone too

**Comment by m4sk1n** [comment]
![screenshot_20180103-153422](https://user-images.githubusercontent.com/21127288/34524438-cfd2cf5e-f09b-11e7-8e8e-a3e2db394336.png)
Fixed? Brave on 7.1

**Comment by Cassolotl** [comment]
It's not fixed on mine, sadly!

**Comment by beatrix-bitrot** [comment]
interesting. doesn't seem fixed for me in mobile chrome...

**Comment by ThibG** [comment]
Is it still occurring? I cannot reproduce it (on Firefox)

**Comment by ThibG** [comment]
I think this is fixed? Please reopen if it isn't!
