### ISSUE TITLE
Emoji hovering causes clipping issues in profile bios.

### ISSUE THREAD

**Issue by AnalogFeelings** [glitch-soc/mastodon#2914]
### Steps to reproduce the problem

1. Open your profile bio.
2. Add an emoji to the start of a line.
3. Save, and hover over it.
4. Observe the clipping.

### Expected behaviour

The emoji should not be clipped by the parent element.

### Actual behaviour

The emoji is being clipped by the parent element.

### Detailed description

<img width="101" alt="image" src="https://github.com/user-attachments/assets/f46a5e13-51c0-42f9-90a6-b04acbbd467a" />

### Mastodon instance

tech.lgbt

### Mastodon version

v4.4.0-alpha.1+glitch

### Browser name and version

Microsoft Edge 131.0.2903.86

### Operating system

macOS 14.7.1

**Comment by ClearlyClaire** [comment]
Enlarging emojis on hover is not a glitch-soc feature.
