### ISSUE TITLE
"Moved" status for someone on another instance is not updating

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#292]
So yesterday I removed the "I've moved to dev.glitch.social" notice on my cybre.space account, so that I could test something else.

Today, after several reloads and typing http://cybre.space/@cassolotl into the search box:

* The profile is still showing that I've moved to dev.glitch.social when I search the profile URL on ephemeral.glitch.social (incorrect 👎 )
* The profile shows no "I have moved" message when I search the profile URL on glitch.social (correct 🌟 )

So it looks like in some situations the move notice doesn't update in an I'm-no-longer-moved direction?

Edit: Let me know if this is just a general Mastodon thing, I can post it on the Big Main Issue List.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by beatrix-bitrot** [comment]
mmmmm glitch.social and ephemeral.glitch.social both run vanilla mastodon from the master branch so i think this is probably an upstream issue yes!

thank you for being so attentive and your effort in documenting these things as well @Cassolotl !

**Comment by Cassolotl** [comment]
That's okay, it's good to know it's useful and appreciated! :)

**Comment by yipdw** [comment]
tootsuite/mastodon#6140 is listed as fixed by commit d319b3dbe4cf40bfca12a224adb54a8fb6033090; that commit was merged into glitchsoc/mastodon by commit 933840bebf4ce8f5282c88e8c3e8c1b3675fbf2d.  Is this error still occurring on dev.glitch.social?

**Comment by Cassolotl** [comment]
The error was never tested on dev.glitch.social! It was only tested on ephemeral and glitch.social. Should I test on one of those?

**Comment by yipdw** [comment]
Yeah -- I think glitch.social is running 2.1.2, which should have the fix also.

**Comment by Cassolotl** [comment]
I tested it on ephemeral, which is where the bug originally happened, and it seems to be working fine now! :) That's on 2.1.1.
