### ISSUE TITLE
Get elephant friend in glitch flavour

### ISSUE THREAD

**Issue by yipdw** [glitch-soc/mastodon#294]
Vanilla flavour has elephant friend and a wave graphic in the compose column.  Glitch flavour should have that too.

(If we can turn elephant friend into _glitchy_ elephant friend at the same time, that'd be great)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ncls7615** [comment]
glitchy elephant friend picture was not png file
if you need new glitchy elephant friend picture, i can make new one 👍 (cuz im former motion designer)

**Comment by yipdw** [comment]
Yeah, I think that'd be great!

**Comment by ncls7615** [comment]
if we can use gif, i think this gif is not bad (imo)
glitch gif (keep alpha)
![mastodon_ui](https://user-images.githubusercontent.com/28977652/34653532-4bdbd54a-f430-11e7-88e5-92d796ba740c.gif)

**Comment by yipdw** [comment]
I like it, but I think people would be interested in a version that does not animate?

**Comment by beatrix-bitrot** [comment]
aaaaahhhh i like it a lot but i think it would be too distracting animating all the time... 😩

**Comment by ncls7615** [comment]
yea agree
I will make static version

**Comment by ncls7615** [comment]
glitch pictures

what do you think about these pictures?
if you want another pictures, i will make another one 👍

- mastodon-ui 1
![mastodon-ui 1](https://user-images.githubusercontent.com/28977652/34653647-4d4a4680-f432-11e7-8ff1-7c71d6215988.png)

- mastodon-ui 2
![mastodon-ui 2](https://user-images.githubusercontent.com/28977652/34653648-4f79c2aa-f432-11e7-916f-73d30f18c3c2.png)

- mastodon-ui 3
![mastodon-ui 3](https://user-images.githubusercontent.com/28977652/34653649-50b49488-f432-11e7-8e37-488e0ae061fc.png)

**Comment by beatrix-bitrot** [comment]
i like 1 the best but i guess we can wait a bit and see what others think :3

**Comment by ncls7615** [comment]
oki~ :3

**Comment by yipdw** [comment]
I'm inclined to use all three and randomize the selection at load-time...

**Comment by ncls7615** [comment]
thats cool idea

**Comment by beatrix-bitrot** [comment]
yeah i'm good with that

**Comment by yipdw** [comment]
I have a first attempt at this in 289aeb4406166e2687ff24cf1522c14066d42753.  There are three problems with it that I know of:

1. The background assignment occurs in rendering, not when the necessary component data is computed.  This is because I don't yet understand React architecture enough to figure out where the right place is.  I need to do some reading.
2. In the above commit, elephant friend _replaces_ the drawer background.  The correct behavior is to overlay elephant friend on top of the wave graphic and solid-color background.  I may need to add more elements to make that work?
3. You can't shrink glitchy elephant friend into nothingness with a big enough compose box.  This is probably related to (2).

**Comment by marrus-sh** [comment]
You can layer multiple background images/colours/positions in css so you shouldn't need any more elements just for that, but if you want to do the shrinky stuff then you will (upstream uses a `<div class='mastodon' />` it looks like).

The right place for assigning the background would probably be the state; you can just do `state = { glitchyFriend: choices[Math.floor(Math.random() * choices.length)] }` under where you declare the props and then never update it ever. This will keep the glitchy friend for as long as the component is mounted but create a new one every time the component is remounted (which will happen on mobile).

If you want the glitchfriend to be static across mounts, then the right place would be in the redux store, probably in `reducers/compose.js`—determine the image in the initial state and then just read that in via `mapStateToProps`.

**Comment by marrus-sh** [comment]
(as an aside, it would be cool if clicking on the elephant switched it to the next glitchfriend. so maybe have

```js
//  actions/compose.js
const COMPOSE_GLITCHFRIEND_CYCLE = 'COMPOSE GLITCHFRIEND_CYCLE';
//  …
//  I forget how we format our action creators but it's something like this…
export const cycleGlitchfriendCompose = () => { type: COMPOSE_GLITCHFRIEND_CYCLE };
```

```js
//  reducers/compose.js
const initialState = ImmutableMap({
  //  …
  glitch_friend: Math.floor(Math.random() * 3),
  // …
});
// …
const cycleFriend = state => state.set('glitch_friend', (state.get('glitch_friend') + 1) % 3);
// …
//  blah blah export function initial state blah
  case COMPOSE_GLITCHFRIEND_CYCLE:
    return cycleFriend(state);
```

… and then read in the number from `state.get(['compose', 'friend']);` and add a `onCycleFriend` which maps to `cycleGlitchfriendCompose`.)

**Comment by Siphonay** [comment]
I know glitch-soc is mainly made for glitch.social but my instance uses it and I don't really want a cycling elephant friend, I'd just like having a regular, unclickable one like on vanilla mastodon. I don't know if I'm alone in this 

I'm currently struggling to remove the code because I don't know much about JS

I'm not saying it should be entirely removed, but it would be nice to include a flavor that doesn't have it so people can make it the default one?

**Comment by yipdw** [comment]
You can remove the onclick handler by disabling the `onClick` action in `app/javascript/flavours/glitch/features/drawer/index.js`, line 114.  If you're familiar with applying diffs:

```diff
+diff --git a/app/javascript/flavours/glitch/features/drawer/index.js b/app/javascript/flavours/glitch/features/drawer/index.js
index 1679e9a4b..02756278f 100644
--- a/app/javascript/flavours/glitch/features/drawer/index.js
+++ b/app/javascript/flavours/glitch/features/drawer/index.js
@@ -111,7 +111,7 @@ class Drawer extends React.Component {
         <div className='contents'>
           <DrawerAccount account={account} />
           <Composer />
-          {multiColumn && <button className='mastodon' onClick={onClickElefriend} />}
+          {multiColumn && <button className='mastodon' />}
           <DrawerResults
             results={results}
             visible={submitted && !searchHidden}
```

**Comment by ThibG** [comment]
You could also do it using CSS only. Something like this should do the trick:
```css
.drawer > .contents > .mastodon {
  pointer-events: none;
  background: … !important;
  filter: none !important;
}
```

(untested, but it should work)
