### ISSUE TITLE
character limit config is does not work

### ISSUE THREAD

**Issue by ncls7615** [glitch-soc/mastodon#297]
<img width="239" alt="2018-01-06 17 33 53" src="https://user-images.githubusercontent.com/28977652/34638085-f6467fbe-f307-11e7-8884-7c1b85627cbd.png">
<img width="397" alt="2018-01-06 17 35 03" src="https://user-images.githubusercontent.com/28977652/34638087-f840d4b8-f307-11e7-9fda-b5f6cdced0e3.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yipdw** [comment]
Commit 2eed4ace1147d08d29bf9fdd9692afb2871e1fd9 seems to fix this on my development environment; please re-open this issue if you encounter further problems with the character limit.

**Comment by ncls7615** [comment]
okay thanks
