### ISSUE TITLE
search popout is broken

### ISSUE THREAD

**Issue by ncls7615** [glitch-soc/mastodon#298]
<img width="302" alt="2018-01-06 17 36 42" src="https://user-images.githubusercontent.com/28977652/34638110-6ffd0c06-f308-11e7-802a-f85c5dc36092.png">
<img width="404" alt="2018-01-06 17 36 58" src="https://user-images.githubusercontent.com/28977652/34638111-71ea442a-f308-11e7-8a34-c9a5e0d01266.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yipdw** [comment]
Looks like there's a selector in `styles/components/index.scss` named `.search-popout`, but the search box now has class `drawer--search--popout`.  Maybe we just need to fix the scss?

**Comment by ncls7615** [comment]
yea
<img width="438" alt="2018-01-06 21 04 49" src="https://user-images.githubusercontent.com/28977652/34639564-51293936-f325-11e7-82e6-45683a9a2a3e.png">

**Comment by yipdw** [comment]
Fixed in #302.

**Comment by ncls7615** [comment]
yea
