### ISSUE TITLE
search cancel button does not work

### ISSUE THREAD

**Issue by ncls7615** [glitch-soc/mastodon#299]
<img width="303" alt="2018-01-06 17 39 33" src="https://user-images.githubusercontent.com/28977652/34638129-cad22a1c-f308-11e7-8240-f7a2012f4b33.png">
<img width="402" alt="2018-01-06 17 39 53" src="https://user-images.githubusercontent.com/28977652/34638130-cd674c30-f308-11e7-9536-4bd189976af8.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by marrus-sh** [comment]
This should be fixed by b5874c1428d9445921db242b248798adbf7b4b9d—let me know if it still has problems. Thanks for letting us know~

**Comment by ncls7615** [comment]
thanks
