### ISSUE TITLE
When language is set to English, the Mastodon flavour page contains Polish text

### ISSUE THREAD

**Issue by yipdw** [glitch-soc/mastodon#300]
To reproduce issue:

1. Set interface language to English on any recent glitchsoc deployment (development environments work, as does dev.glitch.social as of 2018-01-06T09:15:00Z)
2. Go to Preferences > Flavours > Mastodon Vanilla
3. Observe the interface text

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by beatrix-bitrot** [comment]
should be fixed in https://github.com/glitch-soc/mastodon/commit/61ef8d643e8015361a95dbb9b9fd1440f7086bb4

**Comment by yipdw** [comment]
Looks good to me.
