### ISSUE TITLE
toot send shortcut (ctrl + return) does not work

### ISSUE THREAD

**Issue by ncls7615** [glitch-soc/mastodon#301]
toot send shortcut (ctrl + return) is does not work

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yipdw** [comment]
Seems to be fixed in 9f29fd31ba3cdeb2f4551a662c68905e9a1a9e33.
