### ISSUE TITLE
error page is broken

### ISSUE THREAD

**Issue by ncls7615** [glitch-soc/mastodon#305]
![2018-01-08 4 20 12](https://user-images.githubusercontent.com/28977652/34653158-3d282706-f42b-11e7-9255-6e5a7c813bb5.png)

https://dev.glitch.social/404

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yipdw** [comment]
I think 70c99a9f34b645baa65982dfec5351869c1924fe should fix this.

**Comment by ncls7615** [comment]
thanks!
that works for me~ 💕
