### ISSUE TITLE
list editor is broken

### ISSUE THREAD

**Issue by ncls7615** [glitch-soc/mastodon#307]
list editor is broken
<img width="393" alt="2018-01-08 19 26 33" src="https://user-images.githubusercontent.com/28977652/34666910-f5012b88-f4a9-11e7-86c7-6abd7fe0a63d.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yipdw** [comment]
It looks like the `.search__input` and `.search__icon` classes do not exist in the `glitch` stylesheets, and that they could be copied from `app/javascript/styles`.  The question I have is where we should put the copied styles: `app/javascript/flavours/glitch/styles/components/index.scss` maybe?

**Comment by ncls7615** [comment]
probably it's fixed
<img width="2672" alt="2018-01-09 2 38 09" src="https://user-images.githubusercontent.com/28977652/34683699-2cd2e68c-f4e6-11e7-8d28-5049d396d84a.png">

**Comment by yipdw** [comment]
Is that a local modification? I don't see any recent changes in glitch-soc/mastodon that could have fixed that...

**Comment by ncls7615** [comment]
yes its local modification
i will send pr

**Comment by yipdw** [comment]
#308 was deployed to dev.glitch.social and seems to be working; I think that means this error is fixed.
