### ISSUE TITLE
Muted users should not show up in mentions

### ISSUE THREAD

**Issue by yiskah** [glitch-soc/mastodon#31]
When I mute someone it's because I don't want them talking to me anymore, without having to go through the drama of them realizing I blocked them. It's an "assisted ignoring" in my mind. As a popular user, blocking people becomes An Ordeal and people often hassle me in private to ask why I blocked them and the only answer is "I found you annoying" which just isn't worth it. I want to be able to mute someone and that means they can see all my stuff fine but I don't see their posts *in my feeds* and if they @ me it doesn't show up in my notifications. 

* * * *

-  [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yiskah** [comment]
@beatrix-bitrot you said I should "assign" this to you which isn't a privilege I have so I'm tagging

**Comment by marrus-sh** [comment]
Can this be closed now that we have notification muting in upstream??

**Comment by ThibG** [comment]
I would think so. Closing. Please reopen if needed!
