### ISSUE TITLE
Check announcability of local-only statuses

### ISSUE THREAD

**Issue by yipdw** [glitch-soc/mastodon#315]
Commit 35b84985a8b9e57cfd3ffac8a0e3937d3c7a1167 modifies Mastodon to only announce public and unlisted statuses.  Local-only statuses should probably not be announcable.

Investigate the current state of local-only statuses with regard to this commit and make any changes necessary to keep local-only statuses, well, local-only.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by beatrix-bitrot** [comment]
I looked over this and i don't think it relates to distributing stuff to remote instances at all. I think if we put a check for local_only? in here it would prevent reblogs from being distributed to people on the local instance.

**Comment by ThibG** [comment]
`local_only?` statuses and boosts don't get pushed over ActivityPub (or OStatus) *but* boosts of `local_only?` statuses still get serialized for all formats (HTML, OStatus' Atom, ActivityStreams' json). For the latter, it only leaks the existence of the toot, but for the previous two it also serializes its contents.
I'll see what I can do to ensure local-only boosts remain strictly local-only.

**Comment by ThibG** [comment]
Closing this issue, as it's not actually one and fixed my PR.
As for the commit referenced in the issue, we never reach the point where ActivityPub objects are created for local-only toots.
