### ISSUE TITLE
Attempting to switch flavors raises ActionController::ParameterMissing

### ISSUE THREAD

**Issue by monsterpit-daggertooth** [glitch-soc/mastodon#317]
_(Discovered by [@una@monsterpit.net](https://monsterpit.net/@una/99322841904576372))_

As of commit 991371a, when switching flavors, a ``ActionController::ParameterMissing`` is raised in the console:

```
method=PUT path=/settings/flavours/glitch format=html controller=Settings::FlavoursController action=update status=400 error='ActionController::ParameterMissing: param is missing or the value is empty: user' duration=17.04 view=0.00 db=2.7
ActionController::ParameterMissing (param is missing or the value is empty: user):
  app/controllers/settings/flavours_controller.rb:30:in `user_settings_params'
  app/controllers/settings/flavours_controller.rb:19:in `update'
```

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by yipdw** [comment]
That's weird -- that commit didn't affect `Settings::FlavoursController` or associated view files.  I wonder if `simple_form_for` is rendering `current_user` incorrectly...

**Comment by yipdw** [comment]
Nope, turns out everything is still working as designed.  However, a design change altered an assumption.

The controller is expecting a `params` object of the form

```
{ user: { setting_flavour: "...", setting_skin: "..." } }
```

However, if `setting_skin` is not present (because there's only one skin), then the `user[setting_skin]` input field is not present.  This means that the `user` object will also not be present.

To get around this I think we should not use `params.require` -- that's meant to be used in situations where you absolutely will have a key, and omitting it is a client error.  But that's not our situation.

**Comment by yipdw** [comment]
Here's another possibility with fewer conditionals and keeping the use of `require`/`permit` (which offers nice parameter diagnostics):

```diff
diff --git a/app/controllers/settings/flavours_controller.rb b/app/controllers/settings/flavours_controller.rb
index 865d5a479..90843b1e5 100644
--- a/app/controllers/settings/flavours_controller.rb
+++ b/app/controllers/settings/flavours_controller.rb
@@ -27,7 +27,7 @@ class Settings::FlavoursController < Settings::BaseController
   end
 
   def user_settings_params(flavour)
-    params.require(:user).merge({ setting_flavour: flavour }).permit(
+    params.require(:user).permit(
       :setting_flavour,
       :setting_skin
     )
diff --git a/app/views/settings/flavours/show.html.haml b/app/views/settings/flavours/show.html.haml
index a5126d9c5..c79214755 100644
--- a/app/views/settings/flavours/show.html.haml
+++ b/app/views/settings/flavours/show.html.haml
@@ -12,6 +12,7 @@
 
   %hr/
 
+  = f.hidden_field :setting_flavour, value: @selected
   - if Themes.instance.skins_for(@selected).length > 1
     .fields-group
       = f.input :setting_skin, collection: Themes.instance.skins_for(@selected), label_method: lambda { |skin| I18n.t("skins.#{@selected}.#{skin}", default: skin) }, wrapper: :with_label, include_blank: false
diff --git a/config/routes.rb b/config/routes.rb
index f45684519..5d04c36bb 100644
--- a/config/routes.rb
+++ b/config/routes.rb
@@ -102,7 +102,7 @@ Rails.application.routes.draw do
       end
     end
 
-    resources :flavours, only: [:index, :show, :update], param: :flavour
+    resources :flavours, only: [:index, :show, :update]
 
     resource :delete, only: [:show, :destroy]
     resource :migration, only: [:show, :update]
```

Doing this guarantees that we will have a `user[...]` field in the view output (and hence the response).

**Comment by yipdw** [comment]
From https://monsterpit.net/@una/99322841904576372 (linked in the opening text) it looks like this problem is preventing someone from switching to the glitch flavour, so I'm going to merge it in :P  Please let me know if there's changes that should be made via code review comments.
