### ISSUE TITLE
notification 'badges'

### ISSUE THREAD

**Issue by hoodieak** [glitch-soc/mastodon#326]
badges, like this one for skype in my taskbar are a powerful feature for usability.. i dont have a quick example but discord does this too, in a browser, as does slack and i believe twitter as well, along with i'm sure many more apps i haven't used. that + the same sort of badge / mark to show Yes There Is New Things at the top of the column would go a LONG way toward making it more comfortable to use in a browser with multiple tabs

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by deevolutionism** [comment]
AFAIK `document.title` can be used to modify the title that appears in the browser tab. That could be modified to include the number of  notifications in parentheses.
The badge would be a simple as updating the favicon link to a badge that indicates notifications. I can dig into this further.

**Comment by ThibG** [comment]
This should be doable using https://www.npmjs.com/package/favico.js
However, there are quite a lot of issues with how Mastodon/glitch-soc counts unread notifications. I will try to fix that, and then look at how we could use a favicon badge.

**Comment by ThibG** [comment]
Fixed by #718
