### ISSUE TITLE
Disable full-width [Accessibility]

### ISSUE THREAD

**Issue by yiskah** [glitch-soc/mastodon#33]
I have stereoscopy problems and moving my eyes horizontally so much tires my eyes out and then I can't read for a while and also get a migraine. Please let me disable full-width

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by marrus-sh** [comment]
This is now a setting! (Implemented in 595c6de32c052f2a5e21307a0e43a6bd5d4b5c88)
