### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#341]
Could we please have a light theme? :) [Here is one](https://github.com/skiant/mastodon-light-theme)!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by marrus-sh** [comment]
I would love to have this as an option in app settings, I just haven't had the time to integrate it at that level. In the meantime we can probably get one in as a separate skin on the glitch and vanilla flavours; it might take a little bit of work to port over but it hopefully won't be too bad

**Comment by chriswmartin** [comment]
I made a light skin for scifi https://github.com/scififyi/mastodon/blob/glitchy/app/javascript/styles/scifi-light-glitch.scss and we can also take a look at Cybrespace's light theme which I think is a little more complete https://github.com/cybrespace/mastodon/blob/cybrespace/app/javascript/styles/light.scss

**Comment by pianycist** [comment]
Light themes with high contrast would be really helpful for blind or low-vision users!

**Comment by yipdw** [comment]
I think @MightyPork has a light-theme userstyle, but can't remember the link to it.  Even if it's not usable directly for your purposes, we can still run through screenshots of it to see if it's something we could roll in as a glitch flavour skin.

**Comment by chriswmartin** [comment]
The scififyi light skin was created by me, feel free to do whatever you'd like with it 👍

**Comment by ThibG** [comment]
A light theme has been added both for the glitch-soc and vanilla flavours.
Please open new issues if there are issues with it.

**Comment by Cassolotl** [comment]
THIS IS AWESOME
