### ISSUE TITLE
Asset CDN does not work

### ISSUE THREAD

**Issue by ghost** [glitch-soc/mastodon#345]
![error](https://user-images.githubusercontent.com/28977652/35260627-e477011e-004f-11e8-8321-36605cd71987.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yipdw** [comment]
A `Content-Security-Policy` header is hardcoded into `config/environments/production.rb`.  The quick fix is to comment it out, but I think we need to look into getting rid of it, especially since there are now multiple deployments of glitchsoc out there.

**Comment by yipdw** [comment]
cc @beatrix-bitrot since I think getting rid of that header would affect her deployment the most?

**Comment by ncls7615** [comment]
maybe fixed in this [commit](https://github.com/KnzkDev/mastodon/commit/0f2dcfe9446fd3dbeb9f0357d350bf3847e52f8e)

**Comment by yipdw** [comment]
Those changes seem mostly okay in general, though we'll have to see how it affects dev.glitch.social before merging it.

(The `X-Clacks-Overhead` header is present for sentimental reasons; that header would likely remain in glitchsoc if we decided to take this route.)

**Comment by ncls7615** [comment]
oh sorry
i removed X-Clacks-Overhead
but i think X-Clacks-Overhead is pretty important (?)
i pushed new [commit](https://github.com/KnzkDev/mastodon/commit/641e68324386b08d7a37c15064ded90a1d2a54c5)

**Comment by ThibG** [comment]
I think this is fixed, please reopen if that isn't the case.
