### ISSUE TITLE
Default skin not respected on non-web UI pages

### ISSUE THREAD

**Issue by vahnj** [glitch-soc/mastodon#355]
Default flavour/skin does not seem to be respected when there is no user logged in.

You can currently see this in awoo.space's front page especially: Jani is HUGE when logged out, and looks fine when logged in.

Preferably, I'd like for this behavior to rely on the default CSS always for these pages, as opposed to the user's chosen flavour when logged in so those pages have consistent behavior.

An alternative is perhaps a separate pathway that does not rely on any given theme, though I think the former suggestion is an easier solution.

Logged in using the correct skin:
![screen shot 2018-01-30 at 12 54 43 pm](https://user-images.githubusercontent.com/8795527/35591235-1999dcc2-05be-11e8-8998-a6d4409c620b.png)

Logged out (unsure what skin being used):
![screen shot 2018-01-30 at 1 00 39 pm](https://user-images.githubusercontent.com/8795527/35591238-1d07bd84-05be-11e8-9e3b-817936e107e3.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by beatrix-bitrot** [comment]
@marrus-sh please have a look at this when you have a moment

**Comment by marrus-sh** [comment]
yeah i was supposed to do this a long time ago but have been working on a big refactor and so haven't had time to look into it ;_;

it'll be coming soon, promise~

**Comment by ThibG** [comment]
I believe this has been fixed. Please reopen if that's not the case.
