### ISSUE TITLE
"Security verification failed" in Chrome on Android

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#356]
Hello! I'm using a Chrome-ish browser, so Chrome-ish that in "sessions" it's called "Chrome on Android". I did "add to homescreen" for dev.glitch.social. Today when I tapped the icon I got a login screen, and when I entered my details (correctly, I triple checked and even changed my password in the settings using my laptop and re-entered manually), I got this:

![screenshot_20180203-115304](https://user-images.githubusercontent.com/6607512/35766920-41364f0e-08d9-11e8-89aa-f3a605518c2f.png)

I haven't touched my cookie settings at all.

I tried ending the "Chrome on Android" session in settings via my laptop, and that didn't have any effect. I tried force-stopping it on my phone and tapping the icon on the homescreen again and that didn't have any effect.

Is there something I'm doing wrong in particular, a way to get around this?

Thanks!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
The exact same thing is happening with ephemeral.glitch.social, and I'm still getting notifications on my phone for Ephemeral even though I'm apparently not logged in!

**Comment by beatrix-bitrot** [comment]
That sounds like something that probably shouldn't be happening... But also seems like an upstream bug. I will ask Garg about it

**Comment by beatrix-bitrot** [comment]
i've updated a configuration thing on ephemeral @Cassolotl could you take another crack at it there and let me know how it goes?

**Comment by Cassolotl** [comment]
@beatrix-bitrot Just successfully logged in on Ephemeral! :)

**Comment by beatrix-bitrot** [comment]
@Cassolotl should be deployed now on dev.glitch.social as well

**Comment by Cassolotl** [comment]
@beatrix-bitrot Yup, it is working! Awesome, thank you very much. :)
