### ISSUE TITLE
Pawoo features

### ISSUE THREAD

**Issue by mkljczk** [glitch-soc/mastodon#359]
I think it would be nice to cherry-pick some features available on Pawoo.net (pixiv/mastodon) to glitch-soc/glitch front-end, like active users list, media timeline, better toot reporting, better search etc. License allows us to do it.

**Comment by yipdw** [comment]
Which one do you want to start with? 

The license certainly allows it, but pulling out and maintaining the change is a very different matter.  The pawoo codebase is quite different from both tootsuite and glitch-soc.  Some may be easy to port in; others might have quite a few dependencies.

**Comment by ncls7615** [comment]
> scheduled publishing

(probably) thats not scheduled publishing
i think you mean schedule delete feature
anyway, i agree with opinions of david
