### ISSUE TITLE
Image marker on CW posts hard to notice

### ISSUE THREAD

**Issue by dustine** [glitch-soc/mastodon#36]
When a toot is flagged with a CW and contains images, it's collapsed behind the Read More with an image marker, as follows:

![CW toot with a Read More collapsed, image marker on the top right](https://user-images.githubusercontent.com/8994495/27649007-59c60414-5c28-11e7-9172-92cb0868c38e.png)

While the presence of the marker is very important (and imo hiding CW images is as well), it may be easy to overlook as it blends into the toot's information and/or collapsing marker, and makes the user have to glance consciously to the top of toot to verify it's there or not.

A possible solution is borrowing the blue colour from the collapse marker, which can work as a subconscious context clue that there are hidden images in the CW toot, but I'm not entirely sure (colour blindness?).

![Same CW toot as before, but with the image marker now colored in deep sky blue](https://user-images.githubusercontent.com/8994495/27649152-dca58e90-5c28-11e7-9eee-805dd317e89a.png)
![Another CW toot with images, different marker indicating it's a multi picture toot](https://user-images.githubusercontent.com/8994495/27649233-0e079a5a-5c29-11e7-9667-5de49933c271.png)

Another possible solution is also putting the image marker inside the Show More.

![CW toot with the image marker inside the Show More clicker](https://user-images.githubusercontent.com/8994495/27649324-53c44804-5c29-11e7-8548-9ec344efb979.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by dustine** [comment]
May be relevant for #22 as this'd be yet another tweak.

**Comment by yiskah** [comment]
If you're concerned about color blindness you should use

http://webaim.org/resources/contrastchecker/

for color contrast checking and then apply a colorblind filter

https://www.toptal.com/designers/colorfilter

if you go through red-green and blue-yellow you've covered the two major kinds.

Putting the icon outside the show more button, before it or after it, is the ideal solution imo. It mimics the behavior of how that icon gets used when the image links is converted (or used to be converted? I think something broke that feature in 1.4.x) It's also very noticeable as its right there and high contrast.

**Comment by marrus-sh** [comment]
I agree that including the icon with the show more is an elegant solution, and it shouldn't be that hard to implement either~
