### ISSUE TITLE
The report pop-up is really hard to read!

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#364]
Here it is on dev.glitch.social (everything too pale):

![screen shot 2018-02-11 at 14 24 08](https://user-images.githubusercontent.com/6607512/36077874-e5503d9a-0f67-11e8-9a8a-d1864550b0e0.png)

Here it is on ephemeral.glitch.social (usernames too pale):

![screen shot 2018-02-11 at 20 12 58](https://user-images.githubusercontent.com/6607512/36077887-05c18764-0f68-11e8-9f60-4a4f478417fd.png)

Is this an instance-specific thing, or should I report it to the Big Github?

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
PS: don't block luluberlu, they are great

**Comment by Cassolotl** [comment]
I tried it on mastodon.social and it's the same over there, so I've put it on the Big Github. https://github.com/tootsuite/mastodon/issues/6466

**Comment by beatrix-bitrot** [comment]
thanks cas

**Comment by Cassolotl** [comment]
No worries. :) I should've done that in the first place, haha!
