### ISSUE TITLE
Search style issue

### ISSUE THREAD

**Issue by ghost** [glitch-soc/mastodon#366]
| Vanilla | Glitch |
|:-----------:|:------------:|
| <img width="304" alt="2018-02-14 15 03 01" src="https://user-images.githubusercontent.com/28977652/36189907-5b10c3a6-1198-11e8-8373-daf81ace2a7c.png"> | <img width="403" alt="2018-02-14 15 02 41" src="https://user-images.githubusercontent.com/28977652/36189914-62fd8022-1198-11e8-9496-4cd9f628663b.png"> |

Probably drawer is the cause.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by beatrix-bitrot** [comment]
@marrus-sh please take care of this when you have a chance! 🙇‍♀️
