### ISSUE TITLE
Three-dots menu exceeding page boundaries

### ISSUE THREAD

**Issue by Felthry** [glitch-soc/mastodon#367]
The three-dots menu goes outside the boundaries of the page if the toot on which it is clicked is near the bottom of the screen. See the imgur links below for an example.
before scrolling down: https://i.imgur.com/yjdxQa8.png
after scrolling down: https://i.imgur.com/wwkhybG.png

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by beatrix-bitrot** [comment]
this is very much an upstream issue and i honestly have no idea what to do about it 😅

**Comment by Felthry** [comment]
(Rosemary speaking): Well, it seems to me that having the three-dots menu appear above the button if it would go off-screen seems like a sensible way to fix it. That's how every operating system we're aware of does context menus, after all.

**Comment by ThibG** [comment]
I believe this was fixed a while ago. Please reopen if needed!
