### ISSUE TITLE
Error Pages Theming Point to Wrong Location

### ISSUE THREAD

**Issue by Reverite** [glitch-soc/mastodon#373]
https://github.com/glitch-soc/mastodon/blob/master/app/views/layouts/error.html.haml#L8-L9

Looks like these meant to point to `layouts/_theme` a la [app/views/layouts/_theme.html.haml](https://github.com/glitch-soc/mastodon/blob/master/app/views/layouts/_theme.html.haml)?

Right now, https://dev.glitch.social/assets/500.html doesn't seem to point to any CSS as a result, compared to Mastodon's: https://mastodon.social/assets/500.html

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
`layouts/_theme` is used but does nothing, as it relies on `@theme` and `@core` being set by Mastodon's `ApplicationController`'s `use_pack`.
The rake task doesn't use this, and I'm not too sure how best to fix that.
I'll come with a fix shorty, but it's going to be a bit hackish.
