### ISSUE TITLE
Add focal points support to the glitch flavor

### ISSUE THREAD

**Issue by MightyPork** [glitch-soc/mastodon#376]
Upstream PR https://github.com/tootsuite/mastodon/pull/6520

this consists of:
- integrating it into the compose component
- using this metadata in the media gallery component

**Comment by marrus-sh** [comment]
I've been noticing some bugs with the upstream implementation of this (particularly pertaining to GIFVs I think) so we might want to wait until release to make sure they get fixed (unless we're able to figure them out ourselves)

**Comment by ThibG** [comment]
Implemented (not sure about said bugs though)
