### ISSUE TITLE
The "do not auto-insert media URL into text" fix doesn't quite work

### ISSUE THREAD

**Issue by jpdeplaix** [glitch-soc/mastodon#381]
Since https://github.com/tootsuite/mastodon/pull/6672, Mastodon (and thus glitch-soc) is not supposed to display media URLs. However this doesn't work every time and I'm not sure what makes it work and what doesn't. My only guess right now is that it depends on users.
For instance with [this user](https://social.wxcafe.net/@wxcafe/media) it does work perfectly but with [this one](https://social.wxcafe.net/@jacquespa/media) it doesn't.

cc @wxcafe

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by yipdw** [comment]
tootsuite/mastodon#6672 does not actively hide media URLs as far as I can tell; instead, it does not generate them in the web frontend and relaxes some validation rules.

Some clients (e.g. Amaroq) do insert media URLs into statuses.  Is Mastalab (the client reported in some of the second person's toots) one of them?

**Comment by jpdeplaix** [comment]
Well I did some tests before opening this issue and the web frontend doesn't work either.

**Comment by yipdw** [comment]
If you encountered this on glitch-soc, were you using the vanilla or glitch flavour?  The frontend changes made to Mastodon haven't yet been integrated into the glitch flavour.

**Comment by jpdeplaix** [comment]
The glitch flavour but I just tried the vanilla one and it has the same behaviour.
Also it doesn't explain why it works with first user but not with the second. Both are from the same instance.

**Comment by marrus-sh** [comment]
#384 should bring us in line with what upstream has, so we're waiting on them if there are still any bugs, i think.

**Comment by jpdeplaix** [comment]
Ok I just tried using an other account on an other instance not using glitch-soc and it's the same thing :/ I'm going to open an issue (if there is not already one) on mainline Mastodon.
Thanks anyway !
