### ISSUE TITLE
"Show known fediverse on timeline preview" doesn't do anything

### ISSUE THREAD

**Issue by Siphonay** [glitch-soc/mastodon#382]
It seems like the feature that got implemented in the main Mastodon release doesn't work in glitch-soc. I've heard it has a similar feature before Mastodon did, but I didn't look into it because I didn't have a preview timeline enabled. Maybe those are conflicting?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yipdw** [comment]
The timeline components in the `glitch` flavour might not do anything with the `known_fediverse` settings tag.  I (or someone else) can look into this shortly.

**Comment by ThibG** [comment]
I think that's fixed? Can you reproduce this?

**Comment by Siphonay** [comment]
Can confirm that it is fixed

**Comment by ThibG** [comment]
Cool, closing then!
