### ISSUE TITLE
Fix upstream CW-dropping

### ISSUE THREAD

**Issue by marrus-sh** [glitch-soc/mastodon#395]
We stick media inside of CWs, so it is much more important that we fix this

https://github.com/tootsuite/mastodon/issues/6825

**Comment by nightpool** [comment]
yeah this has a completely different context with the way glitchsoc handles sensitive media so it doesn't make sense at all to use upstream's behavior here.

**Comment by yipdw** [comment]
It looks like this means backing out the `text   = options.delete(:spoiler_text) if ...` change done in `post_status_service.rb`, https://github.com/tootsuite/mastodon/commit/cfa9b6e13ab3c434f3901df6f614d0aa94a3d1ed.  Does this sound right?

**Comment by ThibG** [comment]
@yipdw that seems about right, but it's decided when authoring a toot, not when displaying it, so it would feel pretty inconsistent if glitch-issued toots were lacking a body and Mastodon-issued toots were lacking CWs.

**Comment by yipdw** [comment]
Hmm, I'm not sure how backing out that change would result in Mastodon-issued toots lacking CWs -- `PostStatusService` isn't involved in handling remote statuses, so any CWed toot coming in from a Mastodon instance would not be affected by this change.

**Comment by ThibG** [comment]
Yup, that's what I meant with my “but”. I would rather have Mastodon not drop the CW, and maybe use the same kind of hide-media-behind-spoilers behavior as glitch-soc to be honest.

**Comment by yipdw** [comment]
Ah, okay, thanks for the clarification.  I guess we can propose the glitch-soc system to tootsuite whilst applying the change discussed here?
