### ISSUE TITLE
Some admin panel features are broken

### ISSUE THREAD

**Issue by ThibG** [glitch-soc/mastodon#411]
Some (non-critical) admin panel features, such as hiding/showing all media at once from the statuses view, are broken.

This is because `admin.js` is not loaded, as `use_pack 'public'` overwrites `use_pack 'admin'` while both should be used.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by marrus-sh** [comment]
i'm actually not sure that `use_pack 'public'` *should* be loaded; possibly we need to import more things into the admin or common pack because `public` is only supposed to be loaded on static pages

**Comment by ThibG** [comment]
Hm, I don't really know, but tootsuite/mastodon does use it in the admin panel, which pulls the status representation from the static view.

**Comment by nightpool** [comment]
I can confirm that we definitely use public, because that's the bundle with
ujs in it and we need that for PUTing forms.

**Comment by marrus-sh** [comment]
ujs is a part of the common core: https://github.com/glitch-soc/mastodon/blob/master/app/javascript/core/common.js which is loaded on all non-`home` pages, it's not a part of `public`

**Comment by marrus-sh** [comment]
the things provided by `public` are:
- handling content warnings (this might need to be in `admin` as well for reports)
- handling the "open in web app" button (which probably isn't needed)

https://github.com/glitch-soc/mastodon/blob/master/app/javascript/core/public.js

**Comment by marrus-sh** [comment]
yeah so (sorry for posting this in three comments instead of one as i'm working through this) it looks like `public` was added in order to fix CWs, but copying https://github.com/glitch-soc/mastodon/blob/master/app/javascript/core/public.js#L13-L25 into `admin` is probably the better solution (or importing `core/public` into `core/admin` on the javascript side, either way)

**Comment by ThibG** [comment]
Closing this as those features are not present anymore in the new admin panel
