### ISSUE TITLE
Let users delete notifications

### ISSUE THREAD

**Issue by marrus-sh** [glitch-soc/mastodon#42]
I can't tell if this is just a failure on the part of the Mastodon frontend or if the API literally won't let you do this, but you should 100% be able to do this imo.

**Comment by MightyPork** [comment]
I think this works? If you're not talking about something other than 
![screenshot_20170706_213335](https://user-images.githubusercontent.com/2041118/27929336-cc5d0750-6292-11e7-843a-b7104dacdbee.png)
of course. Because I just clicked that and it worked fine.

**Comment by DJSundog** [comment]
Confirmed working on toot-lab running commit 0c7ee5c79208206dad6dcf9a34b10d2ec3e75f15

**Comment by ekiru** [comment]
it would be nice to be able to delete individual notifications., which may be what @marrus-sh has in mind.

**Comment by marrus-sh** [comment]
Yes deleting notifications individually is what I have in mind. There's an API for it unless I'm reading the docs wrong, but there isn't any means of doing this in the frontend as far as I can tell.
