### ISSUE TITLE
Video player is broken

### ISSUE THREAD

**Issue by imncls** [glitch-soc/mastodon#423]
Video position in the video player is broken.
It probably is a problem of CSS.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
Hm, indeed the size/position of the video seems to be dependent on the size of the viewport and not on the size of the container…
The video player has changed quite a bit in tootsuite/mastodon since it was forked in glitch-soc. I will try to backport those changes and see if that fix this issue.
