### ISSUE TITLE
Custom fields on profile don't show in glitch theme

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#452]
I'm on dev.glitch.social, and I went to Edit Profile to put my pronouns:

![screen shot 2018-05-01 at 20 20 31](https://user-images.githubusercontent.com/6607512/39489357-206bde04-4d7d-11e8-8ec5-ff135c45768a.png)

But it's not visible on my profile, even though other profile edits I've made are visible:

![screen shot 2018-05-01 at 20 20 16](https://user-images.githubusercontent.com/6607512/39489370-2b889f52-4d7d-11e8-92ab-ecc0bea4d9b3.png)

It also looks a little weird on my profile page:

![screen_shot_2018-05-01_at_20_21_19](https://user-images.githubusercontent.com/6607512/39489406-4fc9e0c4-4d7d-11e8-9845-5636c815db42.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by yipdw** [comment]
I think #449 is meant to address this?

**Comment by Cassolotl** [comment]
Oh that sounds good! I'll subscribe and close this when it is working. :) Thank you!

**Comment by MxFraud** [comment]
I wondered the same, I guess the issue can be closed since https://github.com/glitch-soc/mastodon/pull/449 has been merged.

**Comment by ThibG** [comment]
Indeed. Thanks for reminding me about this issue!
