### ISSUE TITLE
Glitch-soc uses old report dialog style?

### ISSUE THREAD

**Issue by riking** [glitch-soc/mastodon#473]
Screenshot taken on social.wxcafe.net at the version containing `"/packs/core/common-8c69dc83df4c68146806.js"`

![image](https://user-images.githubusercontent.com/627891/39842945-9835ce38-539d-11e8-9a78-14238f7725ee.png)

The report dialog contains white text on a white background.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by riking** [comment]
amended: apparently this is the old-and-busted report dialog

Screenshot of new dialog at mastodon.social

![image](https://user-images.githubusercontent.com/627891/39843129-8d0016f8-539e-11e8-8e66-0ca143f6f79a.png)

**Comment by ThibG** [comment]
This has been fixed a while ago, your instance's admin really should update someday!
