### ISSUE TITLE
Clipped toot privacy dropdown on desktop view

### ISSUE THREAD

**Issue by dustine** [glitch-soc/mastodon#49]
![toot posting where toot privacy dropdown is clipped inside the modal window](https://user-images.githubusercontent.com/8994495/27841686-6baa18be-60fb-11e7-9a66-8eede3102a18.png)

The toot privacy dropdown spawns inside the modal for creating the toots, forcing me to scroll down every time I want to pick something outside the default.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by MightyPork** [comment]
this should be closed, it's fixed
