### ISSUE TITLE
"Show confirmation dialog before favouriting" has no effect

### ISSUE THREAD

**Issue by kit-ty-kate** [glitch-soc/mastodon#491]
Using glitch-soc 2.4.0rc3 with the mastodon flavour, the setting "Show confirmation dialog before favouriting" has no effect

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by yipdw** [comment]
Is this something that the Mastodon flavour supports? AFAICT, tootsuite has no setting for this: https://github.com/tootsuite/mastodon/blob/master/app/lib/user_settings_decorator.rb#L17

**Comment by kit-ty-kate** [comment]
no it does not

**Comment by kit-ty-kate** [comment]
but at least there should be a sign saying that it's not supported in mastadon flavour or don't show it in case the mastodon flavour is enabled.

**Comment by yipdw** [comment]
I think the former option (putting up an indication that it's a glitch-only thing) is easier to maintain; the preference pages aren't controlled by the flavour system.
