### ISSUE TITLE
Bookmark icon should have a different color (red)

### ISSUE THREAD

**Issue by ThibG** [glitch-soc/mastodon#493]
It has been suggested that the bookmark icon should be red rather than have the default blue highlight color.

I'm not too sure about adding anything not already in the color scheme, but here is an issue to track that.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
'it has been suggested' <3

**Comment by wxcafe** [comment]
my point here is that it's an icon, which can vary color as the "favourite" icon shows already, and it removes the confusion with boost being blue already. Red looks like the obvious candidate with being associated with bookmarks in general
