### ISSUE TITLE
Light theme suggestions

### ISSUE THREAD

**Issue by Cassolotl** [glitch-soc/mastodon#496]
There's a black bar between images in the light theme that isn't there on the vanilla theme, which I think looks a little out of place?

![screen shot 2018-05-20 at 13 22 01](https://user-images.githubusercontent.com/6607512/40278872-0b2d5d2a-5c31-11e8-9cdf-c322eb9c892a.png)
![screen shot 2018-05-21 at 13 07 36](https://user-images.githubusercontent.com/6607512/40306819-03761b5e-5cf8-11e8-8659-f386b3de2d49.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
Tags (links generally?) and the "close" X on the reply UI are not high-contrast enough:

![screen shot 2018-05-20 at 13 25 00](https://user-images.githubusercontent.com/6607512/40278888-3b34b9be-5c31-11e8-9fab-40e5c14da684.png)

**Comment by Cassolotl** [comment]
When you like something, the star spins but doesn't change colour - you have to reload the page to see it turn yellow.

**Comment by Cassolotl** [comment]
The unselected titles and icons on the privacy dropdown are too low contrast.

![screen shot 2018-05-21 at 10 08 33](https://user-images.githubusercontent.com/6607512/40301489-315f0008-5ce4-11e8-932a-232a19e2a96f.png)

**Comment by Cassolotl** [comment]
I've deleted the ones that are not Glitch-specific, and put them on the general Mastodon issue list: https://github.com/tootsuite/mastodon/issues/7566

**Comment by ThibG** [comment]
The black bar is actually the whole media “area” having a background, which makes more sense when letterboxing is enabled.

Only showing it when letterboxing is enabled would require a bit of work, but might be the best solution.

We could also use a different color, but I am not sure which one.

**Comment by Cassolotl** [comment]
Ohhh yeah, that black background! Alright, now I know why it's there I'm happy to close this. :)

**Comment by Cassolotl** [comment]
Yeah, I played with the media settings on dev.glitch.social and the background looks strange. Maybe the light theme can include light backgrounds for media? (No idea if this is possible or good but I thought I'd suggest it!)

**Comment by ThibG** [comment]
Fixed by be644e3b7cd441650d2657914917df08104e3b46
