### ISSUE TITLE
[glitch] Toots are uncollasped when you go back to profile

### ISSUE THREAD

**Issue by Tagadda** [glitch-soc/mastodon#497]
Step to reproduce : 
* From the web client, click on a profile.
* See a pinned auto-collapsed toot
* Click on a non-collapsed toot
* Go back to profile (with the arrow at the top of the column)

Expected behaviour : The pinned toot is still collapsed.

Actual behaviour : The pinned toot is un-collapsed.

I don't know if this happens only with pinned toots.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment]
This is the “auto-collapse lengthy toots” not being reliable because the toot isn't actually drawn when `clientHeight` is called. I am not sure how to fix that…
