### ISSUE TITLE
Can't interact with collapsed media toot without text

### ISSUE THREAD

**Issue by Tagadda** [glitch-soc/mastodon#547]
My client auto-collapse toots with media.
Since the last Mastodon update, toot with media does not require text (usually '.').

So this happens : 
![image](https://user-images.githubusercontent.com/36127788/41510264-a77e25d8-7261-11e8-9aa2-566c175a4cd7.png)

I can not click on anything else the profile picture or the image.

Unrelated : You can also notice that the "fav" button isn't in the good color.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a master.

**Comment by yipdw** [comment]
Hmm.  We might have to insert an interactive text block for collapsed media; maybe something like "(Media hidden, click to view)"?

**Comment by Tagadda** [comment]
I was thinking about making the "collapse icon" interactive, is it possible ?

**Comment by yipdw** [comment]
Oh, the collapse icon isn't interactive? That's weird.  (I've never tried clicking on it.)  But, yes, that would probably also be a good way to go.

**Comment by Tagadda** [comment]
In fact, the uncollapse icon isn't interactive on every toot with media.

**Comment by ThibG** [comment]
It is supposed to be interactive on every toot, media or not, and it is here.
I'll investigate further.
