### ISSUE TITLE
Switch from Travis to CircleCI

### ISSUE THREAD

**Issue by ThibG** [glitch-soc/mastodon#559]
A while ago, upstream switched from Travis to CircleCI, which speeds up CI runs.

We maintained the Travis-based CI in the meantime, but there are some discrepancies and this is becoming a pain.

I'm not too sure what switching from Travis to Circle CI would entail with regards to depending on a third-party, though.

EDIT: PR which switched from Travis to CircleCI upstream: https://github.com/tootsuite/mastodon/pull/7196 ; also, I've subscribed to a free CircleCI plan, but it needs approval by the glitch-soc org to be used there

**Comment by yipdw** [comment]
At one point, Travis updates made it into the Discord server (https://discord.gg/8D5wGH).  That doesn't seem to be the case anymore, though, so it's probably okay to drop Travis and just use the CircleCI build script.

Who in the organization can approve the plan?

**Comment by ThibG** [comment]
@marrus-sh and @beatrix-bitrot are the ones who can accept the plan, as far as I know.

In the meantime, I have found a workaround to the CI issue we get when merging from upstream, so it's not urgent…
