### ISSUE TITLE
Remove remote media with rake task not work

### ISSUE THREAD

**Issue by Dryusdan** [glitch-soc/mastodon#594]
Hello
Today I would clean my public/system folder with rake task `RAILS_ENV=production bundle exec rake mastodon:media:remove_silenced`. But, on Mastodon instance this command work, but on my glitch social instance, this not work. The only message on rake task is it :  `Scoped order is ignored, it's forced to be batch order.`

Thank for your help :)
Regard

Dryusdan

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on `master`

**Comment by Tagadda** [comment]
I think this is now queued in Sidekiq.

**Comment by rhaamo** [comment]
Yes I think ```mastodon:media:remove_silenced``` works like ```mastodon:media:remove_remote``` the rake exec will exit immediatly but the actions are all queued in sidekiq.

**Comment by Dryusdan** [comment]
Okay, so sidekiq delete automaticaly remote file (sorry, I mistake between silcend and remote...) ?

But why on Mastodon instance this command return all deleted file and not here ? :thinking:

**Comment by ThibG** [comment]
Both Mastodon (since 2.4.1rc1) and glitch-soc should delete those files asynchronously through sidekiq when you run that rake task.
So neither Mastodon nor glitch-soc should give you immediate feedback. However, if no media ends up being removed, then it's a bug.

(I'll run the task on my instance and see what happens)

**Comment by Dryusdan** [comment]
Okay, thank you :)

@Tagadda the instance where is test is not up to date but there is on v2.4.2

@ThibG I'm not sure if this working on my instance :thinking: . I have to question : 
- Rake task can follow symlink ?
- 25Go of media file for a little instance is not too heavy ? :)

When I go to the media over 30 days old on external profile in member space or on admin space, my browser not download image on other domain  but on my domain, so I'm wondering.

:)

**Comment by rhaamo** [comment]
> When I go to the media over 30 days old on external profile in member space or on admin space, my browser not download image on other domain but on my domain, so I'm wondering.

Mastodon does cache the remote medias, you have to use ```remove_remote``` regulary to clean them, see: https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/List-of-Rake-tasks.md#media-storage

**Comment by Dryusdan** [comment]
I use this command each night, but it look no effect :/

**Comment by davidmaitland** [comment]
I'm trying to figure this out too. If we're using docker-compose for our deployment do we need to run `mastodon:media:remove_remote` as a cron or something? Why isn't this in Sidekiq as a recurring job like `media_cleanup_scheduler`?

```
docker-compose run --rm web bundle exec rake mastodon:media:remove_remote
Starting mastodon_es_1    ... done
Starting mastodon_redis_1 ... done
Starting mastodon_db_1    ... done
Scoped order is ignored, it's forced to be batch order.
```

That doesn't seem to do anything, my bucket size is the same as before.

**Comment by Dryusdan** [comment]
I use a cron but I have a standalone install of glitch.
This rake task add a sidekiq task and this remove media.

But, I don't know how work this rake task in Docker :/ sorry

**Comment by ThibG** [comment]
@davidmaitland uploaded but unattached media files are useless (which happen for instance if you upload some media but never post the toot you were composing) and should be cleaned up, which `media_cleanup_scheduler` does.
However, remote media make more sense to keep, as they can still be useful if a user stumbles on them. Hence why this hasn't been pushed to a recurring sidekiq job, I guess.

As stated earlier in this issue, the `mastodon:media:remove_remote` tasks returns immediately after queuing deletion tasks. That means the cleaning itself will happen asynchronously.

Now, there might be a bug in the cleaning up process, but in my limited testing, I haven't been able to find one.

**Comment by davidmaitland** [comment]
@ThibG right, but I just want to ensure my AWS bill doesn't get too out of hand storing files that are rarely used.

I'm actually on `tootsuite/mastodon` and not `glitch-soc` so might only be an issue over there, but running `mastodon:media:remove_remote` doesn't seem to decrease my bucket size. I'm not sure how to verify this?

Either way having to run a cron on a docker host is a bit hacky..

```
docker-compose run --rm web bundle exec rake mastodon:media:remove_remote
Starting mastodon_es_1    ... done
Starting mastodon_redis_1 ... done
Starting mastodon_db_1    ... done
Scoped order is ignored, it's forced to be batch order.
```

**Comment by ThibG** [comment]
@davidmaitland I don't think here is the proper avenue to discuss upstream code. Also, I don't know about AWS, sorry.

To everyone else: the task has been updated, both here and upstream (in master) to display the number of queued jobs (so that you know that it's doing *something*). Moreover, the backend used by Mastodon for local file storage wasn't safe for concurrent use (at least in the case of deletions), so it has been changed. This should lead in some more files being successfully deleted, and avoid the tons of confusing errors and failed jobs.

**Comment by sireebob** [comment]
it's also now been deprecated in favor of bin/tootctl, which can be run either synchronously with --no-background, the default, or async through sidekiq with --background
https://github.com/tootsuite/mastodon/commit/793eea29823a44fd4950f87898ecf0ff3b49351d

**Comment by ThibG** [comment]
Closing, please reopen if you still have issues with the new version of those tools.
