### ISSUE TITLE
User option to disable emoji-replacement

### ISSUE THREAD

**Issue by igalic** [glitch-soc/mastodon#647]
By default, mastodon replaces emoji in the with an html `img` tag, that contains an svg Emojione image. For example:

```html
<img draggable="false" class="emojione" alt="☺️" 
  title=":relaxed:" src="https://static.glitch.social/emoji/263a.svg">
```

I'd like to make it easier for this feature to be disabled.
Either by admins, upon installing the instance, or perhaps even to expose it as a user-preference choice… this could become part of glitch-soc's "flavours"

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ticky** [comment]
I’d vote for a checkbox alongside the “use system font” switch.

p.s. it’s also possible to detect native emoji support in a user’s browser using something like [mojibaka](https://www.npmjs.com/package/mojibaka) (disclosure: it’s my project) so it could be made to be off unless the browser needs replacements.

**Comment by igalic** [comment]
I've started toying with this again, to see what I can do from my side without writing any code.

It appears i can Block the URL `||static.glitch.social/emoji/$image` in uBlock, if I also disable `Hide placeholders of blocked elements`

And that only breaks the Emoji Picker. So if someone was to really implement this, they'd also have to configure the [emoji-mart](https://github.com/missive/emoji-mart#emoji) to use `native => true` in the case that a user selects system emoji.

**Comment by ThibG** [comment]
Would it be fine as a local app setting (I mean, a setting set from the settings modal specific to the glitch flavour)? This would not apply to public pages

**Comment by igalic** [comment]
i believe that's what "User Option" means, exactly.

**Comment by ThibG** [comment]
I asked that because there was a suggestion to put it in the server-side thing

> I’d vote for a checkbox alongside the “use system font” switch.

But I'd rather not pass it to the public pages (because there is no readily-system available for that and I don't want to mess with the vanilla parts much more)
