### ISSUE TITLE
Image background on collapsed posts even when disbaled

### ISSUE THREAD

**Issue by yiskah** [glitch-soc/mastodon#65]
Not sure why but even if I uncheck "give collapsed toots image background" it still does it anyway. On Firefox in Windows. 

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by MightyPork** [comment]
odd, works fine here - Chrome and Firefox on Linux

**Comment by yiskah** [comment]
Could you try it in windows? Is that available? It's probably a different codebase on Windows

**Comment by Fidgetcetera** [comment]
Is this still happening for you? Windows 7 Firefox 54.01 here, I have "preview collapsed toot media" and "give collapsed toots an image background" both disabled and I don't appear to get either.

**Comment by yiskah** [comment]
It appears to have been fixed

**Comment by yiskah** [comment]
Closing cuz fixed
