### ISSUE TITLE
Add option to always display full handles for mentions

### ISSUE THREAD

**Issue by hoodieak** [glitch-soc/mastodon#666]
users need to be able to see where their toots are going when DMing and other sensitive actions.

i propose, at the very least, the option to set @user@instance.uri to be visible 100% of the time as a user setting, in addition to hovering a mention always showing the full location of that user, when the option is disabled. this saves a click for many a user.

**Comment by ThibG** [comment]
Well, when DMing, the compose box always has fully-expanded handles. Granted, in the toots as rendered in the timelines, that's not the case. As for displaying the full handle on hovering mentions, that's already the case, isn't it?

**Comment by hoodieak** [comment]
not sure. still want an option for always showing full @ in timelines and columns
