### ISSUE TITLE
Up patch version from 3 to 4 to be in sync with upstream 

### ISSUE THREAD

**Issue by MxFraud** [glitch-soc/mastodon#667]
The security update in 2.4.4 has been merge on glitch-soc (thank you for that) but the version didnt get updated.
Here is the upstream commit https://github.com/tootsuite/mastodon/commit/612d02028c9b33cda250207778ed3cb7fb24e317

Thank you

* * * *

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
This is because we are based on master and not the 2.4 release branch. I'm not sure it makes much sense to change the version this way.

**Comment by MxFraud** [comment]
It was mostly asking to be able to tell apart an instance with the security problem to one that has been fixed.
Maybe the commit ID is already showing somewhere else in the UI and I just haven't found it.
Happy to close the issue either way.

**Comment by ThibG** [comment]
Fixed, as upstream has bumped to 2.5.x and we merged that.
