### ISSUE TITLE
Back button in right column always returns to /web/getting-started

### ISSUE THREAD

**Issue by ekiru** [glitch-soc/mastodon#70]
The Back button that displays on top of the right column always takes me back to /web/getting-started, no matter how many intermediate things I've been to. The browser's back functionality works fine though.

To reproduce:
1. Click a status.
2. In the detailed status view that 1 opens on the right, click the user name to open the user's profile.
3. Click the Back button on top of the column.

Expected behavior:
The rightmost column returns to the detailed status view.

Observed behavior:
The rightmost column returns to the getting-started view.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by MightyPork** [comment]
I'm going to close this. It's still sometimes bugged, but in a different way
