### ISSUE TITLE
Clacks do not display in web app

### ISSUE THREAD

**Issue by marrus-sh** [glitch-soc/mastodon#750]
I'm making this issue here but it's also a problem upstream. (I'm just not expecting upstream to care.)

Right now the `X-Clacks-Overhead` configured in sites like glitch.social, dev.glitch.social does not appear on the web app (`/web/`) even though it does appear in other places (`/about/more`).

Since the web app is the location that users spend most of their time in, it would be nice if the overhead was made available there.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bugs also occur on vanilla Mastodon

**Comment by yipdw** [comment]
Seems okay? I tried it in curl:

```
$ curl -v https://dev.glitch.social/web 2>&1 | grep -i x-clacks
< x-clacks-overhead: GNU Natalie Nguyen
```

(The header name is lowercase, but IIRC HTTP headers are case-insensitive)

**Comment by barzamin** [comment]
Maybe kibi is talking about a visual indication? idk

**Comment by marrus-sh** [comment]
hUH

you all appear to be correct

i was in fact running off of the visual indication offered by https://addons.mozilla.org/en-US/firefox/addon/gnu_terry_pratchett/ in Firefox, which shows on non-web-app pages but gives an empty overhead in the web app

but checking the network response it is indeed the exact same

which makes me think that this is instead caused by JS history state magicks and perhaps not fixable on our end.

the thing is that it definitely used to work with this addon, though 🤔
