### ISSUE TITLE
Enabling reduced motion prevents the boost button from dimming for private statuses

### ISSUE THREAD

**Issue by barzamin** [glitch-soc/mastodon#756]
As in title. Verified on d.g.s.

**This post was submitted on behalf of @ashkitten.**

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
This has been fixed a few weeks ago in ac6fb758b975ec2858c53be24f8e9be8e2d40e90.
I just don't think d.g.s is up-to-date.

**Comment by barzamin** [comment]
Awesome, thanks!
