### ISSUE TITLE
Figure out how to move to upstream's expand_spoilers preference

### ISSUE THREAD

**Issue by ClearlyClaire** [glitch-soc/mastodon#760]
Upstream has implemented an `expand_spoilers` settings in commit 1889526e23ce41a37395fdcf89bd415bb2f7546f, which is similar to our “CW auto-unfold” local-setting with the following differences:
- It is stored server-side and set through the preferences page (/settings/preferences)
- It also applies to public pages (when you are logged in)
- It doesn't have an option to blacklist some CWs from auto-unfolding

Currently, we ignore this setting in the glitch-soc flavor and use our local-setting instead, which is more flexible but is probably confusing.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by KonomiKitten** [comment]
As a user who recently ran into this, I do find it extremely confusing.

**Comment by KonomiKitten** [comment]
Hi could we have some action on this, while it's nice this can be done I  the browser I'm starting to wonder if my favourite Android client tusky can't expand spoilers because the server api isn't implemented right in this fork.

**Comment by ThibG** [comment]
The server-side API is kept untouched. Tusky simply doesn't have this feature (https://github.com/tuskyapp/Tusky/issues/927).

I would still like to have something consistent with the server-side setting (which is currently only used in the vanilla flavor), but I still can't think of a migration path :/
