### ISSUE TITLE
try webpack-chunk-hash thing to end our hell of cache problems

### ISSUE THREAD

**Issue by beatrix-bitrot** [glitch-soc/mastodon#83]
sometimes packs (most notably application.js) are built with the same chunkhashes even though the contents differ. this causes weird intermittent problems

try using this:

https://github.com/alexindigo/webpack-chunk-hash

to fix it, or badger someone into fixing it in upstream maybe. also acceptable.

**Comment by yipdw** [comment]
Is this problem still occurring?

**Comment by beatrix-bitrot** [comment]
last time i stopped clobbering assets when deploying dev it did happen yeah :c

**Comment by ThibG** [comment]
I don't think this is happening anymore? Closing. Please reopen if there is any issue ~
