### ISSUE TITLE
Do not include instance-local-only toots in the federated timeline

### ISSUE THREAD

**Issue by ThibG** [glitch-soc/mastodon#846]
While this is not a privacy issue (local-only toots are only displayed to logged-in users), local-only toots are inserted in the federated timeline, which might be misleading.

It may make sense to not display them there.

I am not completely sure which way it should be as I tend to see the community timeline as a subset of the federated timeline.

**Comment by ThibG** [comment]
Hm… there is a bit of an issue here: the WebUI adds any public toot you post yourself into the public timeline (not waiting to get it back from the streaming API). This can be easily fixed in the glitch-soc flavor, but it would also need fixing in the vanilla one, which we have tried not to modify so far…
Should I patch both?

**Comment by ptah4i** [comment]
It makes sense to separate both timelines.
