### ISSUE TITLE
"Hide your followers count" still visible in mobile and text-based browsers

### ISSUE THREAD

**Issue by trashyfins** [glitch-soc/mastodon#873]
Desktop web UI will not display follower count, but it will show up in a mobile browser. Setting "request desktop site" on mobile will open the desktop version of the profile and the follower count is not displayed.

Testing in both elinks and lynx show the follower count, as well.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment]
Oh, we are talking about public pages and not the WebUI. I can reproduce it and I indeed missed one place where followers count is inserted. Will fix it shortly.
