### ISSUE TITLE
Browser interface crashes when clicking multiple hashtags in column search

### ISSUE THREAD

**Issue by trashyfins** [glitch-soc/mastodon#875]
When searching (clicking) more than one tag, the Mastodon browser UI will crash.

Steps to reproduce:
* Search a tag "foo"
* Click on one of the provided tags in the search column
* If more than one tag is provided back, click another (this also happens when searching [and subsequently clicking] a second tag while leaving the first expanded tag column open)

Instance commit is currently sitting at master (115b1abb6e30517f)

Info provided via crash debug:

Stack trace
-----------

```
t/<@https://chomp.life/packs/flavours/glitch/home-024b14efa45f20c9b5ef.js:1:881400
ca@https://chomp.life/packs/flavours/glitch/home-024b14efa45f20c9b5ef.js:1:262887
ua@https://chomp.life/packs/flavours/glitch/home-024b14efa45f20c9b5ef.js:1:263004
da@https://chomp.life/packs/flavours/glitch/home-024b14efa45f20c9b5ef.js:1:264643
pi@https://chomp.life/packs/flavours/glitch/home-024b14efa45f20c9b5ef.js:1:281609
di@https://chomp.life/packs/flavours/glitch/home-024b14efa45f20c9b5ef.js:1:278854
fi@https://chomp.life/packs/flavours/glitch/home-024b14efa45f20c9b5ef.js:1:278470
vi@https://chomp.life/packs/flavours/glitch/home-024b14efa45f20c9b5ef.js:1:284707
Cn@https://chomp.life/packs/flavours/glitch/home-024b14efa45f20c9b5ef.js:1:229898

```

React component stack
---------------------

```

    in Connect(InjectIntl(t))
    in div
    in div
    in a
    in HotKeys
    in t
    in a
    in withRouter(t)
    in InjectIntl(withRouter(t))
    in Connect(InjectIntl(withRouter(t)))
    in a
    in a
    in a
    in withRouter(a)
    in t
    in t
    in t
    in o
    in IntlProvider
    in t
```

A couple of others using Glitch-Soc have confirmed that they have the same crash problem ([thread here](https://chomp.life/@trashyfins/101326626142599120)).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
I can reproduce it, and it also occurs on vanilla Mastodon. On it.
