### ISSUE TITLE
Better home feed algorithm

### ISSUE THREAD

**Issue by SoniEx2** [glitch-soc/mastodon#891]
### Pitch

The current home feed algorithm adds toots to the home feed based on whether the reply-to *user* is someone you follow (or it doesn't have a reply-to).

(I realize "reply-to" isn't the right name for it and it's actually a special way of using the "to" field, but regardless.)

I'd like to see an algorithm that instead looks at the existing toots on your home feed. If the reply-to *toot* is on the home feed, then the reply should also show up.

### Motivation

If user A replies to B who replied to C, and you don't follow C, you currently see A's reply. This change would solve that without removing all replies from the home feed. More specifically, your mutuals' replies would still show up with this change.

This would not be efficient to implement using the REST API, unless you like your server's API endpoints getting absolutely hammered. I do not recommend using any third party client that implements this filtering on a public instance you don't control.

**Comment by ThibG** [comment]
From a design viewpoint, I can see the how this could be considered an improvement. What about a conversation that becomes one between two people you follow, but has started with someone else in the loop, though?

From a technical viewpoint, this sounds a bit difficult to do efficiently. Indeed, your “home feed” is stored in memory as a list of 400 toots max. With your proposal, when someone you follow replies to a toot, if that toot is not in those last 400 toots, you would have to load it from database *and* check its full ancestry until finding the “root” status to know whether it was authored by someone you follow.

**Comment by SoniEx2** [comment]
I wasn't too heavy on the details, but you'd definitely use a bloom filter (or maybe a counting bloom filter). You also wouldn't keep going beyond the 400 home feed toots. (I don't see it being particularly useful to do otherwise.)

It's probably safe to add another check to see if it's a reply to a toot of your own, tho.

**Comment by ThibG** [comment]
Not going behind the 400 home feed toots: that would prevent you from seeing conversations between your followers if your TL is active and one of the participants takes too much time to reply. That can happen.

**Comment by ashkitten** [comment]
fwiw, i am currently following 239 users, and i don't think that's "anti-friendship" - i interact with the majority of the folx i follow on a regular basis

**Comment by yipdw** [comment]
@SoniEx2: Ordinarily, we'd appreciate the contribution, but your earlier ban from glitch-soc project spaces still stands.  Please do not create new issues in this project or comment on existing ones.

**Comment by SoniEx2** [comment]
what ban??? are you sure you're not mistaking me for someone else? (or thinking of another project)
