### ISSUE TITLE
TypeError: Cannot read property 'getWrappedInstance' of null

### ISSUE THREAD

**Issue by rtucker** [glitch-soc/mastodon#926]
Greetings...

We're getting a lot of these on vulpine.club as of late, usually when a network connection changes. We're a few days behind master.

I'll add more details once I am at a real computer... just wanted to get this out of my copy buffer :)

Stack trace
-----------

```
TypeError: Cannot read property 'getWrappedInstance' of null
    at https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:893558
    at wa (https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:275944)
    at Oa (https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:276255)
    at Ea (https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:277919)
    at Ni (https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:296285)
    at Di (https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:293624)
    at Mi (https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:292976)
    at Si (https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:291997)
    at ti (https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:290917)
    at Object.enqueueSetState (https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:255314)
```

React component stack
---------------------

```

    in InjectIntl(e)
    in Connect(InjectIntl(e))
    in Connect(InjectIntl(e))
    in div
    in div
    in t
    in r
    in e
    in i
    in withRouter(e)
    in InjectIntl(withRouter(e))
    in Connect(InjectIntl(withRouter(e)))
    in i
    in a
    in i
    in withRouter(a)
    in i
    in i
    in e
    in e
    in IntlProvider
    in t
```

**Comment by ThibG** [comment]
I'm pretty sure this has been fixed earlier this week!

Le 21 février 2019 18:17:05 GMT+01:00, Rey Tucker <notifications@github.com> a écrit :
>Greetings...
>
>We're getting a lot of these on vulpine.club as of late, usually when a
>network connection changes. We're a few days behind master.
>
>I'll add more details once I am at a real computer... just wanted to
>get this out of my copy buffer :)
>
>Stack trace
>-----------
>
>```
>TypeError: Cannot read property 'getWrappedInstance' of null
>at
>https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:893558
>at wa
>(https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:275944)
>at Oa
>(https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:276255)
>at Ea
>(https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:277919)
>at Ni
>(https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:296285)
>at Di
>(https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:293624)
>at Mi
>(https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:292976)
>at Si
>(https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:291997)
>at ti
>(https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:290917)
>at Object.enqueueSetState
>(https://cdn-assets.vulpine.owogroupllc.com/packs/flavours/glitch/home-dafc95774543506ca474.js:1:255314)
>```
>
>
>React component stack
>---------------------
>
>```
>
>    in InjectIntl(e)
>    in Connect(InjectIntl(e))
>    in Connect(InjectIntl(e))
>    in div
>    in div
>    in t
>    in r
>    in e
>    in i
>    in withRouter(e)
>    in InjectIntl(withRouter(e))
>    in Connect(InjectIntl(withRouter(e)))
>    in i
>    in a
>    in i
>    in withRouter(a)
>    in i
>    in i
>    in e
>    in e
>    in IntlProvider
>    in t
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/glitch-soc/mastodon/issues/926

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by rtucker** [comment]
Awesome... we're at 1aa87a1967b37e9f118b87ee643944798d3c90f4 right now, I'm gonna merge up to see if this fixes it :)

(this make take a few hours)

**Comment by rtucker** [comment]
Looks like this is, indeed, fixed!  Thanks :)
