### ISSUE TITLE
Mastodon Custom CSS field no longer applies

### ISSUE THREAD

**Issue by GibsonGibson** [glitch-soc/mastodon#933]
Custom CSS field in Admiin panel does not apply to default user experience. Is there any way to change this, or is it not supported due to custom flavours?

**Comment by ThibG** [comment]
It does still apply. However, there are some parts of the markup that are different in both flavours, so that may be one issue.
Additionally, having a quick look at hackers.town, it seems like it is trying to load external images in a way that is forbidden by the Content Security Policy (which might be stricter than upstream's, I'd have to check).

**Comment by GibsonGibson** [comment]
That is true... I am pointed at a background image else where...

I have noticed since posting that certain parts of the custom CS are applying, but none of the colors or background image...

I'll tweak it and see where I can get.

**Comment by GibsonGibson** [comment]
Below is the custom CSS load... working parts are commented out.

.account__header .account__header__fields dd,
.public-account-bio .account__header__fields dd,
.drawer__inner, .drawer__inner__mastodon {
background-color: #000000;
}

##a.status-link:not(.mention) {
##text-decoration: underline;
##}

.drawer__inner, .drawer__inner__mastodon {
background-color: transparent;
opacity: 0.90;
}

.column {
background-color: transparent;
opacity: 0.90;}

.ui, .landing-page, .public-layout {
background-image: url("https://hackers.town/system/media_attachments/files/000/664/431/original/22394ee850a45c70.jpg");
background-size: cover;
background-repeat: no-repeat;
background-position: center;

.detailed-status__action-bar {
background-color:#000000;
}

.compose-form__buttons-wrapper {
background-color:#000000;
}

**Comment by ThibG** [comment]
Sorry for the late reply. Can you check whether #982 helps?

**Comment by GibsonGibson** [comment]
I forgot to update.

I found a mistake in my CSS that apparently pasted wrong when I moved it over.

All is well.

**Comment by ThibG** [comment]
Just a heads up that starting with https://github.com/glitch-soc/mastodon/pull/1277 you can easily use images from other origins by making use of the `EXTRA_DATA_HOSTS` environment variable
