### ISSUE TITLE
Custom Emoji not correctly displayed in polls

### ISSUE THREAD

**Issue by Feufochmar** [glitch-soc/mastodon#956]
See for instance: https://donphan.social/@Feufochmar/101733747157114319
donphan.social uses glitch-soc, and I put custom emoji in the poll options. The poll options doesn't show the emoji, but their text representation.

As I haven't checked if it's also present in vanilla (I don't have an account on a vanilla server supporting polls), I'm reporting there. However, I can tell that on servers that are not up-to-date for displaying polls, the custom emoji are correctly displayed in the toot.

**Comment by ThibG** [comment]
This is an upstream issue. See https://github.com/tootsuite/mastodon/pull/10322
