### ISSUE TITLE
searches that return custom emoji crash the frontend

### ISSUE THREAD

**Issue by BenLubar** [glitch-soc/mastodon#967]
Emoji searches that return custom emoji crash the entire frontend. This is because `short_names` is not assigned for custom emoji.

/cc @undergroundmonorail

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [unknown] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
This is a bug in emoji-mart, see https://github.com/tootsuite/mastodon/issues/10315

**Comment by BenLubar** [comment]
Can we go back to a previous version of emoji-mart that didn't exhibit this issue?

**Comment by ThibG** [comment]
Yeah. Reverted that.
