### ISSUE TITLE
Allow larger subset of html in posts

### ISSUE THREAD

**Issue by transitracer** [glitch-soc/mastodon#993]
### Pitch

Don't sanitize away as many html elements.

### Motivation

This allows proper viewing of many posts made using pleroma and other software not correctly viewable otherwise on mastodon. It would be a relatively trivial sanitizer config change, with just small modifications to `app/lib/sanitize_config.rb`. Pleroma's default html scrubber configuration can be found [here](https://git.pleroma.social/pleroma/pleroma/blob/73df3046e014ae16e03f16a9c82921652cefcb54/lib/pleroma/html.ex#L142), but if the wish wasn't to completely replicate pleroma's rules, any opening up of the possible formatting options would be welcome.

**Comment by ThibG** [comment]
I'm inclined to allow most, if not all of what pleroma currently allows, but we also have to make sure the CSS for it is decent.

**Comment by ThibG** [comment]
Forgot to mark https://github.com/glitch-soc/mastodon/pull/994 as fixing this.
